.slot 2
.section "Enemy, name, item lists" superfree
Lists:

Items:  
  String " " 
  
  String "<A> Wood Cane"                    
  String "<A> Short Sword"                  
  String "<An> Iron Sword"                  
  String "<A> Psycho Wand"                  
  String "<A> Silver Tusk"                  
  String "<An> Iron Axe"                    
  String "<A> Titanium Sword"               
  String "<A> Ceramic Sword"                
  String "<A> Needle Gun"                   
  String "<A> Saber Claw"                   
  String "<A> Heat Gun"                     
  String "<A> Light Saber"                  
  String "<A> Laser Gun"                    
  String "<A> Laconian Sword"               
  String "<A> Laconian Axe"                 

  String "<A> Leather Clothes"              
  String "<A> White Mantle"                 
  String "<A> Light Suit"                   
  String "<An> Iron Armor"                  
  String "<A> Spiky Squirrel Fur"           
  String "<A> Zirconia Mail"                
  String "<A> Diamond Armor"                
  String "<A> Laconian Armor"               
  String "<The> Frad Mantle"                

  String "<A> Leather Shield"               
  String "<An> Iron Shield"                 
  String "<A> Bronze Shield"                
  String "<A> Ceramic Shield"               
  String "<An> Animal Glove"                
  String "<A> Laser Barrier"                
  String "<The> Shield of Perseus"          
  String "<A> Laconian Shield"              

  String "<The> LandMaster"                 
  String "<The> FlowMover"                  
  String "<The> IceDecker"                  

  String "<A> PelorieMate"                  
  String "<A> Ruoginin"                     
  String "<The> Soothe Flute"               
  String "<A> Searchlight"                  
  String "<An> Escape Cloth"                
  String "<A> TranCarpet"                   
  String "<A> Magic Hat"                    
  String "<An> Alsuline"                    
  String "<A> Polymeteral"                  
  String "<A> Dungeon Key"                  
  String "<A> Telepathy Ball"               
  String "<The> Eclipse Torch"              
  String "<The> Aeroprism" 
  String "<The> Laerma Berries"             
  String "Hapsby"                           
  String "<A> Roadpass"                     
  String "<A> Passport"                     
  String "<A> Compass"                      
  String "<A> Shortcake"                    
  String "<The> Governor[-General]'s Letter"
  String "<A> Laconian Pot"                 
  String "<The> Light Pendant"              
  String "<The> Carbuncle Eye"              
  String "<A> GasClear"                     
  String "Damoa's Crystal"                  
  String "<A> Master System"                
  String "<The> Miracle Key"                
  String "Zillion"                          
  String "<A> Secret Thing"                 

Names:
  String "Alisa"                            
  String "Myau"                             
  String "Tairon" 
  String "Lutz"                             

Enemies:
  String " " 
  String "<The> Monster Fly"                
  String "<The> Green Slime"                
  String "<The> Wing Eye"                   
  String "<The> Maneater"                   
  String "<The> Scorpius"                   
  String "<The> Giant Naiad"                
  String "<The> Blue Slime"                 
  String "<The> Motavian Peasant"           
  String "<The> Devil Bat"                  
  String "<The> Killer Plant"               
  String "<The> Biting Fly"                 
  String "<The> Motavian Teaser"            
  String "<The> Herex"                      
  String "<The> Sandworm"                   
  String "<The> Motavian Maniac"            
  String "<The> Gold Lens" 
  String "<The> Red Slime"                  
  String "<The> Bat Man"                    
  String "<The> Horseshoe Crab"             
  String "<The> Shark King"                 
  String "<The> Lich"                       
  String "<The> Tarantula"                  
  String "<The> Manticort"                  
  String "<The> Skeleton"                   
  String "<The> Ant-lion"                   
  String "<The> Marshes"                    
  String "<The> Dezorian"                   
  String "<The> Desert Leech"               
  String "<The> Cryon"                      
  String "<The> Big Nose"                   
  String "<The> Ghoul"                      
  String "<The> Ammonite" 
  String "<The> Executor"                   
  String "<The> Wight"                      
  String "<The> Skull Soldier"              
  String "<The> Snail"                      
  String "<The> Manticore"                  
  String "<The> Serpent"                    
  String "<The> Leviathan"                  
  String "<The> Dorouge"                    
  String "<The> Octopus"                    
  String "<The> Mad Stalker"                
  String "<The> Dezorian Head"              
  String "<The> Zombie"                     
  String "<The> Living Dead"                
  String "<The> Robot Police"               
  String "<The> Cyborg Mage"                
  String "<The> Flame Lizard" 
  String "Tajim"                            
  String "<The> Gaia"                       
  String "<The> Machine Guard"              
  String "<The> Big Eater"                  
  String "<The> Talos"                      
  String "<The> Snake Lord"                 
  String "<The> Death Bearer"               
  String "<The> Chaos Sorcerer"             
  String "<The> Centaur"                    
  String "<The> Ice Man"                    
  String "<The> Vulcan"                     
  String "<The> Red Dragon"                 
  String "<The> Green Dragon"               
  String "LaShiec"                          
  String "<The> Mammoth"                    
  String "<The> King Saber"   
  String "<The> Dark Marauder"              
  String "<The> Golem"                      
  String "Medusa"                           
  String "<The> Frost Dragon"               
  String "Dragon Wise"                      
  String "<The> Gold Drake"                 
  String "<The> Mad Doctor"                 
  String "LaShiec"                          
  String "Dark Force"                       
  String "Nightmare"                        
.ends
