_BattlesAll:  .stringmap tilemap " Todas"
_BattlesHalf: .stringmap tilemap " Mitad"
_Brown: .stringmap tilemap "Marrón"
_Black: .stringmap tilemap " Negro"
_Font1: .stringmap tilemap "Polaris"
_Font2: .stringmap tilemap " DG2284"
_Normal:.stringmap tilemap "Normal"
_Fast:  .stringmap tilemap "Rápido"
