.slot 2
.section "Enemy, name, item lists" superfree
Lists:

Items:
; empty item (blank)
  String " "
; Armas         123456789012345678
  String  "<un> Bastón"
  String "<una> Espada Corta"
  String "<una> Espada de Hierro"
  String  "<un> Bastón Mágico"
  String  "<un> Colmillo de Plata"
  String "<una> Hacha de Hierro"
  String "<una> Espada de Titanio"
  String "<una> Espada de Cerámica"
  String "<una> Pistola de Agujas"
  String "<una> Garra Afilada"
  String "<una> Pistola de Calor"
  String  "<un> Sable de Luz"
  String "<una> Arma Láser"
  String "<una> Espada de Laconia"
  String "<una> Hacha de Laconia"
; Armaduras     123456789012345678
  String  "<un> Peto de Cuero"
  String  "<un> Mantel Blanco"
  String  "<un> Vestido Ligero"
  String "<una> Armadura de Hierro"
  String "<una> Piel Puntiaguda"
  String "<una> Malla de Zirconita"
  String "<una> Armadura de Diamante"
  String "<una> Armadura de Laconia"
  String  "<la> Capa de Fray"
; Escudos       123456789012345678
  String  "<un> Escudo de Cuero"
  String  "<un> Escudo de Bronce"
  String  "<un> Escudo de Hierro"
  String  "<un> Escudo de Cerámica"
  String  "<un> Guante Animal"
  String "<una> Barrera Láser"
  String  "<el> Escudo de Perseo"
  String  "<un> Escudo de Laconia"
; veículos      123456789012345678
  String  "<el> LandMaster"
  String  "<el> Aerodeslizador"
  String  "<el> Rompehielos"
; objetos       123456789012345678
  String  "<un> PelorieMate"
  String  "<un> Ruoginin"
  String  "<la> Flauta Calmante"
  String "<una> Linterna"
  String "<una> Capa de Fuga"
  String "<una> TeleAlfombra"
  String  "<un> Sombrero Mágico"
  String "<una> Alsulina"
  String  "<un> Polymeteral"
  String "<una> Llave de Mazmorra"
  String "<una> Bola Telepática"
  String  "<la> Antorcha de Eclipse"
  String  "<el> Aeroprisma"
  String "<los> Frutos de Laerma"
  String  "Hapsby"
  String  "<un> Salvoconducto"
  String  "<un> Pasaporte"
  String "<una> Brújula"
  String  "<un> Pastel"
  String  "<la> Carta del Gobernador[ General]"
  String "<una> Olla de Laconia"
  String "<el> Pendiente de Luz"
  String "<el> Ojo de Carbúnculo"
  String "<una> Máscara de Gas"
  String  "<el> Cristal de Damoa"
  String "<una> Master System"
  String  "<la> llave Milagrosa"
  String       "Zillion"
  String "<una> Cosa Secreta"
Names:
; Personajes
  String "Alisa"
  String "Myau"
  String "Tylon"
  String "Lutz"
Enemies:
; Monstres
; empty item (blank)
  String " "
  String "<el> Abejorro"
  String "<el> Limo Verde"
  String "<el> Ojo Volador"
  String "<el> Devorahombres"
  String "<el> Escorpión"
  String "<el> Escorpión Gigante"
  String "<el> Limo Azul"
  String "<el> Agricultor de Motavia"
  String "<el> Murcielago Perverso"
  String "<la> Planta Asesina"
  String "<el> Escorpión Asesino"
  String "<el> Tahur de Motavia"
  String "<el> Herex"
  String "<la> Lombriz de Tierra"
  String "<el> Maníaco de Motavia"
  String "<la> Lente Dorada"
  String "<el> Limo Rojo"
  String "<el> Hombre Murciélago"
  String "<el> Cangrejo Herradura"
  String "<el> Rey Tiburón"
  String "<el> Liche"
  String "<la> Tarántula"
  String "<la> Mantícora"
  String "<el> Esqueleto"
  String "<la> Hormiga León"
  String "<el> Hombree del Pantano"
  String "<el> Dezoriano"
  String "<la> Sanguijuela de Arena"
  String "<el> Vampiro"
  String "<el> Elefante"
  String "<el> Necrófago"
  String "<la> Ammonita"
  String "<el> Verdugo"
  String "<el> Alma en Pena"
  String "<el> Soldado Calavera"
  String "<el> Caracol"
  String "<la> Esfinge"
  String "<la> Serpiente"
  String "<el> Leviatán"
  String "<el> Opresor"
  String "<el> Pulpo"
  String "<el> Cazador Loco"
  String "<el> Cabecilla Dezoriano"
  String "<el> Zombi"
  String "<el> Muerto Viviente"
  String "<el> Policía Robot"
  String "<el> Mago Cyborg"
  String "<la> Salamandra"
  String "Tajim"
  String "<el> Titán"
  String "<el> Guardia Mecánico"
  String "<el> Tentáculo"
  String "<el> Talos"
  String "<la> Señora Serpiente"
  String "<el> Portador de Muerte"
  String "<el> Mago del Caos"
  String "<el> Centauro"
  String "<el> Hombre de Hielo"
  String "<el> Vulcano"
  String "<el> Dragón Rojo"
  String "<el> Dragón Verde"
  String "Lashiec"
  String "<el> Mamut"
  String "<el> Rey Centauro"
  String "<el> Caballero Negro"
  String "<el> Golem"
  String "Medusa"
  String "<el> Dragón de Hielo"
  String "<el> Dragón Sabio"
  String "<el> Dragón Dorado"
  String "<el> Doctor Loco"
  String "Lashiec"
  String "Fuerza Oscura"
  String "<el> Súcubo"

.ends
