.slot 2
.section "Enemy, name, item lists" superfree
Lists:

Items:
; empty item (blank)
  String " "
; Armas         123456789012345678
  String  "<um> Cajado"
  String "<uma> Espada Curta"
  String "<uma> Espada de Ferro"
  String  "<um> Cajado Mágico"
  String "<uma> Presa de Prata"
  String  "<um> Machado de Ferro"
  String "<uma> Espada de Titânio"
  String "<uma> Espada de Cerâmica"
  String "<uma> Pistola de Agulhas"
  String "<uma> Garra Afiada"
  String "<uma> Pistola de Calor"
  String  "<um> Sabre de Luz"
  String "<uma> Arma Laser"
  String "<uma> Espada de Lacônia"
  String  "<um> Machado de Lacônia"
; Armaduras     123456789012345678
  String "<uma> Veste de Couro"
  String  "<um> Manto Branco"
  String "<uma> Veste Leve"
  String "<uma> Armadura de Ferro"
  String "<uma> Pele Espinhosa"
  String "<uma> Malha de Zircônio"
  String "<uma> Armadura de Diamante"
  String "<uma> Armadura de Lacônia"
  String   "<o> Manto de Frade"
; Escudos       123456789012345678
  String  "<um> Escudo de Couro"
  String  "<um> Escudo de Bronze"
  String  "<um> Escudo de Ferro"
  String  "<um> Escudo de Cerâmica"
  String "<uma> Luva Animal"
  String "<uma> Barreira Laser"
  String   "<o> Escudo de Perseu"
  String  "<um> Escudo de Lacônia"
; veículos      123456789012345678
  String   "<o> Rover Terrestre"
  String   "<o> Aerobarco"
  String   "<o> Escavador de Gelo"
; objetos       123456789012345678
  String "<uma> PelorieMate"
  String "<uma> Ruoginina"
  String   "<a> Flauta Calmante"
  String "<uma> Lanterna"
  String "<uma> Capa de Fuga"
  String  "<um> Teletapete"
  String  "<um> Chapéu Mágico"
  String "<uma> Alsulina"
  String  "<um> Polimaterial"
  String "<uma> Chave do Calabouço"
  String "<uma> Bola de Telepatia"
  String   "<a> Tocha Eclipse"
  String   "<o> Aeroprisma"
  String  "<as> Frutas de Laerma"
  String       "Hapsby"
  String  "<um> Passe"
  String  "<um> Passaporte"
  String "<uma> Bússola"
  String  "<um> Bolo"
  String   "<a> Carta do Governador[-Geral]"
  String  "<um> Pote de Lacônia"
  String   "<o> Pingente de Luz"
  String   "<o> Olho de Carbúnculo"
  String "<uma> Máscara de Gás"
  String   "<o> Cristal de Damoa"
  String  "<um> Master System"
  String   "<a> Chave Milagrosa"
  String       "Zillion"
  String "<uma> Coisa Secreta"
Names:
; Personagens
  String "Alisa"
  String "Myau"
  String "Tylon"
  String "Lutz"
Enemies:
; Monstros
; empty item (blank)
  String " "
  String "<a> Mosca Gigante"
  String "<a> Gosma Verde"
  String "<o> Olho Alado"
  String "<o> Devorador"
  String "<o> Escorpião"
  String "<o> Escorpião Gigante"
  String "<a> Gosma Azul"
  String "<o> Motaviano Camponês"
  String "<o> Olho Perverso"
  String "<a> Planta Assassina"
  String "<o> Escorpião Assassino"
  String "<o> Motaviano Cardador"
  String "<a> Herex"
  String "<o> Verme da Areia"
  String "<o> Motaviano Maníaco"
  String "<a> Lente Dourada"
  String "<a> Gosma Vermelha"
  String "<o> Homem Morcego"
  String "<o> Caranguejo-Ferradura"
  String "<o> Homem-Peixe"
  String "<o> Lich"
  String "<a> Tarântula"
  String "<a> Mantícora"
  String "<o> Esqueleto"
  String "<a> Formiga-Leão"
  String "<o> Homem do Pântano"
  String "<o> Dezoriano"
  String "<a> Sanguessuga"
  String "<o> Vampiro"
  String "<o> Elefante"
  String "<o> Canibal"
  String "<a> Amonita"
  String "<o> Executor"
  String "<a> Alma Penada"
  String "<o> Soldado Caveira"
  String "<o> Caracol"
  String "<a> Esfinge"
  String "<a> Serpente"
  String "<o> Leviatã"
  String "<o> Opressor"
  String "<o> Polvo"
  String "<o> Caçador Maluco"
  String "<o> Líder Dezoriano"
  String "<o> Zumbi"
  String "<o> Morto-Vivo"
  String "<o> Robô Policial"
  String "<o> Mago Ciborgue"
  String "<a> Salamandra"
  String "<nome> Tajim"
  String "<o> Titã"
  String "<o> Guarda Mecânico"
  String "<o> Tentáculo"
  String "<o> Talos"
  String "<a> Senhora Serpente"
  String "<o> Ceifador"
  String "<o> Mago Caótico"
  String "<o> Centauro"
  String "<o> Homem de Gelo"
  String "<o> Vulcão"
  String "<o> Dragão Vermelho"
  String "<o> Dragão Verde"
  String "<nome> LaShiec"
  String "<o> Mamute"
  String "<o> Centauro Rei"
  String "<o> Saqueador Negro"
  String "<o> Golem"
  String "<nome> Medusa"
  String "<o> Dragão de Gelo"
  String "<o> Dragão Sábio"
  String "<o> Dragão Dourado"
  String "<o> Doutor Maluco"
  String "<nome> LaShiec"
  String "<nome> Força Sombria"
  String "<nome> Pesadelo"
.ends
