.slot 2
.section "Enemy, name, item lists" semisuperfree banks 3-31
Lists:

Items:
; empty item (blank)
  String " "
; Armes
  String "<du> Sceptre"
  String "<du> Glaive"
  String "<de l'>Épée"
  String "<du> Sceptre Psycho"
  String "<des> Griffes d'acier"
  String "<de la> Hache"
  String "<de l'>Épée titane"
  String "<de l'>Épée céramique"
  String "<du> Pistolet à pointes"
  String "<des> Crocs en métal"
  String "<du> Canon plasma"
  String "<du> Sabre laser"
  String "<du> Pistolet laser"
  String "<de l'>Épée en laconia"
  String "<de la> Hache en laconia"
; Armures
  String "<du> Tenue de cuir"
  String "<de la> Cape blanche"
  String "<du> Plastron"
  String "<de l'>Armure d'acier"
  String "<de la> Fourrure piquante"
  String "<de la> Armure en zircone"
  String "<de l'>Armure en diamant"
  String "<de l'>Armure en laconia"
  String "<de la> Cape de Frad"
; Boucliers
  String "<du> Bouclier de cuir"
  String "<du> Bouclier de bronze"
  String "<du> Bouclier d'acier"
  String "<du> Bouclier céramique"
  String "<des> Gants sauvages"
  String "<du> Bouclier laser"
  String "<du> Bouclier de Persée"
  String "<du> Bouclier en laconia"
; véhicules
  String "<du> GéoMaster"
  String "<de l'>AquaNaute"
  String "<du> ForaGlace"
; objets
  String "<de la> Vitabarre"
  String "<de l'>Aquavital"
  String "<de la> Flute apaisante"
  String "<de la> Lampe torche"
  String "<du> Voile de fuite"
  String "<du> Tapis du croyant"
  String "<de la> Coiffe magique"
  String "<de l'>Alsuline"
  String "<de la> Polymatériau"
  String "<de la> Clé des donjons"
  String "<de la> Sphère d'esprit"
  String "<de la> Torche d'éclipse"
  String "<de l'>Aéroprisme"
  String "<des> Baies Laerma"
  String "<de> Hapsby"
  String "<du> Permis"
  String "<du> Passeport"
  String "<du> Boussole"
  String "<de la> Tarte"
  String "<de la> Lettre [du Gouverneur]"
  String "<du> Vase en laconia"
  String "<du> Pendentif lumineux"
  String "<de l'>Œil d'escarboucle"
  String "<du> Masque à gaz"
  String "<du> Cristal de Damoa"
  String "<de la> Master System"
  String "<de la> Clé Magique"
  String "<de> Shinobi"
  String "<de l'>Objet secret"
Names:
; Persos
  String "<d'>Alisa"
  String "<de> Myau"
  String "<de> Tylon"
  String "<de> Lutz"
Enemies:
; Monstres
; empty item (blank)
  String " "
  String "<de la> Mouche géante"
  String "<du> Gluant vert"
  String "<de l'>Oculum ailé"
  String "<du> Dévoreur"
  String "<du> Scorpion"
  String "<de la> Naïade géante"
  String "<du> Gluant bleu"
  String "<du> Paysan Motavien"
  String "<de l'>Oculum vampire"
  String "<de la> Plante carnivore"
  String "<de l'>Hélix"
  String "<du> Chineur Motavien"
  String "<de la> Mouche piquante"
  String "<du> Vers des sables"
  String "<du> Barjot Motavien"
  String "<de l'>Oculum doré"
  String "<du> Gluant rouge"
  String "<de l'>Homo chiropter"
  String "<de la> Limule"
  String "<de l'>Homo squalus"
  String "<de l'>Âme errante"
  String "<de la> Tarentule"
  String "<de la> Manticore"
  String "<du> Squelette"
  String "<du> Fourmilion"
  String "<de l'>Homo palustris"
  String "<du> Dézorien"
  String "<de la> Sangsue du désert"
  String "<de l'>Homo nosferatu"
  String "<de l'>Éléphant"
  String "<du> Goule"
  String "<de l'>Ammonite"
  String "<de l'>Exécuteur"
  String "<de la> Liche"
  String "<du> Soldat squelette"
  String "<du> Nautilus"
  String "<du> Sphinx"
  String "<du> Serpent"
  String "<du> Léviathan"
  String "<du> Roi Liche"
  String "<de la> Pieuvre"
  String "<du> Rôdeur"
  String "<du> Chef Dézorien"
  String "<du> Revenant"
  String "<du> Mort vivant"
  String "<du> Cyber garde"
  String "<du> Sorcier du Chaos"
  String "<du> Lézard de feu"
  String "<de> Maître Tajim"
  String "<du> Gaia"
  String "<du> Garde mécanique"
  String "<du> Kraken"
  String "<du> Talos"
  String "<du> Seigneur serpent"
  String "<du> Porteur de mort"
  String "<du> Cyber mage"
  String "<du> Centaure"
  String "<du> Géant de glace"
  String "<du> Géant de feu"
  String "<du> Dragon rouge"
  String "<du> Dragon vert"
  String "<de l'>Ombre de Lassic"
  String "<du> Mammouth"
  String "<du> Roi des sabres"
  String "<du> Maraudeur sombre"
  String "<du> Golem"
  String "<de> Médusa"
  String "<du> Dragon blanc"
  String "<du> Dragon de Casba"
  String "<du> Dragon doré"
  String "<du> Savant fou"
  String "<de> Lassic"
  String "<de> Force Obscure"
  String "<de> Cauchemar"
.ends
