.slot 2
.section "Enemy, name, item lists" semisuperfree banks 3-31
Lists:

Items:
; empty item (blank)
  String " "
; Armes
  String "<de la> Canne en Bois"
  String "<de l'>Épée Courte"
  String "<de l'>Épée en Fer"
  String "<du> Bâton Psycho"
  String "<des> Griffe Argentée"
  String "<de la> Hache en Fer"
  String "<de l'>Épée en Titane"
  String "<de l'>Épée en Céramique"
  String "<du> Pistolet à Pointes"
  String "<des> Griffe Sabre"
  String "<du> Pistolet Thermique"
  String "<du> Sabre Laser"
  String "<du> Pistolet Laser"
  String "<de l'>Épée en Laconia"
  String "<de la> Hache en Laconia"
; Armures
  String "<de la> Tenue de Cuir"
  String "<de la> Cape Blanche"
  String "<de la> Combinaison Légère"
  String "<de l'>Armure en Fer"
  String "<de la> Fourrure Piquante"
  String "<de l'> Armure zirconium"
  String "<de l'>Armure en Diamant"
  String "<de l'>Armure en Laconia"
  String "<de la> Cape de Frad"
; Boucliers
  String "<du> Bouclier en Cuir"
  String "<du> Bouclier en Fer"
  String "<du> Bouclier en Bronze"
  String "<du> Bouclier Céramique"
  String "<des> Gant Animal"
  String "<de la> Barrière Laser"
  String "<du> Bouclier de Persée"
  String "<du> Bouclier Laconia"
; véhicules
  String "<du> Géomaster"
  String "<de l'>Aéroglisseur"
  String "<du> Foraglace"
; objets
  String "<de la> Vitabarre"
  String "<de l'>Aquavital"
  String "<de la> Flûte Apaisante"
  String "<de la> Lampe Torche"
  String "<du> Voile de Fuite"
  String "<du> Tapis Volant"
  String "<du> Chapeau Magique"
  String "<de l'>Alsuline"
  String "<du> Polymétéral"
  String "<de la> Clé des Donjons"
  String "<de la> Sphère d'Esprit"
  String "<de la> Torche d'Eclipse"
  String "<de l'>Aéroprisme"
  String "<des> Baies Laerma"
  String "<de> Hapsby"
  String "<du> Laissez-passer"
  String "<du> Passeport"
  String "<de la> Boussole"
  String "<du> Shortcake"
  String "<de la> Lettre Gouverneur"
  String "<du> Vase en Laconia"
  String "<du> Pendentif Lumineux"
  String "<de l'>Oeil d'Escarboucle"
  String "<du> Masque à Gaz"
  String "<du> Cristal de Damoa"
  String "<de la> Master System"
  String "<de la> Clé Miracle"
  String "<de> zillion"
  String "<de l'>Objet Secret"
Names:
; Persos
  String "<d'>Alisa"
  String "<de> Myau"
  String "<de> Tylon"
  String "<de> Lutz"
Enemies:
; Monstres
; empty item (blank)
  String " "
  String "<de la> Mouche géante"
  String "<du> Gluant vert"
  String "<de l'>Oculum ailé"
  String "<de la> Plante anthropophage"
  String "<du> Scorpailes léger"
  String "<du> Scorpailes libellule"
  String "<du> Gluant bleu"
  String "<du> Motavien paysan"
  String "<de l'>Oculum diable"
  String "<de la> Plante tueuse"
  String "<du> Scorpailes cinglant"
  String "<du> Motavien chineur"
  String "<de la> Mouche hélice"
  String "<du> Vers des sables"
  String "<du> Motavien barjot"
  String "<de l'>Oculum doré"
  String "<du> Gluant rouge"
  String "<du> Vampire ailé"
  String "<du> Crabe fer à cheval"
  String "<du> Roi requin"
  String "<du> Fantôme errant"
  String "<de l'>Arachnide tarentule"
  String "<de la> Manticore argentée"
  String "<du> Squelette fou"
  String "<de l'>Arachnide fourmilion"
  String "<du> Roi des marais"
  String "<du> Dézorien amical"
  String "<du> Vers sangsue aride"
  String "<du> Vampire cryon"
  String "<de l'>Éléphant gros nez"
  String "<du> Mort-vivant goule"
  String "<du> Coquillage ammonite"
  String "<du> Crabe exécuteur"
  String "<du> Fantôme sorcier"
  String "<du> Squelette soldat"
  String "<du> Coquillage escargot"
  String "<de la> Manticore dorée"
  String "<du> Serpent hypnotique"
  String "<du> Vers léviathan"
  String "<du> Fantôme chimérique"
  String "<du> Poulpe pieuvre"
  String "<du> Squelette harceleur"
  String "<du> Dézorien hostile"
  String "<du> Mort-vivant zombie"
  String "<du> Mort-vivant amusant"
  String "<du> Garde cyber"
  String "<du> Mage cyborg"
  String "<du> Serpent lézard"
  String "<de> Maître Tajim"
  String "<du> Géant gaia"
  String "<du> Garde mécanique"
  String "<du> Poulpe gros mangeur"
  String "<du> Géant talos"
  String "<du> Serpent seigneur"
  String "<du> Guerrier mortuaire"
  String "<du> Mage sorcier"
  String "<du> Centaure cavalier"
  String "<du> Colosse de glace"
  String "<du> Colosse de feu"
  String "<du> Dragon rouge"
  String "<du> Dragon vert"
  String "<de l'>Ombre de LaShiec"
  String "<de l'>Éléphant mammouth"
  String "<du> Centaure roi sabres"
  String "<du> Guerrier maraudeur"
  String "<du> Géant golem"
  String "<de> Médusa"
  String "<du> Dragon givre"
  String "<du> Grand Dragon sage"
  String "<du> Grand Dragon doré"
  String "<du> Docteur fou"
  String "<de> LaShiec"
  String "<de la> Force obscure"
  String "<du> Cauchemar"
.ends
