.slot 2
.section "Enemy, name, item lists" superfree
Lists:

; Order is important!
Items:
  ; Max width 18 excluding <...> prefix (with space)
  String " " ; empty item (blank). Must be at least one space.
  String "ウッドケイン"
  String "ショートソード"
  String "アイアンソード"
  String "サイコウォンド"
  String "シルバータスク"
  String "アイアンアクス"
  String "チタニウムソード"
  String "セラミックソード"
  String "ニードルガン"
  String "サーベルクロー"
  String "ヒートガン"
  String "ライトセイバー"
  String "レーザーガン"
  String "ラコニアンソード"
  String "ラコニアンアクス"
; armour: 10-18
  String "レザークロス"
  String "ホワイトマント"
  String "ライトスーツ"
  String "アイアンアーマ"
  String "トゲリスノケガワ" ; 棘栗鼠の毛皮
  String "ジルコニアメイル"
  String "ダイヤノヨロイ" ; ダイヤの鎧
  String "ラコニアアーマ"
  String "フラードマント"
; shields: 19-20
  String "レザーシールド"
  String "アイアンシールド"
  String "ボロンシールド"
  String "セラミックノタテ" ; セラミックの盾
  String "アニマルグラブ"
  String "レーザーバリア"
  String "ペルセウスノタテ" ; ペルセウスの盾
  String "ラコニアシールド"
; vehicles: 21-23
  String "ランドマスター"
  String "フロームーバー"
  String "アイスデッカー"
; items: 24+
  String "ペロリーメイト"
  String "ルオギニン"
  String "スーズフルート"
  String "サーチライト"
  String "エスケープクロス"
  String "トランカーペット"
  String "マジックハット"
  String "アルシュリン"
  String "ポリメテラール"
  String "ダンジョンキー"
  String "テレパシーボール"
  String "イクリプストーチ"
  String "エアロプリズム"
  String "ラエルマベリー"
  String "ハプスビー"
  String "ロードパス"
  String "パスポート"
  String "コンパス"
  String "ショートケーキ"
  String "ソウトクノテガミ" ; 総督の手紙
  String "ラコニアンポット"
  String "ライトペンダント"
  String "カーバンクルアイ"
  String "ガスクリア"
  String "ダモアクリスタル"
  String "マスターシステム"
  String "ミラクルキー"
  String "ジリオン"
  String "ヒミツノモノ" ; 秘密の物

Names:
  String "アリサ"
  String "ミャウ"
  String "タイロン"
  String "ルツ"

Enemies:
  String " " ; Empty
  String "モンスターフライ"
  String "グリーンスライム"
  String "ウイングアイ"
  String "マンイーター"
  String "スコーピラス"
  String "ラージヤーゴ" ; ラージ水蠆
  String "ブルースライム"
  String "モタビアンノーフ"
  String "デビルバット"
  String "キラープラント"
  String "バイターフライ"
  String "モタビアンイビル" ; モタビアン農夫
  String "ヘレックス"
  String "サンドフーム"
  String "モタビアンマニア"
  String "ゴールドレンズ"
  String "レッドスライム"
  String "バットマン"
  String "カブトガニ"
  String "シャーキン"
  String "リッチ"
  String "タランチュラ"
  String "マンチコア"
  String "スケルトン"
  String "アリジゴク"
  String "マーシーズ"
  String "デゾリアン"
  String "デザートリーチ"
  String "クライオン"
  String "ビッグノーズ"
  String "グール"
  String "アンモナイト"
  String "エグゼキュート"
  String "ワイト"
  String "スカルソルジャー"
  String "マイマイ"
  String "マンチコート"
  String "サーペント"
  String "リバイアサン"
  String "ドルージュ"
  String "オクトパス"
  String "マッドストーカー"
  String "デゾリアンヘッド"
  String "ゾンビ"
  String "ビュート"
  String "ロボットポリス"
  String "サイボーグメイジ"
  String "フレームリザード"
  String "タジム"
  String "ガイア"
  String "マシーンガーダー"
  String "ビッグイーター"
  String "タロス"
  String "スネークロード"
  String "デスベアラー"
  String "カオスソーサラー"
  String "セントール"
  String "アイスマン"
  String "バルカン"
  String "レッドドラゴン"
  String "グリーンドラゴン"
  String "ラシーク"
  String "マンモス"
  String "キングセイバー"
  String "ダークマローダー"
  String "ゴーレム"
  String "メデューサ"
  String "フロストドラゴン"
  String "ドラゴンワイズ"
  String "ゴールドドレイク"
  String "マッドドクター"
  String "ラシーク"
  String "ダークファルス"
  String "ナイトメア"
.ends
