_BattlesAll:  .stringmap tilemap "Ganz"
_BattlesHalf: .stringmap tilemap "Halb"
_Brown: .stringmap tilemap "  Braun"
_Black: .stringmap tilemap "Schwarz"
_Font1: .stringmap tilemap "Polaris"
_Font2: .stringmap tilemap " AW2284"
_Normal:.stringmap tilemap " Normal"
_Fast:  .stringmap tilemap "Schnell"
