StatsBorderTop:     .stringmap tilemap "┌──────────────────╖"
Level:              .stringmap tilemap "│Gradus         "
EXP:                .stringmap tilemap "│Experientia  "
Attack:             .stringmap tilemap "│Impulsus       "
Defense:            .stringmap tilemap "│Defensio       "
MaxMP:              .stringmap tilemap "│Maximum PM     "
MaxHP:              .stringmap tilemap "│Maximum PV     "
StatsBorderBottom:  .stringmap tilemap "╘══════════════════╝"