.slot 2
.section "Enemy, name, item lists" superfree
Lists:

Items:
; empty item (blank)
  String " "
; Armas         123456789012345678
  String  "<un> Bastó"
  String "<una> Espasa Curta"
  String "<una> Espasa de Ferro"
  String  "<un> Bastó Màgic"
  String  "<un> Ullal de Plata"
  String "<una> Destral de Ferro"
  String "<una> Espasa de Titani"
  String "<una> Espasa de Ceràmica"
  String "<una> Pistola d'Agulles"
  String "<una> Garra Esmolada"
  String "<una> Pistola de Calor"
  String  "<un> Sabre de Llum"
  String "<una> Arma Làser"
  String "<una> Espasa de Laconia"
  String "<una> Destral de Laconia"
; Armaduras     123456789012345678
  String  "<un> Peto de Cuir"
  String  "<un> Mantell Blanc"
  String  "<un> Vestit Lleuger"
  String "<una> Armadura de Ferro"
  String "<una> Pell Punxeguda"
  String "<una> Malla de Zirconita"
  String "<una> Armadura de Diamant"
  String "<una> Armadura de Laconia"
  String  "<la> Capa de Frai"
; Escudos       123456789012345678
  String  "<un> Escut de Cuir"
  String  "<un> Escut de Bronze"
  String  "<un> Escut de Ferro"
  String  "<un> Escut de Ceràmica"
  String  "<un> Guant Animal"
  String "<una> Barrera Làser"
  String  "<el> Escut de Perseu"
  String  "<un> Escut de Laconia"
; veículos      123456789012345678
  String  "<el> LandMaster"
  String  "<l'>AeroLliscador"
  String  "<el> Trencaglaç"
; objetos       123456789012345678
  String  "<un> PelorieMate"
  String  "<un> Ruoginin"
  String  "<la> Flauta Calmant"
  String "<una> Llanterna"
  String "<una> Capa de Fuga"
  String "<una> Telecatifa"
  String  "<un> Barret Màgic"
  String "<una> Alsulina"
  String  "<un> Polymeteral"
  String "<una> Clau de Masmorra"
  String "<una> Bola Telepàtica"
  String  "<la> Torcha d'Eclipsi"
  String  "<el> Aeroprisma"
  String "<els> Fruits de Laerma"
  String  "<en> Hapsby"
  String  "<un> Salconduit"
  String  "<un> Passaport"
  String "<una> Brúixola"
  String  "<un> Pastís"
  String  "<la> Carta del Governador[ General]"
  String "<una> Olla de Laconia"
  String   "<l'>Arrecada de Llum"
  String   "<l'>Ull de Carboncle"
  String "<una> Màscara de Gas"
  String  "<el> Cristall de Damoa"
  String "<una> Master System"
  String  "<la> Clau Miraculosa"
  String       "Zillion"
  String "<una> Cosa Secreta"
Names:
; Personagens
  String "Alisa"
  String "Myau"
  String "Tylon"
  String "Lutz"
Enemies:
; Monstres
; empty item (blank)
  String " "
  String "<el> Borinot"
  String "<el> Llot Verd"
  String  "<l'>Ull Volador"
  String "<el> Devorahomes"
  String  "<l'>Escorpí"
  String  "<l'>Escorpí Gegant"
  String "<el> Llot Blau"
  String "<el> Pagés de Motavia"
  String "<el> Ratpenat Pervers"
  String "<la> Planta Assassina"
  String  "<l'>Escorpí Assassí"
  String "<el> Tafur de Motavia"
  String "<el> Herex"
  String "<el> Cuc de Terra"
  String "<el> Maníac de Motavia"
  String "<la> Lent Daurada"
  String "<el> Llot Vermell"
  String  "<l'>Home Ratpenat"
  String "<el> Cranc Ferradura"
  String "<el> Rei Tauró"
  String "<el> Calabre"
  String "<la> Taràntula"
  String "<la> Mantícora"
  String  "<l'>Esquelet"
  String "<la> Formiga Lleó"
  String  "<l'>Home de l'Aiguamoll"
  String "<el> Dezorià"
  String "<la> Sangonera de Sorra"
  String "<el> Vampir"
  String  "<l'>Elefant"
  String "<el> Gul"
  String  "<l'>Ammonita"
  String "<el> Botxí"
  String  "<l'>Anima en Pena"
  String "<el> Soldat Calavera"
  String "<el> Cargol"
  String "<l'> Esfinx"
  String "<la> Serp"
  String "<el> Leviatà"
  String  "<l'>Opressor"
  String "<el> Pop"
  String "<el> Caçador Foll"
  String "<el> Cabdill Dezorià"
  String "<el> Zombi"
  String "<el> Mort Vivent"
  String "<el> Policia Robot"
  String "<el> Mag Cyborg"
  String "<la> Salamandra"
  String "<en> Tajim"
  String "<el> Tità"
  String "<el> Guardia Mecànic"
  String "<el> Tentacle"
  String "<el> Talos"
  String "<la> Senyora Serp"
  String "<el> Portamort"
  String "<el> Mag del Caos"
  String "<el> Centaure"
  String  "<l'>Home de Gel"
  String "<el> Vulcà"
  String "<el> Drac Vermell"
  String "<el> Drac Verd"
  String "<en> Lashiec"
  String "<el> Mamut"
  String "<el> Rei Centaure"
  String "<el> Cavaller Negre"
  String "<el> Golem"
  String "<na> Medusa"
  String "<el> Drac de Gel"
  String "<el> Drac Savi"
  String "<el> Drac Daurat"
  String "<el> Doctor Boig"
  String "<en> Lashiec"
  String "<na> Força Fosca"
  String "<el> Súcube"

.ends
