; Lookup table into script

ScriptLookup:
.dw textSueloPart1,textSueloPart2,textSueloPart3,textNekisePart1,textNekisePart2,textNekisePart3,textNekisePart4
.dw textNekisePart5,text845e,text8481,text84a4,text84be,text84d4,text84f6,text8511
.dw text8524,text8536,text854e,text8557,text8569,text8581,text85a2,text85c3
.dw text85e2,text8601,text8624,text8649,text8666,text8687,text86a3,text86c8
.dw text86e9,text870e,text8732,text8754,text8773,text8794,text87d4,text87f8
.dw text881d,text8836,text885b,text8868,text8886,text88a4,text88c0,text88e0
.dw text8904,text890c,text8927,text8944,text8967,text8988,text89ad,text89d2
.dw text89f7,text8a06,text8a27,text8a40,text8a60,text8a78,text8a95,text8aa6
.dw text8abf,text8ad9,text8afc,text8b21,text8b44,text8b5d,text8b70,text8b94
.dw text8baa,text8bc8,text8bea,text8bf6,text8c0f,text8c32,text8c4d,text8c63
.dw text8c7d,text8c9a,text8ca4,text8cc9,text8cee,text8d0b,text8d30,text8d51
.dw text8d72,text8d82,text8d88,text8d8e,text8d9d,text8db6,text8dd7,text8dfc
.dw text8e1f,text8e40,text8e5a,text8e7f,text8ea4,text8ebd,text8edb,text8f15
.dw text8f1c,text8f3a,text8f5a,text8f77,text8f92,text8fb3,text8fd1,text8fe8
.dw text900f,text904a,text907b,text90be,text90cd,text90e2,text90fb,text9113
.dw text9138,text915b,text9178,text91a6,text91e0,text9204,text9225,text9242
.dw text9261,text9281,text929d,text92d9,text92fc,text930f,text9334,text9359
.dw text9374,text9390,text93b3,text93ca,text93f1,text940a,text942c,text943e
.dw text945f,text9482,text94a6,text94d4,text94ea,text9508,text9529,text9558
.dw text9572,text9597,text95b3,text95f1,text9610,text9625,text963f,text964c
.dw text966f,text968b,text96aa,text96c4,text96e8,text9700,text9711,text9755
.dw text975c,text9773,text9790,text97ad,text97cb,text97d7,text97e3,text97fc
.dw text980d,text9828,text983e,text984c,text985e,text9881,text989f,text98c4
.dw text98e6,text992c,text9947,text996a,text9989,text99af,text99bd,text99db
.dw text99f8,text9a16,text9a2d,text9a4f,text9a72,text9a80,text9a93,text9ab5
.dw text9ae5,text9b02,text9b1e,text9b3a,text9b58,text9b65,text9b76,text9b8e
.dw text9b9e,text9baf,text9bcf,text9bef,text9c0f,text9c2c,text9c4d,text9c69
.dw text9c88,text9c94,text9cb4,text9cd6,text9ce9,text9cfb,text9d1b,text9d3f
.dw text9d5d,text9d7c,text9d9d,text9dbb,text9dc2,text9ddd,text9dfd,text9e1b
.dw text9e33,text9e55,text9e77,text9e94,text9eab,text9ec3,text9ed3,text9ef3
.dw text9f0c,text9f2c,text9f51,text9f74,text9f8f,text9fb7,text9fd9,text9ffa
.dw texta00e,texta020,texta03d,texta054,texta072,texta093,texta0b7,texta0dc
.dw texta0ff,texta122,texta146,texta167,texta171,texta193,texta1a1,texta1a5
.dw texta1af,texta1b9,texta1e2,texta1fc,texta227,texta248,texta25a,texta269
.dw texta27b,texta29a,texta2b5,texta2ca,texta2ec,texta302,texta31b,texta326
.dw texta351,texta372,texta3a3,texta3be,texta3ca,texta3ed,texta40e,texta43a
.dw texta45c,texta47e,texta490,texta4a6,texta4c3,texta4dc,texta50c,texta52f
.dw texta552,texta571,texta590,texta5b2,texta5d0,texta5e3,texta606,texta615
.dw texta638,texta654,texta66c,texta678,texta68c,texta6aa,texta6b9,texta6e6
.dw texta70f,texta72e,texta74c,texta767,texta786,texta814,texta850,texta850
.dw texta850,texta850,texta86f,texta891,texta8d6,texta8f4,texta914,texta92e
.dw texta94c,texta96b,texta98c,texta9c8,texta9dc,texta9ef,textaa06,textaa27
.dw textaa57,textaa65,textAlisasHouse,textaa8b,textaaab,textaacd

; Script

textSueloPart1:
.db $2c $10 $0c $1a $00 $0d $04 $2b $4c $01 $28 $0b $19 $00 $07 $23 $11 $1a
.db $26 $08 $2c $06 $29 $2c $4c $23 $03 $3d $2a $23 $00 $01 $15 $10 $2d TextButton
textSueloPart2:
.db $14 $22 $29 $0a $14 $1a $00 $40 $07 $15 $02 $4c $00 $40 $23 $00 $23 $0c
.db $10 $10 $06 $02 $40 $00 $07 $3a $12 $02 $10 $14 $07 $1a TextButtonEnd
; WaTaSiHa SuERo.ARiSaNo KiMoTiHaYoKuWaKaRuWa.MoUDaReMo ANaTaWo[Wait for button press and blank text]
; ToMeRuKoToHa DeKiNaI. DeMo MoSiTaTaKaIDe KiZuTuITaToKiHa[Exit after button press]
; My name is Suelo.
; I know how you feel, Alisa. No one will be able to stop you from doing what you must do.

textSueloPart3:
.db $0a $0a $40 $00 $25 $2f $08 $28 $00 $24 $0d $2e $40 $00 $05 $25 $07 $4c TextButton
.db $21 $28 $2d $00 $0c $15 $02 $26 $03 $16 $18 $4c TextNewLine
.db $1f $10 $00 $02 $12 $40 $23 $00 $02 $27 $2f $0c $30 $02 $4c TextButtonEnd
; KoKoDe YutuKuRi YaSuNDe OYuKi.[Wait for button press and blank text]
; MuRiWo SiNaIYoUNiNe.[Line break]
; MaTa ITuDeMo IRatuSiyaI.[Exit after button press]
; Please relax and recover.
; Don't overdo it, okay? You will always be welcome here.

textNekisePart1:
.db $46 $08 $1a $00 $18 $07 $0e $4c TextNewLine
.db $07 $08 $14 $0a $2b $16 $00 $26 $29 $14 TextButton
textNekisePart2:
.db $25 $03 $0c $30 $00 $10 $02 $2b $2e $1a $00 $0c $05 $2e $14 $02 $03 TextNewLine
.db $1f $11 $16 $00 $02 $29 $27 $0c $02 $4c TextButton
textNekisePart3:
.db $01 $2f $4c $0f $2a $14 $00 $18 $2b $06 $27 TextNewLine
.db $27 $0a $16 $01 $2e $4b $2f $14 $00 $14 $02 $03 $00 $12 $46 $2d TextButton
textNekisePart4:
.db $01 $3a $06 $2f $13 $10 $2e $3d $4c $01 $14 $40 $00 $24 $08 $16 TextNewLine
.db $10 $12 $3d $2b $03 $06 $27 $00 $23 $2f $13 $02 $08 $14 $02 $02 $26 $4c TextButtonEnd
; BoKuHa NeKiSe.[Line break]
; KiKuToKoRoNi YoRuTo[Wait for button press and blank text]
; YuUSiya TaIRoNHa SiONToIU[Line break]
; MaTiNi IRuRaSiI.[Wait for button press and blank text]
; Atu.SoReTo NeRoKaRa[Line break]
; RaKoNiANPotuTo ToIU TuBoWo[Wait for button press and blank text]
; AZuKatuTeTaNDa.AToDe YaKuNi[Line break]
; TaTuDaRoUKaRa MotuTeIKuToIIYo.[Exit after button press]
; My name is Nekise.
; I just found out that the hero Tairon is staying in the town of Shion.
; Oh, and, your brother entrusted me with this jar - it's called a Laconian Pot.
; Here, you should take it with you. It may come in handy later on.

textNekisePart5:
.db $11 $06 $27 $16 $15 $2a $15 $08 $13 $00 $37 $22 $2e $4c TextNewLine
.db $44 $39 $2d $00 $02 $19 $2f $13 $29 $26 $4c TextButtonEnd
; TiKaRaNiNaReNaKuTe GoMeN.[Line break]
; BuZiWo INotuTeRuYo.[Exit after button press]
; Forgive me, but there is nothing more I can do. May your journey be safe.

text845e:
.db $0a $19 $00 $06 $20 $16 $4d $14 $00 $07 $32 $39 $31 $03 $08 $1a TextNewLine
.db $06 $02 $36 $2e $2a $02 $33 $00 $0c $06 $2a $13 $02 $29 $2e $3d $4c TextButtonEnd
; KoNo KaMiNi-To KiyoZiyuUKuHa[Line break]
; KaIGeNReIGa SiKaReTeIRuNDa.[Exit after button press]

text8481:
.db $06 $34 $19 $00 $06 $06 $2f $10 $00 $41 $01 $2d $00 $01 $09 $29 $16 $1a
.db $3d $2e $39 $32 $2e $07 $4d $33 $00 $1b $12 $26 $03 $40 $0d $4c TextButtonEnd
; KaGiNo KaKatuTa DoAWo AKeRuNiHaDaNZiyoNKi-Ga HiTuYoUDeSu.[Exit after button press]

text84a4:
.db $01 $06 $28 $33 $15 $02 $14 $00 $0d $0d $22 $15 $02 TextNewLine
.db $3d $2e $39 $32 $2e $23 $00 $01 $29 $26 $4c TextButtonEnd
; AKaRiGaNaITo SuSuMeNaI[Line break]
; DaNZiyoNMo ARuYo.[Exit after button press]

text84be:
.db $06 $20 $16 $4d $14 $19 $00 $16 $0c $1a $00 $0d $4a $4d $0d $4b $4d $14
.db $40 $0d $4c TextButtonEnd
; KaMiNi-ToNo NiSiHa SuPe-SuPo-ToDeSu.[Exit after button press]

text84d4:
.db $20 $15 $14 $1f $11 $40 $1a $00 $02 $2b $02 $2b $15 $00 $14 $28 $1b $07
.db $33 $00 $40 $07 $29 $00 $14 $02 $03 $00 $1a $15 $0c $3d $4c TextButtonEnd
; MiNaToMaTiDeHa IRoIRoNa ToRiHiKiGa DeKiRu ToIU HaNaSiDa.[Exit after button press]

text84f6:
.db $07 $32 $39 $31 $03 $08 $19 $00 $0f $14 $16 $1a $00 $40 $15 $02 $1e $03
.db $33 $00 $20 $19 $10 $22 $3d $4c TextButtonEnd
; KiyoZiyuUKuNo SoToNiHa DeNaIHoUGa MiNoTaMeDa.[Exit after button press]

text8511:
.db $0c $16 $10 $08 $15 $06 $2f $10 $27 $00 $0a $0a $16 $02 $29 $2e $3d $4c TextButtonEnd
; SiNiTaKuNaKatuTaRa KoKoNiIRuNDa.[Exit after button press]

text8524:
.db $0a $0a $2d $00 $14 $05 $0d $2c $09 $16 $1a $00 $02 $06 $15 $02 $4c TextButtonEnd
; KoKoWo ToOSuWaKeNiHa IKaNaI.[Exit after button press]

text8536:
.db $2b $4d $41 $47 $0d $19 $00 $15 $02 $23 $19 $1a $00 $0a $0a $2d TextNewLine
.db $14 $05 $2a $15 $02 $4c TextButtonEnd
; Ro-DoPaSuNo NaIMoNoHa KoKoWo[Line break]
; ToOReNaI.[Exit after button press]

text854e:
.db $14 $05 $2f $13 $00 $26 $0c $4c TextButtonEnd
; ToOtuTe YoSi.[Exit after button press]

text8557:
.db $0a $0a $1a $00 $47 $2b $28 $14 $00 $07 $32 $39 $31 $03 $08 $26 $4c TextButtonEnd
; KoKoHa PaRoRiTo KiyoZiyuUKuYo.[Exit after button press]

text8569:
.db $23 $28 $19 $15 $06 $1a $00 $14 $08 $16 TextNewLine
.db $07 $2d $12 $09 $10 $1e $03 $33 $02 $02 $26 $4c TextButtonEnd
; MoRiNoNaKaHa ToKuNi[Line break]
; KiWoTuKeTaHoUGaIIYo.[Exit after button press]

text8581:
.db $07 $32 $39 $31 $03 $08 $19 $00 $20 $15 $20 $19 $00 $41 $03 $08 $12 $16
.db $22 $40 $31 $4d $0b $00 $14 $02 $03 $00 $1f $23 $19 $33 TextButton
text85a2:
.db $26 $20 $33 $04 $2f $10 $14 $02 $03 $4c $0d $33 $10 $2d TextNewLine
.db $20 $10 $23 $19 $1a $00 $02 $0c $16 $00 $0b $2a $29 $0f $03 $3d $4c TextButtonEnd
; KiyoZiyuUKuNo MiNaMiNo DoUKuTuNiMeDeyu-Sa ToIU MaMoNoGa[Wait for button press and blank text]
; YoMiGaEtuTaToIU.SuGaTaWo[Line break]
; MiTaMoNoHa ISiNi SaReRuSoUDa.[Exit after button press]

text85c3:
.db $1b $33 $0c $1d $00 $02 $08 $14 $00 $0c $05 $2e $00 $14 $02 $03 TextNewLine
.db $20 $15 $14 $1f $11 $33 $00 $01 $29 $27 $0c $02 $4c TextButtonEnd
; HiGaSiHe IKuTo SiON ToIU[Line break]
; MiNaToMaTiGa ARuRaSiI.[Exit after button press]

text85e2:
.db $0d $4a $4d $0d $4b $4d $14 $06 $27 $00 $23 $10 $43 $01 $0e $02 $19 TextNewLine
.db $47 $0e $05 $00 $1f $40 $00 $02 $09 $29 $26 $4c TextButtonEnd
; SuPe-SuPo-ToKaRa MoTaBiASeINo[Line break]
; PaSeO MaDe IKeRuYo.[Exit after button press]

text8601:
.db $47 $2b $28 $14 $19 $00 $16 $0c $16 $01 $29 $00 $33 $0c $0a $19 $23 $28
.db $1d $1a $00 $11 $06 $12 $03 $2b $33 $00 $01 $29 $27 $0c $02 $4c TextButtonEnd
; PaRoRiToNo NiSiNiARu GaSiKoNoMoRiHeHa TiKaTuURoGa ARuRaSiI.[Exit after button press]

text8624:
.db $10 $02 $2b $2e $15 $27 $00 $22 $40 $31 $4d $0b $2d $00 $10 $05 $0c $16
.db $02 $2f $10 $26 $4c $00 $24 $12 $1a $00 $0a $14 $42 $2d $00 $1a $15 $0d TextButton
text8649:
.db $41 $03 $44 $12 $2d $00 $12 $2a $13 $00 $02 $10 $15 $01 $4c TextNewLine
.db $0f $19 $00 $41 $03 $44 $12 $1a $00 $08 $43 $16 TextButton
text8666:
.db $08 $0d $28 $43 $2e $2d $00 $44 $27 $0b $36 $13 $02 $10 $33 TextNewLine
.db $15 $16 $06 $19 $00 $24 $08 $16 $00 $10 $12 $19 $06 $18 $04 $4c TextButtonEnd
; TaIRoNNaRa MeDeyu-SaWo TaOSiNiItuTaYo. YaTuHa KoToBaWo HaNaSu[Wait for button press and blank text]
; DoUBuTuWo TuReTe ITaNaA.[Line break]
; SoNo DoUBuTuHa KuBiNi[Wait for button press and blank text]
; KuSuRiBiNWo BuRaSaGeTeITaGa[Line break]
; NaNiKaNo YaKuNi TaTuNoKaNeE.[Exit after button press]

text8687:
.db $27 $0c $4d $08 $00 $2d $00 $10 $05 $0c $16 $02 $08 $2e $3d $2f $13 TextNewLine
.db $15 $4c $00 $33 $2e $42 $2a $26 $4c TextButtonEnd
; RaSi-Ku Wo TaOSiNiIKuNDatuTe[Line break]
; Na. GaNBaReYo.[Exit after button press]

text86a3:
.db $0a $19 $1f $04 $00 $22 $40 $31 $4d $0b $19 $00 $41 $03 $08 $12 $40 TextNewLine
.db $0c $30 $45 $29 $00 $41 $03 $44 $12 $2d $00 $1b $2b $2f $10 $2e $3d $4c TextButton
text86c8:
.db $47 $0e $05 $19 $00 $0c $32 $03 $16 $2e $16 $00 $10 $06 $08 $00 $03 $28
.db $12 $09 $13 $24 $2f $10 $26 $4c $1d $2f $1d $2f $1d $4c TextButtonEnd
; KoNoMaE MeDeyu-SaNo DoUKuTuDe[Line break]
; SiyaBeRu DoUBuTuWo HiRotuTaNDa.[Wait for button press and blank text]
; PaSeONo SiyoUNiNNi TaKaKu URiTuKeTeYatuTaYo.HetuHetuHe.[Exit after button press]

text86e9:
.db $0b $02 $07 $2e $1a $00 $1c $09 $02 $07 $3d $18 $4c $41 $0a $06 $16 TextNewLine
.db $02 $02 $00 $23 $03 $09 $42 $15 $0c $1a $00 $15 $02 $23 $19 $06 $18 $4c TextButtonEnd
; SaIKiNHa HuKeIKiDaNe.DoKoKaNi[Line break]
; II MoUKeBaNaSiHa NaIMoNoKaNe.[Exit after button press]

text870e:
.db $0c $05 $2e $19 $00 $20 $15 $20 $19 $00 $1a $2e $14 $03 $16 $1a TextNewLine
.db $02 $01 $27 $14 $00 $26 $42 $2a $29 $00 $41 $03 $08 $12 $33 $01 $29 $4c TextButtonEnd
; SiONNo MiNaMiNo HaNToUNiHa[Line break]
; IARaTo YoBaReRu DoUKuTuGaARu.[Exit after button press]

text8732:
.db $0a $0a $1a $00 $20 $15 $14 $1f $11 $00 $0c $05 $2e $4c $21 $06 $0c $1a
.db $46 $03 $04 $07 $40 $00 $16 $34 $2c $2f $10 $23 $19 $3d $4c TextButtonEnd
; KoKoHa MiNaToMaTi SiON.MuKaSiHaBoUEKiDe NiGiWatuTaMoNoDa.[Exit after button press]

text8754:
.db $04 $48 $14 $02 $03 $00 $1f $26 $02 $19 $23 $28 $1a TextNewLine
.db $0a $2e $47 $0d $33 $15 $02 $14 $00 $14 $05 $2a $15 $02 $26 $4c TextButtonEnd
; EPiToIU MaYoINoMoRiHa[Line break]
; KoNPaSuGaNaITo ToOReNaIYo.[Exit after button press]

text8773:
.db $1f $1e $03 $19 $00 $06 $06 $2f $10 $41 $01 $1a $00 $1f $39 $2f $08 $2d
.db $12 $06 $2c $15 $02 $14 $00 $1b $27 $07 $1f $0e $2e $4c TextButtonEnd
; MaHoUNo KaKatuTaDoAHa MaZituKuWoTuKaWaNaITo HiRaKiMaSeN.[Exit after button press]

text8794:
.db $0a $19 $1f $11 $06 $27 $00 $07 $10 $1d $02 $08 $14 $00 $42 $24 TextNewLine
.db $1f $4d $2a $00 $14 $02 $03 $00 $05 $06 $33 $00 $01 $28 $1f $0d $4c TextButton
.db $40 $23 $2c $2a $2c $2a $1a $00 $0f $19 $05 $06 $1d TextNewLine
.db $11 $06 $3f $08 $0a $14 $33 $00 $40 $07 $1f $0e $2e $4c TextButtonEnd
; KoNoMaTiKaRa KiTaHeIKuTo BaYa[Line break]
; Ma-Re ToIU OKaGa ARiMaSu.[Wait for button press and blank text]
; DeMoWaReWaReHa SoNoOKaHe[Line break]
; TiKaDuKuKoToGa DeKiMaSeN.[Exit after button press]

text87d4:
.db $42 $24 $1f $4d $2a $19 $00 $07 $10 $19 $00 $06 $02 $33 $2e $16 TextNewLine
.db $15 $03 $27 $14 $02 $03 $00 $41 $03 $08 $12 $33 $00 $01 $28 $1f $0d $4c TextButtonEnd
; BaYaMa-ReNo KiTaNo KaIGaNNi[Line break]
; NaURaToIU DoUKuTuGa ARiMaSu.[Exit after button press]

text87f8:
.db $23 $10 $43 $01 $19 $00 $0f $03 $14 $08 $1a $00 $23 $0c $06 $0c $10 $27
.db $20 $06 $10 $16 $00 $15 $2f $13 $08 $2a $29 $06 $23 $0c $2a $15 $02 $4c TextButtonEnd
; MoTaBiANo SoUToKuHa MoSiKaSiTaRaMiKaTaNi NatuTeKuReRuKaMoSiReNaI.[Exit after button press]

text881d:
.db $23 $10 $43 $01 $16 $1a $00 $0d $37 $02 $00 $04 $0d $47 $4d $33 TextNewLine
.db $02 $29 $27 $0c $02 $26 $4c TextButtonEnd
; MoTaBiANiHa SuGoI ESuPa-Ga[Line break]
; IRuRaSiIYo.[Exit after button press]

text8836:
.db $33 $0c $0a $19 $23 $28 $16 $1a $00 $0f $19 $21 $06 $0c $00 $29 $45 $19
.db $1a $06 $0e $19 $00 $09 $2e $07 $31 $03 $39 $32 $33 $00 $01 $2f $10 $4c TextButtonEnd
; GaSiKoNoMoRiNiHa SoNoMuKaSi RuBeNoHaKaSeNo KeNKiyuUZiyoGa AtuTa.[Exit after button press]

text885b:
.db $04 $48 $19 $21 $27 $1d $00 $26 $03 $0a $0f $4c TextButtonEnd
; EPiNoMuRaHe YoUKoSo.[Exit after button press]

text8868:
.db $0f $15 $10 $1a $00 $3d $2e $39 $32 $2e $07 $4d $19 $00 $01 $28 $06 $2d
.db $0b $33 $0c $13 $00 $02 $29 $19 $06 $15 $4c TextEnd
; SoNaTaHa DaNZiyoNKi-No ARiKaWoSaGaSiTe IRuNoKaNa.[Exit immediately]

text8886:
.db $3d $2e $39 $32 $2e $07 $4d $1a $00 $06 $20 $16 $4d $14 TextNewLine
.db $07 $32 $39 $31 $03 $08 $19 $00 $1a $3a $2a $16 $01 $29 TextButton
text88a4:
.db $0f $03 $0a $19 $15 $06 $16 $00 $2c $0c $33 $00 $0a $2f $0f $28 TextNewLine
.db $06 $08 $0c $13 $05 $02 $10 $3c $26 $4c TextButtonEnd
; DaNZiyoNKi-Ha KaMiNi-To[Line break]
; KiyoZiyuUKuNo HaZuReNiARu[Wait for button press and blank text]
; SoUKoNoNaKaNi WaSiGa KotuSoRi[Line break]
; KaKuSiTeOITaZoYo.[Exit after button press]

text88c0:
.db $0e $06 $02 $40 $00 $02 $11 $42 $2e $00 $06 $10 $08 $13 $00 $12 $26 $02
.db $44 $2f $0c $12 $2d $00 $0c $2f $13 $02 $29 $06 $4c TextEnd
; SeKaIDe ITiBaN KaTaKuTe TuYoIButuSiTuWo SituTeIRuKa.[Exit immediately]

text88e0:
.db $0f $2a $1a $00 $27 $0a $16 $01 $00 $39 $30 $4c $00 $0f $2a $40 TextNewLine
.db $40 $07 $10 $00 $44 $07 $1a $00 $0b $02 $07 $32 $03 $15 $2e $39 $30 $4c TextButtonEnd
; SoReHa RaKoNiA Ziya. SoReDe[Line break]
; DeKiTa BuKiHa SaIKiyoUNaNZiya.[Exit after button press]

text8904:
.db $15 $27 $42 $00 $26 $02 $4c TextButtonEnd
; NaRaBa YoI.[Exit after button press]

text890c:
.db $01 $29 $37 $29 $00 $10 $02 $26 $03 $09 $02 $19 $00 $2c $08 $0e $02 $2d
.db $0c $2f $13 $02 $29 $06 $15 $4c TextEnd
; ARuGoRu TaIYoUKeINo WaKuSeIWoSituTeIRuKaNa.[Exit immediately]

text8927:
.db $47 $29 $1f $00 $23 $10 $43 $01 $00 $40 $3c $28 $0d $00 $19 $00 TextNumber $12
.db $19 $00 $2c $08 $0e $02 $33 $01 $29 $4c TextButton
text8944:
.db $47 $29 $1f $1a $00 $20 $41 $28 $19 $1e $0c $4c $23 $10 $43 $01 $1a TextNewLine
.db $0d $15 $19 $1e $0c $4c $40 $3c $28 $0d $1a $00 $0a $05 $28 $19 TextButton
text8967:
.db $1e $0c $39 $30 $4c $01 $29 $37 $29 $00 $10 $02 $26 $03 $09 $02 $16 $1a
.db $07 $07 $33 $00 $0e $1f $2f $13 $02 $29 $19 $39 $30 $4c TextButtonEnd
; PaRuMa MoTaBiA DeZoRiSu No [number]TuNo WaKuSeIGaARu.[Wait for button press and blank text]
; PaRuMaHa MiDoRiNoHoSi.MoTaBiAHa[Line break]
; SuNaNoHoSi.DeZoRiSuHa KoORiNo[Wait for button press and blank text]
; HoSiZiya.ARuGoRu TaIYoUKeINiHaKiKiGa SeMatuTeIRuNoZiya.[Exit after button press]

text8988:
.db $0a $0a $1a $00 $47 $29 $1f $19 $00 $0d $4a $4d $0d $4b $4d $14 $3d $4c
.db $23 $10 $43 $01 $0e $02 $19 $00 $47 $0e $05 $1f $40 $00 $02 $09 $29 $4c TextButtonEnd
; KoKoHa PaRuMaNo SuPe-SuPo-ToDa.MoTaBiASeINo PaSeOMaDe IKeRu.[Exit after button press]

text89ad:
.db $47 $0e $05 $16 $1a $00 $0f $03 $14 $08 $33 $00 $02 $29 $4c $23 $10 $43
.db $01 $0e $02 $00 $3b $2e $44 $2d $00 $05 $0b $22 $13 $02 $29 $2e $3d $4c TextButtonEnd
; PaSeONiHa SoUToKuGa IRu.MoTaBiASeI ZeNBuWo OSaMeTeIRuNDa.[Exit after button press]

text89d2:
.db $33 $0c $0a $19 $00 $09 $2e $07 $31 $03 $39 $32 $40 $1a $00 $21 $06 $0c
.db $0d $4a $4d $0d $0c $2f $49 $2d $00 $12 $08 $2f $13 $10 $0f $03 $3d $4c TextButtonEnd
; GaSiKoNo KeNKiyuUZiyoDeHa MuKaSiSuPe-SuSituPuWo TuKutuTeTaSoUDa.[Exit after button press]

text89f7:
.db $47 $0d $4b $4d $14 $2d $00 $23 $2f $13 $02 $29 $06 $4c TextEnd
; PaSuPo-ToWo MotuTeIRuKa.[Exit immediately]

text8a06:
.db $0a $0a $40 $00 $47 $0d $4b $4d $14 $19 $00 $0c $2e $0e $02 $33 TextNewLine
.db $40 $07 $1f $0d $4c $0c $2e $0e $02 $2d $0c $1f $0d $06 $4c TextEnd
; KoKoDe PaSuPo-ToNo SiNSeIGa[Line break]
; DeKiMaSu.SiNSeIWoSiMaSuKa.[Exit immediately]

text8a27:
.db $02 $1f $1f $40 $16 $00 $2c $29 $02 $0a $14 $2d $00 $0c $10 $0a $14 $33
.db $01 $28 $1f $0d $06 $4c TextEnd
; IMaMaDeNi WaRuIKoToWo SiTaKoToGaARiMaSuKa.[Exit immediately]

text8a40:
.db $02 $1f $00 $01 $15 $10 $1a $00 $15 $16 $06 $00 $2c $29 $02 TextNewLine
.db $43 $32 $03 $07 $16 $00 $06 $06 $2f $13 $02 $1f $0d $06 $4c TextEnd
; IMa ANaTaHa NaNiKa WaRuI[Line break]
; BiyoUKiNi KaKatuTeIMaSuKa.[Exit immediately]

text8a60:
.db $13 $0d $03 $28 $32 $03 $00 TextNumber $22 $0e $10 $40 $0d $4c TextNewLine
.db $26 $2b $0c $02 $40 $0d $06 $4c TextEnd
; TeSuURiyoU [number]MeSeTaDeSu.[Line break]
; YoRoSiIDeSuKa.[Exit immediately]

text8a78:
.db $40 $1a $00 $47 $0d $4b $4d $14 $2d $00 $1a $2f $0a $03 $0c $1f $0d $4c
.db $05 $03 $09 $14 $28 $08 $3d $0b $02 $4c TextButtonEnd
; DeHa PaSuPo-ToWo HatuKoUSiMaSu.OUKeToRiKuDaSaI.[Exit after button press]

text8a95:
.db $0f $03 $40 $0d $06 $4c $40 $1a $00 $05 $07 $2d $12 $09 $13 $4c TextButtonEnd
; SoUDeSuKa.DeHa OKiWoTuKeTe.[Exit after button press]

text8aa6:
.db $0f $2a $1a $00 $26 $08 $15 $02 $40 $0d $18 $4c TextNewLine
.db $1f $10 $00 $05 $0a $0c $08 $3d $0b $02 $4c TextButtonEnd
; SoReHa YoKuNaIDeSuNe.[Line break]
; MaTa OKoSiKuDaSaI.[Exit after button press]

text8abf:
.db $0a $0a $1a $00 $23 $10 $43 $01 $19 TextNewLine
.db $47 $0e $05 $00 $0d $4a $4d $0d $4b $4d $14 $00 $3d $26 $4c TextButtonEnd
; KoKoHa MoTaBiANo[Line break]
; PaSeO SuPe-SuPo-To DaYo.[Exit after button press]

text8ad9:
.db $0b $42 $08 $19 $00 $15 $06 $40 $1a $00 $01 $28 $39 $37 $08 $33 TextNewLine
.db $01 $42 $2a $13 $00 $02 $29 $14 $02 $03 $00 $03 $2c $0b $3d $26 $4c TextButtonEnd
; SaBaKuNo NaKaDeHa ARiZiGoKuGa[Line break]
; ABaReTe IRuToIU UWaSaDaYo.[Exit after button press]

text8afc:
.db $47 $29 $1f $0e $02 $19 TextNewLine
.db $15 $03 $27 $00 $14 $02 $03 $00 $41 $03 $08 $12 $16 $1a TextButton
.db $09 $4d $07 $24 $33 $00 $01 $29 $2e $3d $2f $13 $18 $4c TextButtonEnd
; PaRuMaSeINo[Line break]
; NaURa ToIU DoUKuTuNiHa[Wait for button press and blank text]
; Ke-KiYaGa ARuNDatuTeNe.[Exit after button press]

text8b21:
.db $23 $10 $43 $01 $19 $00 $0f $03 $14 $08 $1a $00 $39 $12 $1a TextNewLine
.db $27 $0c $4d $08 $14 $00 $15 $06 $33 $00 $2c $29 $02 $27 $0c $02 $26 $4c TextButtonEnd
; MoTaBiANo SoUToKuHa ZiTuHa[Line break]
; RaSi-KuTo NaKaGa WaRuIRaSiIYo.[Exit after button press]

text8b44:
.db $0f $03 $14 $08 $16 $00 $01 $03 $16 $1a $00 $05 $08 $28 $23 $19 $33 TextNewLine
.db $02 $29 $0f $03 $26 $4c TextButtonEnd
; SoUToKuNi AUNiHa OKuRiMoNoGa[Line break]
; IRuSoUYo.[Exit after button press]

text8b5d:
.db $0f $03 $14 $08 $1a $00 $01 $1f $02 $23 $19 $33 $00 $3d $02 $0d $07 $4c TextButtonEnd
; SoUToKuHa AMaIMoNoGa DaISuKi.[Exit after button press]

text8b70:
.db $1f $1a $29 $00 $14 $02 $03 $00 $41 $03 $08 $12 $33 $00 $47 $0e $05 $19
.db $07 $10 $19 $00 $24 $1f $19 $00 $15 $06 $16 $00 $01 $28 $1f $0d $4c TextButtonEnd
; MaHaRu ToIU DoUKuTuGa PaSeONoKiTaNo YaMaNo NaKaNi ARiMaSu.[Exit after button press]

text8b94:
.db $0a $0a $1a $00 $23 $10 $43 $01 $19 $00 $0c $31 $14 TextNewLine
.db $47 $0e $05 $00 $40 $0d $4c TextButtonEnd
; KoKoHa MoTaBiANo SiyuTo[Line break]
; PaSeO DeSu.[Exit after button press]

text8baa:
.db $01 $28 $39 $37 $08 $1a $00 $1b $14 $19 $00 $01 $0c $40 $1a TextNewLine
.db $14 $13 $23 $00 $14 $05 $2a $15 $02 $3d $2b $03 $4c TextButtonEnd
; ARiZiGoKuHa HiToNo ASiDeHa[Line break]
; ToTeMo ToOReNaIDaRoU.[Exit after button press]

text8bc8:
.db $22 $3a $27 $0c $02 $00 $41 $03 $44 $12 $33 $00 $02 $29 $2e $3d $09 $41
.db TextNumber $05 $08 $00 $22 $0e $10 $40 $00 $06 $2c $15 $02 $06 $4c TextEnd
; MeZuRaSiI DoUBuTuGa IRuNDaKeDo[number]OKu MeSeTaDe KaWaNaIKa.[Exit immediately]

text8bea:
.db $01 $2e $10 $00 $03 $0f $12 $07 $3d $18 $4c TextButtonEnd
; ANTa USoTuKiDaNe.[Exit after button press]

text8bf6:
.db $05 $24 $00 $01 $2e $10 $00 $22 $3a $27 $0c $02 $00 $12 $46 $2d TextNewLine
.db $23 $2f $13 $02 $29 $18 $4c TextButton
text8c0f:
.db $0f $19 $00 $27 $0a $16 $01 $2e $4b $2f $14 $00 $14 $15 $27 TextNewLine
.db $0a $03 $06 $2e $0c $13 $23 $00 $02 $02 $26 $4c $00 $41 $03 $06 $18 $4c TextEnd
; OYa ANTa MeZuRaSiI TuBoWo[Line break]
; MotuTeIRuNe.[Wait for button press and blank text]
; SoNo RaKoNiANPotuTo ToNaRa[Line break]
; KoUKaNSiTeMo IIYo. DoUKaNe.[Exit immediately]

text8c32:
.db $0f $2a $39 $30 $00 $12 $2a $13 $02 $07 $15 $4c TextNewLine
.db $06 $2c $02 $33 $2f $13 $00 $24 $2f $13 $08 $2a $4c TextButtonEnd
; SoReZiya TuReTeIKiNa.[Line break]
; KaWaIGatuTe YatuTeKuRe.[Exit after button press]

text8c4d:
.db $0f $03 $14 $08 $1d $19 $00 $05 $08 $28 $23 $19 $2d TextNewLine
.db $23 $2f $13 $07 $10 $06 $4c TextEnd
; SoUToKuHeNo OKuRiMoNoWo[Line break]
; MotuTeKiTaKa.[Exit immediately]

text8c63:
.db $40 $1a $00 $0f $19 $00 $0c $32 $4d $14 $09 $4d $07 $2d TextNewLine
.db $01 $3a $06 $2f $13 $00 $05 $0a $03 $4c TextButtonEnd
; DeHa SoNo Siyo-ToKe-KiWo[Line break]
; AZuKatuTe OKoU.[Exit after button press]

text8c7d:
.db $05 $08 $28 $23 $19 $16 $00 $15 $29 $26 $03 $15 $00 $23 $19 $2d TextNewLine
.db $23 $2f $13 $15 $02 $39 $30 $15 $02 $06 $4c TextButtonEnd
; OKuRiMoNoNi NaRuYoUNa MoNoWo[Line break]
; MotuTeNaIZiyaNaIKa.[Exit after button press]

text8c9a:
.db $0b $2f $0b $14 $00 $06 $04 $2a $4c TextButtonEnd
; SatuSaTo KaERe.[Exit after button press]

text8ca4:
.db $2c $10 $0c $33 $00 $0a $19 $1e $0c $19 $00 $0f $03 $14 $08 $3d $4c TextNewLine
.db $27 $0c $4d $08 $2d $00 $10 $05 $0c $16 $00 $02 $08 $0f $03 $3d $15 $4c TextButton
text8cc9:
.db $0f $19 $00 $25 $03 $07 $2d $00 $1e $22 $13 $24 $29 $4c $1f $1a $29 $19
.db $41 $03 $08 $12 $16 $00 $29 $12 $00 $14 $02 $03 $00 $04 $0d $47 $4d $33 TextButton
text8cee:
.db $02 $29 $4c $00 $2c $10 $0c $19 $00 $13 $33 $20 $2d $00 $23 $2f $13 TextNewLine
.db $01 $02 $16 $00 $25 $08 $33 $26 $02 $4c TextButton
text8d0b:
.db $27 $0c $4d $08 $2d $00 $10 $05 $0c $13 $00 $07 $2f $14 $00 $0a $0a $1d
.db $23 $41 $2f $13 $08 $29 $0a $14 $2d $00 $0c $2e $39 $13 $02 $29 $3c $4c TextButtonEnd
; WaTaSiGa KoNoHoSiNo SoUToKuDa.[Line break]
; RaSi-KuWo TaOSiNi IKuSoUDaNa.[Wait for button press and blank text]
; SoNo YuUKiWo HoMeTeYaRu.MaHaRuNoDoUKuTuNi RuTu ToIU ESuPa-Ga[Wait for button press and blank text]
; IRu. WaTaSiNo TeGaMiWo MotuTe[Line break]
; AINi YuKuGaYoI.[Wait for button press and blank text]
; RaSi-KuWo TaOSiTe KituTo KoKoHeMoDotuTeKuRuKoToWo SiNZiTeIRuZo.[Exit after button press]

text8d30:
.db $29 $12 $1a $00 $47 $0e $05 $19 $00 $0f $03 $14 $08 $19 TextNewLine
.db $22 $02 $2a $02 $15 $27 $42 $00 $07 $08 $06 $23 $0c $2a $15 $02 $4c TextButtonEnd
; RuTuHa PaSeONo SoUToKuNo[Line break]
; MeIReINaRaBa KiKuKaMoSiReNaI.[Exit after button press]

text8d51:
.db $01 $15 $10 $33 $10 $1a $00 $3d $2a $40 $0d $06 $4c $00 $2c $10 $0c $1a
.db $02 $1f $00 $0c $31 $34 $32 $03 $11 $31 $03 $40 $0d $4c TextButton
text8d72:
.db $39 $30 $1f $2d $00 $0c $15 $02 $40 $00 $08 $3d $0b $02 $4c TextButtonEnd
; ANaTaGaTaHa DaReDeSuKa. WaTaSiHaIMa SiyuGiyoUTiyuUDeSu.[Wait for button press and blank text]
; ZiyaMaWo SiNaIDe KuDaSaI.[Exit after button press]

text8d82:
.db $24 $2f $1e $4d $4c TextButtonEnd
; YatuHo-.[Exit after button press]

text8d88:
.db $35 $03 $35 $03 $4c TextButtonEnd
; GuUGuU.[Exit after button press]

text8d8e:
.db $41 $03 $3c $00 $24 $0d $2e $40 $00 $02 $2f $13 $18 $4c TextButtonEnd
; DoUZo YaSuNDe ItuTeNe.[Exit after button press]

text8d9d:
.db $41 $03 $06 $00 $44 $39 $16 $00 $23 $41 $2f $13 $07 $13 $18 $4c TextNewLine
.db $02 $19 $2f $13 $29 $2c $4c TextButtonEnd
; DoUKa BuZiNi MoDotuTeKiTeNe.[Line break]
; INotuTeRuWa.[Exit after button press]

text8db6:
.db $01 $2e $10 $00 $05 $2a $16 $00 $4a $2b $28 $4d $22 $02 $14 $2d TextNewLine
.db $1b $14 $12 $00 $22 $35 $2e $40 $00 $08 $2a $15 $02 $06 $4c TextEnd
; ANTa OReNi PeRoRi-MeIToWo[Line break]
; HiToTu MeGuNDe KuReNaIKa.[Exit immediately]

text8dd7:
.db $01 $28 $33 $14 $03 $4c $0a $0a $1a $00 $21 $06 $0c $00 $29 $45 $19 TextNewLine
.db $14 $02 $03 $00 $06 $33 $08 $0c $30 $19 $00 $09 $2e $07 $31 $03 $39 $32 TextButton
text8dfc:
.db $3d $2f $10 $4c $3d $09 $41 $00 $29 $45 $19 $1a $00 $08 $29 $2f $13 TextNewLine
.db $02 $29 $14 $02 $03 $00 $28 $25 $03 $40 $00 $0a $19 $21 $27 $19 TextButton
text8e1f:
.db $20 $15 $20 $16 $01 $29 $00 $14 $28 $01 $3d $00 $14 $02 $03 TextNewLine
.db $2b $03 $37 $08 $16 $00 $14 $39 $0a $22 $27 $2a $10 $2e $3d $4c TextButtonEnd
; ARiGaToU.KoKoHa MuKaSi RuBeNo[Line break]
; ToIU KaGaKuSiyaNo KeNKiyuUZiyo[Wait for button press and blank text]
; DatuTa.DaKeDo RuBeNoHa KuRutuTe[Line break]
; IRuToIU RiYuUDe KoNoMuRaNo[Wait for button press and blank text]
; MiNaMiNiARu ToRiADa ToIU[Line break]
; RoUGoKuNi ToZiKoMeRaReTaNDa.[Exit after button press]

text8e40:
.db $01 $2e $10 $16 $00 $1a $15 $0d $0a $14 $1a $00 $15 $02 $4c TextNewLine
.db $41 $0a $06 $1d $00 $07 $04 $15 $4c TextButtonEnd
; ANTaNi HaNaSuKoToHa NaI.[Line break]
; DoKoKaHe KiENa.[Exit after button press]

text8e5a:
.db $33 $0c $0a $19 $23 $28 $06 $27 $00 $24 $1f $1d $00 $12 $03 $39 $29 TextNewLine
.db $02 $2f $4b $2e $20 $11 $19 $00 $05 $08 $16 $01 $29 $00 $14 $03 $16 $1a TextButton
text8e7f:
.db $11 $06 $3f $08 $15 $4c $0f $0a $16 $1a $00 $0d $33 $10 $2d $00 $20 $10
.db $3d $09 $40 $00 $06 $27 $3d $33 $00 $02 $0c $16 $15 $2f $13 $0c $1f $03 TextButton
text8ea4:
.db $14 $02 $03 $00 $05 $0f $2b $0c $02 $00 $1f $23 $19 $33 $00 $0d $2e $40
.db $02 $29 $27 $0c $02 $4c TextButtonEnd
; GaSiKoNoMoRiKaRa YaMaHe TuUZiRu[Line break]
; ItuPoNMiTiNo OKuNiARu ToUNiHa[Wait for button press and blank text]
; TiKaDuKuNa.SoKoNiHa SuGaTaWo MiTaDaKeDe KaRaDaGa ISiNiNatuTeSiMaU[Wait for button press and blank text]
; ToIU OSoRoSiI MaMoNoGa SuNDeIRuRaSiI.[Exit after button press]

text8ebd:
.db $05 $05 $4c $05 $0f $06 $2f $10 $19 $03 $4c TextNewLine
.db $0b $2f $0f $08 $39 $30 $33 $00 $2c $0c $19 $00 $39 $32 $0c $31 $2d TextButton
text8edb:
.db $12 $2a $13 $07 $13 $08 $2a $4c $11 $06 $12 $03 $2b $19 $00 $15 $06 $16
.db $06 $08 $2a $13 $05 $29 $1a $3a $39 $30 $4c TextButton
.db $1e $2e $14 $16 $00 $01 $02 $12 $1a $00 $1a $3a $06 $0c $33 $28 $24 $40
.db $0a $1f $2f $10 $23 $19 $39 $30 $4c TextButtonEnd
; OO.OSoKatuTaNoU.[Line break]
; SatuSoKuZiyaGa WaSiNo ZiyoSiyuWo[Wait for button press and blank text]
; TuReTeKiTeKuRe.TiKaTuURoNo NaKaNiKaKuReTeORuHaZuZiya.[Wait for button press and blank text]
; HoNToNi AITuHa HaZuKaSiGaRiYaDeKoMatuTaMoNoZiya.[Exit after button press]

text8f15:
.db $1c $38 $09 $29 $15 $4c TextButtonEnd
; HuZaKeRuNa.[Exit after button press]

text8f1c:
.db $10 $28 $15 $02 $19 $03 $4c $00 $2c $29 $02 $33 $00 $05 $06 $18 $2d TextNewLine
.db $01 $12 $22 $13 $07 $13 $08 $2a $2e $06 $4c TextButtonEnd
; TaRiNaINoU. WaRuIGa OKaNeWo[Line break]
; ATuMeTeKiTeKuReNKa.[Exit after button press]

text8f3a:
.db $26 $2b $0a $45 $00 $12 $02 $16 $00 $03 $11 $31 $03 $0e $2e TextNewLine
.db $29 $45 $19 $37 $03 $33 $00 $40 $07 $01 $33 $2f $10 $3c $4c TextButtonEnd
; YoRoKoBe TuINi UTiyuUSeN[Line break]
; RuBeNoGoUGa DeKiAGatuTaZo.[Exit after button press]

text8f5a:
.db $02 $03 $14 $05 $28 $16 $00 $0c $15 $02 $15 $27 TextNewLine
.db $1b $07 $03 $09 $29 $2c $09 $16 $1a $00 $02 $06 $15 $02 $4c TextButtonEnd
; IUToORiNi SiNaINaRa[Line break]
; HiKiUKeRuWaKeNiHa IKaNaI.[Exit after button press]

text8f77:
.db $0c $06 $0c $00 $05 $1f $04 $16 $1a $00 $29 $45 $19 $37 $03 $1a TextNewLine
.db $0f $03 $39 $31 $03 $40 $07 $2e $4c TextButtonEnd
; SiKaSi OMaENiHa RuBeNoGoUHa[Line break]
; SoUZiyuUDeKiN.[Exit after button press]

text8f92:
.db $29 $45 $19 $37 $03 $19 $00 $11 $32 $03 $0c $1a $00 $41 $03 $39 $30 $4c
.db $3d $02 $39 $16 $00 $12 $06 $2f $13 $00 $05 $08 $2a $4c TextButtonEnd
; RuBeNoGoUNo TiyoUSiHa DoUZiya.DaIZiNi TuKatuTe OKuRe.[Exit after button press]

text8fb3:
.db $0f $2a $1a $00 $38 $2e $18 $2e $39 $30 $4c TextNewLine
.db $05 $1f $04 $19 $00 $10 $43 $23 $00 $0a $0a $1f $40 $06 $19 $03 $4c TextButtonEnd
; SoReHa ZaNNeNZiya.[Line break]
; OMaENo TaBiMo KoKoMaDeKaNoU.[Exit after button press]

text8fd1:
.db $02 $1f $00 $02 $0f $33 $0c $02 $2e $3d $4c TextNewLine
.db $39 $30 $1f $0c $15 $02 $40 $08 $2a $4c TextButtonEnd
; IMa ISoGaSiINDa.[Line break]
; ZiyaMaSiNaIDeKuRe.[Exit after button press]

text8fe8:
.db $2c $0c $1a $00 $29 $45 $19 $39 $30 $4c $10 $0d $09 $16 TextNewLine
.db $07 $10 $19 $15 $27 $00 $26 $09 $02 $15 $0a $14 $39 $30 $4c TextButton
.db $06 $04 $29 $33 $02 $02 $4c TextButtonEnd
; WaSiHa RuBeNoZiya.TaSuKeNi[Line break]
; KiTaNoNaRa YoKeINaKoToZiya.[Wait for button press and blank text]
; KaERuGaII.[Exit after button press]

text900f:
.db $15 $16 $4c $03 $11 $31 $03 $0e $2e $2d $00 $12 $08 $2a $39 $30 $14 $4c
.db $42 $06 $23 $00 $24 $0d $20 $00 $24 $0d $20 $00 $02 $04 $4c TextButton
.db $2c $0c $33 $00 $0f $2e $15 $0a $14 $2d $00 $1b $07 $03 $09 $29 $14 TextNewLine
.db $05 $23 $03 $19 $06 $4c TextButtonEnd
; NaNi.UTiyuUSeNWo TuKuReZiyaTo.BaKaMo YaSuMi YaSuMi IE.[Wait for button press and blank text]
; WaSiGa SoNNaKoToWo HiKiUKeRuTo[Line break]
; OMoUNoKa.[Exit after button press]

text904a:
.db $03 $4d $21 $4c $0a $28 $15 $02 $24 $12 $39 $30 $4c TextNewLine
.db $0c $06 $10 $33 $15 $02 $4c TextButton
.db $2c $0c $19 $00 $02 $03 $14 $05 $28 $16 $00 $0c $13 $23 $27 $03 $33 TextNewLine
.db $0f $2a $40 $23 $26 $02 $06 $4c TextEnd
; U-Mu.KoRiNaIYaTuZiya.[Line break]
; SiKaTaGaNaI.[Wait for button press and blank text]
; WaSiNo IUToORiNi SiTeMoRaUGa[Line break]
; SoReDeMoYoIKa.[Exit immediately]

text907b:
.db $26 $0c $4c $0f $2a $40 $1a $00 $1b $14 $01 $0c $00 $0b $07 $16 TextNewLine
.db $33 $0c $0a $19 $00 $21 $27 $1d $00 $02 $2f $13 TextButton
.db $39 $31 $2e $43 $0d $29 $06 $27 $00 $01 $14 $06 $27 $00 $0a $02 $4c TextNewLine
.db $2c $0c $19 $0a $14 $15 $27 $00 $0c $2e $47 $02 $21 $26 $03 $39 $30 $4c TextButtonEnd
; YoSi.SoReDeHa HiToASi SaKiNi[Line break]
; GaSiKoNo MuRaHe ItuTe[Wait for button press and blank text]
; ZiyuNBiSuRuKaRa AToKaRa KoI.[Line break]
; WaSiNoKoToNaRa SiNPaIMuYoUZiya.[Exit after button press]

text90be:
.db $2b $4d $41 $47 $0d $2d $00 $23 $2f $13 $02 $29 $06 $4c TextEnd
; Ro-DoPaSuWo MotuTeIRuKa.[Exit immediately]

text90cd:
.db $10 $02 $0c $10 $00 $41 $07 $32 $03 $3d $4c TextNewLine
.db $0c $2e $40 $23 $27 $03 $3c $4c TextButtonEnd
; TaISiTa DoKiyoUDa.[Line break]
; SiNDeMoRaUZo.[Exit after button press]

text90e2:
.db $08 $23 $19 $00 $06 $02 $44 $12 $1a $00 $1e $2e $14 $03 $1a TextNewLine
.db $06 $0c $0a $02 $2e $3d $26 $4c TextButtonEnd
; KuMoNo KaIBuTuHa HoNToUHa[Line break]
; KaSiKoINDaYo.[Exit after button press]

text90fb:
.db $1a $49 $0d $43 $4d $00 $14 $02 $03 TextNewLine
.db $2b $46 $2f $14 $2d $00 $0c $2f $13 $29 $06 $02 $4c TextEnd
; HaPuSuBi- ToIU[Line break]
; RoBotuToWo SituTeRuKaI.[Exit immediately]

text9113:
.db $24 $1f $19 $00 $21 $0a $03 $1a $00 $06 $38 $2e $19 $00 $1c $2e $06 $40
.db $26 $03 $33 $2e $02 $09 $33 $00 $40 $07 $13 $02 $29 $0f $03 $3d $26 $4c TextButtonEnd
; YaMaNo MuKoUHa KaZaNNo HuNKaDeYoUGaNIKeGa DeKiTeIRuSoUDaYo.[Exit after button press]

text9138:
.db $33 $0c $0a $19 $00 $24 $1f $05 $08 $16 $01 $29 $00 $14 $03 $1a TextNewLine
.db $22 $40 $31 $4d $0b $19 $14 $03 $14 $00 $26 $42 $2a $13 $02 $29 $4c TextButtonEnd
; GaSiKoNo YaMaOKuNiARu ToUHa[Line break]
; MeDeyu-SaNoToUTo YoBaReTeIRu.[Exit after button press]

text915b:
.db $24 $01 $4c $1b $14 $16 $00 $01 $03 $19 $1a TextNewLine
.db $1b $0b $0c $44 $28 $3d $4c $05 $1a $15 $0c $0c $26 $03 $26 $4c TextEnd
; YaA.HiToNi AUNoHa[Line break]
; HiSaSiBuRiDa.OHaNaSiSiYoUYo.[Exit immediately]

text9178:
.db $4b $28 $22 $13 $27 $4d $29 $00 $14 $02 $03 $00 $08 $0d $28 $1a TextButton
.db $27 $0a $16 $01 $00 $02 $33 $02 $19 $00 $44 $2f $0c $12 $1a TextNewLine
.db $0d $45 $13 $00 $14 $06 $0d $0f $03 $3d $26 $4c TextButtonEnd
; PoRiMeTeRa-Ru ToIU KuSuRiHa[Wait for button press and blank text]
; RaKoNiA IGaINo ButuSiTuHa[Line break]
; SuBeTe ToKaSuSoUDaYo.[Exit after button press]

text91a6:
.db $04 $4d $2f $4c $00 $29 $45 $19 $1a $06 $0e $33 $00 $06 $04 $2f $13 TextNewLine
.db $07 $10 $19 $06 $02 $4c TextButton
.db $1f $10 $00 $03 $11 $31 $03 $0e $2e $2d $00 $12 $08 $29 $19 $06 $4c TextNewLine
.db $0c $32 $03 $33 $18 $04 $24 $4c $0d $35 $02 $08 $26 $4c TextButtonEnd
; E-tu. RuBeNoHaKaSeGa KaEtuTe[Line break]
; KiTaNoKaI.[Wait for button press and blank text]
; MaTa UTiyuUSeNWo TuKuRuNoKa.[Line break]
; SiyoUGaNeEYa.SuGuIKuYo.[Exit after button press]

text91e0:
.db $05 $08 $19 $00 $1d $24 $1d $00 $1a $02 $2f $13 $00 $02 $07 $13 TextNewLine
.db $06 $04 $2f $10 $23 $19 $1a $00 $02 $15 $02 $4c $1b $2f $1b $2f $1b $4c TextButtonEnd
; OKuNo HeYaHe HaItuTe IKiTe[Line break]
; KaEtuTaMoNoHa INaI.HituHituHi.[Exit after button press]

text9204:
.db $02 $0c $16 $00 $0b $2a $13 $0c $1f $2f $10 $00 $1b $14 $27 $0c $02 $4c
.db $23 $14 $16 $00 $23 $41 $2a $29 $19 $3d $2b $03 $06 $4c TextButtonEnd
; ISiNi SaReTeSiMatuTa HiToRaSiI.MoToNi MoDoReRuNoDaRoUKa.[Exit after button press]

text9225:
.db $23 $1a $24 $00 $06 $08 $37 $1a $00 $40 $07 $13 $05 $29 TextNewLine
.db $39 $30 $2b $03 $15 $4c $00 $1c $2f $1c $2f $1c $4c TextButtonEnd
; MoHaYa KaKuGoHa DeKiTeORu[Line break]
; ZiyaRoUNa. HutuHutuHu.[Exit after button press]

text9242:
.db $02 $07 $41 $1f $28 $39 $30 $4c $00 $23 $41 $28 $15 $0b $02 $4c TextNewLine
.db $06 $04 $29 $15 $27 $00 $02 $1f $19 $03 $11 $3d $4c TextButtonEnd
; IKiDoMaRiZiya. MoDoRiNaSaI.[Line break]
; KaERuNaRa IMaNoUTiDa.[Exit after button press]

text9261:
.db $05 $05 $4c $15 $2e $14 $00 $25 $03 $06 $2e $15 TextNewLine
.db $2c $06 $23 $19 $26 $4c $00 $2c $15 $16 $00 $07 $2d $12 $09 $13 $15 $4c TextButtonEnd
; OO.NaNTo YuUKaNNa[Line break]
; WaKaMoNoYo. WaNaNi KiWoTuKeTeNa.[Exit after button press]

text9281:
.db $42 $29 $13 $46 $1a $00 $05 $2a $19 $00 $15 $2c $42 $28 $3d $4c TextNewLine
.db $01 $27 $0d $2e $39 $30 $15 $02 $3c $4c TextButtonEnd
; BaRuTeBoHa OReNo NaWaBaRiDa.[Line break]
; ARaSuNZiyaNaIZo.[Exit after button press]

text929d:
.db $1a $49 $0d $43 $4d $00 $14 $02 $03 $00 $2b $46 $2f $14 $2d TextNewLine
.db $0b $33 $0c $13 $08 $29 $2e $39 $30 $4c TextButton
.db $01 $19 $00 $2b $46 $2f $14 $15 $27 $00 $03 $11 $31 $03 $0e $2e $2d TextNewLine
.db $0f $03 $39 $31 $03 $00 $40 $07 $29 $1a $3a $39 $30 $4c TextButtonEnd
; HaPuSuBi- ToIU RoBotuToWo[Line break]
; SaGaSiTeKuRuNZiya.[Wait for button press and blank text]
; ANo RoBotuToNaRa UTiyuUSeNWo[Line break]
; SoUZiyuU DeKiRuHaZuZiya.[Exit after button press]

text92d9:
.db $0a $19 $00 $0d $08 $27 $2f $49 $19 $15 $06 $16 $00 $0e $02 $19 $03 $19
.db $02 $02 $00 $2b $46 $2f $14 $33 $00 $0d $13 $27 $2a $13 $02 $29 TextButton
text92fc:
.db $14 $02 $03 $1a $15 $0c $3d $09 $41 $00 $1e $2e $14 $03 $06 $18 $4d $4c TextButtonEnd
; KoNo SuKuRatuPuNoNaKaNi SeINoUNoII RoBotuToGa SuTeRaReTeIRu[Wait for button press and blank text]
; ToIUHaNaSiDaKeDo HoNToUKaNe-.[Exit after button press]

text930f:
.db $01 $43 $05 $2e $19 $00 $21 $27 $16 $00 $4b $28 $22 $13 $27 $4d $29 TextNewLine
.db $14 $02 $03 $00 $08 $0d $28 $33 $00 $03 $2f $13 $02 $29 $27 $0c $02 $4c TextButtonEnd
; ABiONNo MuRaNi PoRiMeTeRa-Ru[Line break]
; ToIU KuSuRiGa UtuTeIRuRaSiI.[Exit after button press]

text9334:
.db $0a $0a $1a $00 $2b $01 $4d $00 $14 $02 $03 $00 $21 $27 $40 $0d $4c TextNewLine
.db $27 $0c $4d $08 $19 $0e $02 $40 $00 $0b $43 $2a $13 $0c $1f $2f $10 $4c TextButtonEnd
; KoKoHa RoA- ToIU MuRaDeSu.[Line break]
; RaSi-KuNoSeIDe SaBiReTeSiMatuTa.[Exit after button press]

text9359:
.db $06 $4d $42 $2e $08 $29 $01 $02 $00 $14 $02 $03 $00 $1e $03 $0e $07 $2d
.db $0c $2f $13 $02 $1f $0d $06 $4c TextButton
text9374:
.db $06 $0d $42 $19 $00 $41 $27 $37 $2e $33 $00 $23 $2f $13 $02 $29 TextNewLine
.db $14 $02 $03 $00 $03 $2c $0b $40 $0d $4c TextButtonEnd
; Ka-BaNKuRuAI ToIU HoUSeKiWoSituTeIMaSuKa.[Wait for button press and blank text]
; KaSuBaNo DoRaGoNGa MotuTeIRu[Line break]
; ToIU UWaSaDeSu.[Exit after button press]

text9390:
.db $0a $19 $0c $1f $19 $00 $16 $0c $19 $00 $1a $3a $2a $16 $1a TextNewLine
.db $01 $43 $05 $2e $00 $14 $02 $03 $00 $21 $27 $33 $00 $01 $28 $1f $0d $4c TextButtonEnd
; KoNoSiMaNo NiSiNo HaZuReNiHa[Line break]
; ABiON ToIU MuRaGa ARiMaSu.[Exit after button press]

text93b3:
.db $27 $04 $29 $1f $12 $28 $4d $00 $14 $02 $03 $00 $07 $2d TextNewLine
.db $0c $2f $13 $02 $29 $06 $4c TextEnd
; RaERuMaTuRi- ToIU KiWo[Line break]
; SituTeIRuKa.[Exit immediately]

text93ca:
.db $40 $3c $28 $0d $0e $02 $19 $00 $01 $29 $11 $49 $27 $19 TextNewLine
.db $14 $26 $42 $2a $29 $00 $0a $03 $36 $2e $16 TextButton
.db $05 $02 $0c $36 $2f $13 $02 $29 $14 $06 $4c TextButtonEnd
; DeZoRiSuSeINo ARuTiPuRaNo[Line break]
; ToYoBaReRu KoUGeNNi[Wait for button press and blank text]
; OISiGetuTeIRuToKa.[Exit after button press]

text93f1:
.db $04 $2f $00 $27 $0c $4d $08 $2d $00 $10 $05 $0c $16 $00 $02 $08 $19 $4c
.db $0d $37 $02 $18 $04 $4c TextButtonEnd
; Etu RaSi-KuWo TaOSiNi IKuNo.SuGoINeE.[Exit after button press]

text940a:
.db $03 $2c $0b $3d $09 $41 $00 $01 $29 $00 $08 $28 $0d $10 $29 $1a TextNewLine
.db $01 $0c $07 $00 $1f $1e $03 $2d $00 $1c $03 $39 $29 $14 $06 $4c TextButtonEnd
; UWaSaDaKeDo ARu KuRiSuTaRuHa[Line break]
; ASiKi MaHoUWo HuUZiRuToKa.[Exit after button press]

text942c:
.db $0a $19 $21 $27 $1a $00 $01 $43 $05 $2e $00 $14 $02 $03 $19 $26 $4c TextButtonEnd
; KoNoMuRaHa ABiON ToIUNoYo.[Exit after button press]

text943e:
.db $27 $0c $4d $08 $19 $00 $1f $19 $13 $1a $00 $0a $19 $21 $27 $16 $23 TextNewLine
.db $19 $43 $13 $07 $10 $4c $00 $10 $0d $09 $13 $08 $2a $4c TextButtonEnd
; RaSi-KuNo MaNoTeHa KoNoMuRaNiMo[Line break]
; NoBiTeKiTa. TaSuKeTeKuRe.[Exit after button press]

text945f:
.db $0a $19 $21 $27 $16 $00 $06 $2c $2f $10 $00 $05 $14 $0a $33 TextNewLine
.db $1b $2f $0a $0c $13 $07 $10 $26 $4c $41 $03 $44 $12 $39 $2f $09 $2e $2d TextButton
text9482:
.db $24 $2f $13 $29 $27 $0c $02 $33 $00 $07 $20 $33 $2c $29 $02 $15 $01 $4c
.db $12 $46 $00 $20 $10 $02 $15 $23 $19 $2d $00 $23 $2f $13 $10 $26 $4c TextButtonEnd
; KoNoMuRaNi KaWatuTa OToKoGa[Line break]
; HituKoSiTeKiTaYo.DoUBuTuZituKeNWo[Wait for button press and blank text]
; YatuTeRuRaSiIGa KiMiGaWaRuINaA.TuBo MiTaINaMoNoWo MotuTeTaYo.[Exit after button press]

text94a6:
.db $27 $0a $16 $01 $40 $00 $40 $07 $10 $00 $2b $46 $2f $14 $3d $26 $4c TextButton
.db $40 $23 $00 $0d $08 $27 $2f $49 $16 $00 $0b $2a $13 TextNewLine
.db $0d $13 $27 $2a $11 $1f $2f $10 $27 $0c $02 $26 $4c TextButtonEnd
; RaKoNiADe DeKiTa RoBotuToDaYo.[Wait for button press and blank text]
; DeMo SuKuRatuPuNi SaReTe[Line break]
; SuTeRaReTiMatuTaRaSiIYo.[Exit after button press]

text94d4:
.db $2c $10 $0c $00 $03 $11 $31 $03 $19 $00 $10 $43 $33 TextNewLine
.db $0c $13 $20 $10 $02 $2c $4c TextButtonEnd
; WaTaSi UTiyuUNo TaBiGa[Line break]
; SiTeMiTaIWa.[Exit after button press]

text94ea:
.db $39 $30 $0a $03 $18 $0a $00 $14 $02 $03 $00 $41 $03 $44 $12 $1a TextNewLine
.db $01 $29 $00 $07 $19 $20 $2d $00 $10 $45 $29 $14 TextButton
text9508:
.db $05 $05 $07 $08 $15 $2f $13 $00 $0f $27 $2d $00 $14 $45 $29 $26 $03 $16
.db $15 $29 $0f $03 $3d $26 $4c $00 $1c $0c $34 $3d $18 $4c TextButtonEnd
; ZiyaKoUNeKo ToIU DoUBuTuHa[Line break]
; ARu KiNoMiWo TaBeRuTo[Wait for button press and blank text]
; OOKiKuNatuTe SoRaWo ToBeRuYoUNiNaRuSoUDaYo. HuSiGiDaNe.[Exit after button press]

text9529:
.db $46 $08 $1a $00 $1a $49 $0d $43 $4d $4c TextButton
.db $20 $12 $09 $13 $08 $2a $13 $00 $01 $28 $33 $14 $03 $4c $00 $29 $45 $19
.db $37 $03 $19 $00 $0f $03 $39 $31 $03 $1a $00 $1f $06 $0e $13 $18 $4c TextButtonEnd
; BoKuHa HaPuSuBi-.[Wait for button press and blank text]
; MiTuKeTeKuReTe ARiGaToU. RuBeNoGoUNo SoUZiyuUHa MaKaSeTeNe.[Exit after button press]

text9558:
.db $0a $0a $1a $00 $23 $10 $43 $01 $0e $02 $19 $00 $03 $4d $3c TextNewLine
.db $14 $02 $03 $00 $21 $27 $40 $0d $4c TextButtonEnd
; KoKoHa MoTaBiASeINo U-Zo[Line break]
; ToIU MuRaDeSu.[Exit after button press]

text9572:
.db $01 $28 $39 $37 $08 $1a $00 $27 $2e $41 $1f $0d $10 $4d $00 $14 $02 $03
.db $19 $28 $23 $19 $2d $00 $12 $06 $04 $42 $00 $14 $05 $2a $1f $0d $26 $4c TextButtonEnd
; ARiZiGoKuHa RaNDoMaSuTa- ToIUNoRiMoNoWo TuKaEBa ToOReMaSuYo.[Exit after button press]

text9597:
.db $03 $4d $3c $19 $00 $20 $15 $20 $16 $00 $06 $0d $42 $00 $14 $02 $03 TextNewLine
.db $21 $27 $33 $00 $01 $28 $1f $0d $4c TextButtonEnd
; U-ZoNo MiNaMiNi KaSuBa ToIU[Line break]
; MuRaGa ARiMaSu.[Exit after button press]

text95b3:
.db $06 $0d $42 $19 $00 $41 $03 $08 $12 $16 $1a $00 $41 $27 $37 $2e $33 TextNewLine
.db $0d $20 $12 $02 $10 $27 $0c $02 $40 $0d $26 $4c TextButton
.db $0f $19 $00 $41 $27 $37 $2e $19 $00 $01 $10 $1f $16 $1a TextNewLine
.db $1e $03 $0e $07 $33 $00 $1a $02 $2f $13 $02 $29 $14 $06 $4c TextButtonEnd
; KaSuBaNo DoUKuTuNiHa DoRaGoNGa[Line break]
; SuMiTuITaRaSiIDeSuYo.[Wait for button press and blank text]
; SoNo DoRaGoNNo ATaMaNiHa[Line break]
; HoUSeKiGa HaItuTeIRuToKa.[Exit after button press]

text95f1:
.db $1c $27 $4d $41 $1f $2e $14 $00 $14 $02 $03 $00 $1f $2e $14 $2d TextNewLine
.db $0c $2f $13 $29 $06 $02 $4c $00 $06 $29 $02 $09 $41 TextButton
text9610:
.db $0d $37 $02 $00 $46 $03 $34 $32 $28 $32 $08 $33 TextNewLine
.db $01 $29 $0f $03 $3d $26 $4c TextButtonEnd
; HuRa-DoMaNTo ToIU MaNToWo[Line break]
; SituTeRuKaI. KaRuIKeDo[Wait for button press and blank text]
; SuGoI BoUGiyoRiyoKuGa[Line break]
; ARuSoUDaYo.[Exit after button press]

text9625:
.db $0d $4d $3a $1c $29 $4d $14 $00 $14 $02 $03 $00 $1c $04 $19 $0a $14 $2d
.db $0c $2f $13 $29 $06 $02 $4c TextEnd
; Su-ZuHuRu-To ToIU HuENoKoToWoSituTeRuKaI.[Exit immediately]

text963f:
.db $0f $03 $06 $02 $4c $12 $1f $2e $18 $04 $19 $4c TextButtonEnd
; SoUKaI.TuMaNNeENo.[Exit after button press]

text964c:
.db $15 $02 $0c $32 $3d $09 $41 $0b $00 $46 $08 $33 $00 $47 $29 $1f $0e $02
.db $1d $00 $02 $2f $10 $14 $07 $16 $00 $33 $0c $0a $19 $21 $27 $19 TextButton
text966f:
.db $1a $3a $2a $16 $00 $03 $22 $13 $07 $10 $2e $3d $4c $3d $2a $16 $23 TextNewLine
.db $02 $2f $11 $30 $3d $22 $3d $26 $4c TextButtonEnd
; NaISiyoDaKeDoSa BoKuGa PaRuMaSeIHe ItuTaToKiNi GaSiKoNoMuRaNo[Wait for button press and blank text]
; HaZuReNi UMeTeKiTaNDa.DaReNiMo[Line break]
; ItuTiyaDaMeDaYo.[Exit after button press]

text968b:
.db $3d $2a $16 $00 $07 $02 $10 $06 $00 $0c $27 $15 $02 $33 TextNewLine
.db $01 $07 $27 $22 $10 $1e $03 $33 $00 $20 $19 $10 $22 $3d $4c TextButtonEnd
; DaReNi KiITaKa SiRaNaIGa[Line break]
; AKiRaMeTaHoUGa MiNoTaMeDa.[Exit after button press]

text96aa:
.db $3d $22 $15 $23 $19 $1a $00 $3d $22 $3d $4c TextNewLine
.db $0b $4d $00 $06 $04 $2f $10 $4c $06 $04 $2f $10 $4c TextButtonEnd
; DaMeNaMoNoHa DaMeDa.[Line break]
; Sa- KaEtuTa.KaEtuTa.[Exit after button press]

text96c4:
.db $0c $12 $0a $02 $24 $12 $3d $4c $0f $2e $15 $16 $00 $02 $03 $19 $15 $27
.db $0c $06 $10 $33 $15 $02 $4c $3d $2a $16 $23 $00 $02 $03 $15 $26 $4c TextButtonEnd
; SiTuKoIYaTuDa.SoNNaNi IUNoNaRaSiKaTaGaNaI.DaReNiMo IUNaYo.[Exit after button press]

text96e8:
.db $2c $0c $1a $00 $0e $06 $02 $02 $11 $19 $00 $03 $27 $15 $02 $0c TextNewLine
.db $3d $23 $01 $39 $30 $4c TextButton
text9700:
.db $2c $0c $19 $00 $03 $27 $15 $02 $2d $00 $0c $2e $39 $29 $06 $4c TextEnd
; WaSiHa SeKaIITiNo URaNaISi[Line break]
; DaMoAZiya.[Wait for button press and blank text]
; WaSiNo URaNaIWo SiNZiRuKa.[Exit immediately]

text9711:
.db $42 $29 $13 $46 $16 $1a $00 $46 $08 $19 $00 $14 $23 $3d $11 $33 TextNewLine
.db $02 $29 $2e $3d $4c TextButton
.db $02 $1f $1a $00 $26 $03 $33 $2e $02 $09 $19 $00 $0e $02 $40 TextNewLine
.db $10 $02 $1d $2e $3d $2b $03 $15 $01 $4c TextButton
.db $01 $2f $10 $27 $00 $26 $2b $0c $08 $00 $02 $2f $14 $02 $13 $18 $4c TextButtonEnd
; BaRuTeBoNiHa BoKuNo ToMoDaTiGa[Line break]
; IRuNDa.[Wait for button press and blank text]
; IMaHa YoUGaNIKeNo SeIDe[Line break]
; TaIHeNDaRoUNaA.[Wait for button press and blank text]
; AtuTaRa YoRoSiKu ItuToITeNe.[Exit after button press]

text9755:
.db $26 $0c $4c $26 $0c $4c TextButtonEnd
; YoSi.YoSi.[Exit after button press]

text975c:
.db $05 $1f $04 $1a $00 $0b $33 $0c $23 $19 $2d $00 $0c $13 $05 $29 TextNewLine
.db $39 $30 $2b $03 $4c TextEnd
; OMaEHa SaGaSiMoNoWo SiTeORu[Line break]
; ZiyaRoU.[Exit immediately]

text9773:
.db $15 $2e $39 $30 $14 $4c $00 $00 $05 $1f $04 $1a TextNewLine
.db $0d $15 $05 $40 $15 $02 $4c $00 $06 $04 $29 $33 $02 $02 $4c TextButtonEnd
; NaNZiyaTo.  OMaEHa[Line break]
; SuNaODeNaI. KaERuGaII.[Exit after button press]

text9790:
.db $05 $1f $04 $1a $00 $01 $2a $2f $08 $0d $00 $05 $0b $4d $29 $2d TextNewLine
.db $0b $33 $0c $13 $05 $29 $39 $30 $2b $03 $4c TextEnd
; OMaEHa ARetuKuSu OSa-RuWo[Line break]
; SaGaSiTeORuZiyaRoU.[Exit immediately]

text97ad:
.db $2c $0c $19 $00 $02 $03 $0a $14 $1a $00 $0d $45 $13 $00 $10 $3d $0c $02
.db $19 $39 $30 $4c $00 $2c $06 $2f $10 $06 $4c TextEnd
; WaSiNo IUKoToHa SuBeTe TaDaSiINoZiya. WaKatuTaKa.[Exit immediately]

text97cb:
.db $40 $1a $00 $1f $10 $08 $29 $33 $02 $02 $4c TextButtonEnd
; DeHa MaTaKuRuGaII.[Exit after button press]

text97d7:
.db $2c $0c $16 $00 $0b $06 $27 $03 $19 $06 $4c TextEnd
; WaSiNi SaKaRaUNoKa.[Exit immediately]

text97e3:
.db $0f $03 $3d $2b $03 $4c $05 $1f $04 $1a $00 $15 $06 $15 $06 TextNewLine
.db $20 $41 $0a $2b $33 $01 $29 $4c TextButton
text97fc
.db $1e $03 $43 $16 $00 $08 $28 $0d $10 $29 $2d $00 $24 $2b $03 $4c TextButtonEnd
; SoUDaRoU.OMaEHa NaKaNaKa[Line break]
; MiDoKoRoGaARu.[Wait for button press and blank text]
; HoUBiNi KuRiSuTaRuWo YaRoU.[Exit after button press]

text980d:
.db $0a $0a $2d $00 $42 $24 $1f $4d $2a $19 $00 $14 $03 $14 TextNewLine
.db $0c $28 $15 $33 $27 $00 $07 $10 $19 $06 $4c TextEnd
; KoKoWo BaYaMa-ReNo ToUTo[Line break]
; SiRiNaGaRa KiTaNoKa.[Exit immediately]

text9828:
.db $06 $15 $27 $3a $24 $00 $13 $2e $19 $00 $02 $06 $28 $16 TextNewLine
.db $1c $2a $26 $03 $3c $4c TextButtonEnd
; KaNaRaZuYa TeNNo IKaRiNi[Line break]
; HuReYoUZo.[Exit after button press]

text983e:
.db $15 $27 $42 $00 $1b $07 $06 $04 $0d $33 $26 $02 $4c TextButtonEnd
; NaRaBa HiKiKaESuGaYoI.[Exit after button press]

text984c:
.db $0a $0a $1a $00 $06 $0d $42 $00 $14 $02 $03 $00 $21 $27 $40 $0d $4c TextButtonEnd
; KoKoHa KaSuBa ToIU MuRaDeSu.[Exit after button press]

text985e:
.db $0a $19 $21 $27 $19 $00 $41 $03 $08 $12 $16 $00 $41 $27 $37 $2e $33 TextNewLine
.db $0d $20 $12 $02 $10 $19 $4c $2c $10 $0c $00 $0a $2c $4d $02 $4c TextButtonEnd
; KoNoMuRaNo DoUKuTuNi DoRaGoNGa[Line break]
; SuMiTuITaNo.WaTaSi KoWa-I.[Exit after button press]

text9881:
.db $3d $2e $39 $32 $2e $19 $00 $15 $06 $40 $1a $00 $05 $19 $2a $19 TextNewLine
.db $22 $2d $00 $0c $2e $39 $29 $40 $15 $02 $3c $4c TextButtonEnd
; DaNZiyoNNo NaKaDeHa ONoReNo[Line break]
; MeWo SiNZiRuDeNaIZo.[Exit after button press]

text989f:
.db $1f $2c $28 $2d $00 $07 $28 $16 $00 $06 $0a $1f $2a $10 $00 $21 $27 TextNewLine
.db $16 $1a $00 $40 $2e $0e $12 $19 $00 $10 $13 $19 $00 $02 $02 $12 $10 $04 TextButton
text98c4:
.db $33 $01 $29 $4c $0f $19 $21 $06 $0c $00 $4a $29 $0e $03 $0d $33 TextNewLine
.db $1f $23 $19 $10 $02 $39 $16 $00 $12 $06 $2f $10 $14 $02 $03 $4c TextButtonEnd
; MaWaRiWo KiRiNi KaKoMaReTa MuRa[Line break]
; NiHa DeNSeTuNo TaTeNo IITuTaE[Wait for button press and blank text]
; GaARu.SoNoMuKaSi PeRuSeUSuGa[Line break]
; MaMoNoTaIZiNi TuKatuTaToIU.[Exit after button press]

text98e6:
.db $46 $08 $33 $00 $20 $3a $03 $20 $19 $00 $16 $0c $1d $00 $02 $08 $14 TextButton
.db $07 $28 $19 $26 $03 $15 $00 $05 $0f $2b $0c $02 $00 $41 $08 $33 $0d $33
.db $1b $2b $33 $2f $13 $02 $10 $2e $3d $4c TextButton
.db $15 $2e $14 $06 $00 $0c $15 $02 $14 TextNewLine
.db $14 $13 $23 $00 $11 $06 $26 $2a $15 $02 $26 $4c TextButtonEnd
; BoKuGa MiZuUMiNo NiSiHe IKuTo[Wait for button press and blank text]
; KiRiNoYoUNa OSoRoSiI DoKuGaSuGaHiRoGatuTeITaNDa.[Wait for button press and blank text]
; NaNToKa SiNaITo[Line break]
; ToTeMo TiKaYoReNaIYo.[Exit after button press]

text992c:
.db $1c $2b $4d $21 $4d $42 $4d $00 $14 $02 $03 $00 $19 $28 $23 $19 $2d TextNewLine
.db $0c $2f $13 $02 $29 $06 $02 $4c TextEnd
; HuRo-Mu-Ba- ToIU NoRiMoNoWo[Line break]
; SituTeIRuKaI.[Exit immediately]

text9947:
.db $47 $29 $1f $0e $02 $19 $00 $0c $05 $2e $19 $1f $11 $40 $00 $06 $2f $10
.db $2e $3d $09 $41 $00 $0a $2c $2a $11 $1f $2f $10 $20 $10 $02 $40 TextButton
text996a:
.db $42 $29 $13 $46 $16 $00 $0d $13 $11 $1f $2f $10 $26 $4c TextNewLine
.db $23 $2f $10 $02 $15 $02 $0a $14 $00 $0c $11 $1f $2f $10 $4c TextButtonEnd
; PaRuMaSeINo SiONNoMaTiDe KatuTaNDaKeDo KoWaReTiMatuTaMiTaIDe[Wait for button press and blank text]
; BaRuTeBoNi SuTeTiMatuTaYo.[Line break]
; MotuTaINaIKoTo SiTiMatuTa.[Exit after button press]

text9989:
.db $1c $2b $4d $21 $4d $42 $4d $2d $00 $20 $12 $09 $10 $4c TextButton
.db $1a $49 $0d $43 $4d $33 TextNewLine
.db $0a $2c $2a $10 $14 $0a $2b $2d $00 $15 $05 $0c $10 $19 $40 TextButton
text99af:
.db $12 $06 $04 $29 $26 $03 $16 $00 $15 $2f $10 $3c $4c TextButtonEnd
; HuRo-Mu-Ba-Wo MiTuKeTa.[Wait for button press and blank text]
; HaPuSuBi-Ga[Line break]
; KoWaReTaToKoRoWo NaOSiTaNoDe[Wait for button press and blank text]
; TuKaERuYoUNi NatuTaZo.[Exit after button press]

text99bd:
.db $01 $2a $1a $00 $45 $2e $28 $3d $26 $4c $00 $20 $3a $19 $03 $04 $2d TextNewLine
.db $0d $02 $0d $02 $00 $02 $09 $29 $2e $3d $4c TextButtonEnd
; AReHa BeNRiDaYo. MiZuNoUEWo[Line break]
; SuISuI IKeRuNDa.[Exit after button press]

text99db:
.db $0a $0a $1a $00 $41 $27 $0d $37 $4d $4c $00 $03 $20 $19 $03 $04 $19 TextNewLine
.db $11 $02 $0b $15 $00 $1f $11 $40 $0d $4c TextButtonEnd
; KoKoHa DoRaSuGo-. UMiNoUENo[Line break]
; TiISaNa MaTiDeSu.[Exit after button press]

text99f8:
.db $02 $1f $00 $03 $20 $19 $00 $20 $11 $1a $00 $14 $38 $0b $2a $13 TextNewLine
.db $1c $18 $0b $04 $00 $12 $06 $04 $15 $02 $19 $16 TextButton
text9a16:
.db $26 $08 $23 $1f $01 $00 $0a $19 $1f $11 $1d TextNewLine
.db $10 $41 $28 $12 $07 $1f $0c $10 $18 $4c TextButtonEnd
; IMa UMiNo MiTiHa ToZaSaReTe[Line break]
; HuNeSaE TuKaENaINoNi[Wait for button press and blank text]
; YoKuMoMaA KoNoMaTiHe[Line break]
; TaDoRiTuKiMaSiTaNe.[Exit after button press]

text9a2d:
.db $01 $43 $05 $2e $19 $00 $14 $03 $16 $1a $00 $1f $28 $32 $08 $2d TextNewLine
.db $1c $03 $39 $29 $00 $09 $2e $33 $00 $01 $29 $0f $03 $40 $0d $4c TextButtonEnd
; ABiONNo ToUNiHa MaRiyoKuWo[Line break]
; HuUZiRu KeNGa ARuSoUDeSu.[Exit after button press]

text9a4f:
.db $2c $10 $0c $1a $00 $21 $06 $0c $00 $0f $27 $16 $00 $03 $06 $44 TextNewLine
.db $05 $05 $07 $15 $00 $02 $2c $2d $00 $20 $10 $0a $14 $33 $01 $29 $4c TextButtonEnd
; WaTaSiHa MuKaSi SoRaNi UKaBu[Line break]
; OOKiNa IWaWo MiTaKoToGaARu.[Exit after button press]

text9a72:
.db $11 $32 $03 $0a $05 $18 $4d $0b $2e $40 $4d $0d $4c TextButton
text9a80:
.db $33 $2e $42 $2f $13 $00 $46 $03 $09 $2e $2d $00 $12 $3f $09 $13 $18 $4c TextButtonEnd
; TiyoUKoONe-SaNDe-Su.[Wait for button press and blank text]
; GaNBatuTe BoUKeNWo TuDuKeTeNe.[Exit after button press]

text9a93:
.db $2c $10 $0c $1a $00 $41 $08 $33 $0d $06 $27 $00 $20 $2d $00 $1f $23 $29
.db $33 $0d $08 $28 $01 $4d $00 $14 $02 $03 $00 $0f $03 $11 $33 TextButton
text9ab5:
.db $0a $0a $16 $00 $03 $2f $13 $02 $29 $14 $00 $07 $02 $10 $19 $3d $33 TextNewLine
.db $20 $0e $33 $00 $41 $0a $16 $01 $29 $19 $06 $00 $2c $06 $27 $15 $02 $4c TextButton
.db $0a $1f $2f $10 $4c $0a $1f $2f $10 $4c TextButtonEnd
; WaTaSiHa DoKuGaSuKaRa MiWo MaMoRuGaSuKuRiA- ToIU SoUTiGa[Wait for button press and blank text]
; KoKoNi UtuTeIRuTo KiITaNoDaGa[Line break]
; MiSeGa DoKoNiARuNoKa WaKaRaNaI.[Wait for button press and blank text]
; KoMatuTa.KoMatuTa.[Exit after button press]

text9ae5:
.db $0a $0a $1a $00 $01 $02 $13 $21 $0c $32 $2f $49 $40 $0d $4c TextNewLine
.db $41 $2e $15 $00 $37 $26 $03 $40 $0c $32 $03 $4c TextButton
text9b02:
.db $15 $4d $2e $11 $30 $2f $13 $4c $06 $27 $06 $2f $13 $37 $22 $2e $4c TextNewLine
.db $06 $2e $45 $2e $0c $13 $11 $32 $4c TextButtonEnd
; KoKoHa AITeMuSiyotuPuDeSu.[Line break]
; DoNNa GoYoUDeSiyoU.[Wait for button press and blank text]
; Na-NTiyatuTe.KaRaKatuTeGoMeN.[Line break]
; KaNBeNSiTeTiyo.[Exit after button press]

text9b1e:
.db $0a $2e $15 $14 $0a $16 $00 $05 $20 $0e $33 $00 $01 $2f $13 TextNewLine
.db $43 $2f $08 $28 $00 $0c $10 $40 $0c $32 $4c TextButton
text9b3a:
.db $33 $0d $08 $28 $01 $4d $00 TextNumber $22 $0e $10 $40 $0d $4c TextNewLine
.db $24 $0d $02 $40 $0c $32 $4c $00 $06 $02 $1f $0d $06 $4c TextEnd
; KoNNaToKoNi OMiSeGa AtuTe[Line break]
; BituKuRi SiTaDeSiyo.[Wait for button press and blank text]
; GaSuKuRiA- [number]MeSeTaDeSu.[Line break]
; YaSuIDeSiyo. KaIMaSuKa.[Exit immediately]

text9b58:
.db $01 $28 $33 $14 $03 $4c $1f $10 $07 $13 $18 $4c TextButtonEnd
; ARiGaToU.MaTaKiTeNe.[Exit after button press]

text9b65:
.db $05 $06 $18 $33 $15 $02 $19 $4d $4c $00 $0c $09 $13 $2e $15 $4d $4c
text9b76:
.db $05 $24 $00 $23 $2f $10 $02 $15 $02 $4c TextNewLine
.db $23 $03 $00 $03 $2f $13 $01 $36 $15 $02 $26 $4c TextButtonEnd
; OKaNeGaNaINo-. SiKeTeNNa-.OYa MotuTaINaI.[Line break]
; MoU UtuTeAGeNaIYo.[Exit after button press]

text9b8e:
.db $0d $4a $4d $0d $4b $4d $14 $1a $00 $1d $02 $0b $0d $29 $4c TextButtonEnd
; SuPe-SuPo-ToHa HeISaSuRu.[Exit after button press]

text9b9e:
.db $47 $0d $4b $4d $14 $2d $00 $46 $2f $0c $31 $03 $0d $29 $3c $4c TextButtonEnd
; PaSuPo-ToWo BotuSiyuUSuRuZo.[Exit after button press]

text9baf:
.db $0a $0a $1a $00 $40 $3c $28 $0d $0e $02 $19 $00 $0d $08 $2a $4c TextNewLine
.db $0f $14 $1a $00 $0b $21 $06 $2f $10 $40 $0c $32 $03 $4c TextButtonEnd
; KoKoHa DeZoRiSuSeINo SuKuRe.[Line break]
; SoToHa SaMuKatuTaDeSiyoU.[Exit after button press]

text9bcf:
.db $47 $29 $1f $0e $02 $06 $27 $19 $00 $02 $20 $2e $1a $00 $1e $14 $2e $41 $0a $19 $1f $11 $16 $00 $0d $2e $40 $02 $1f $0d $4c TextButtonEnd
; PaRuMaSeIKaRaNo IMiNHa HoToNDoKoNoMaTiNi SuNDeIMaSu.[Exit after button press]

text9bef:
.db $2c $10 $0c $00 $0a $19 $1e $0c $19 $0a $14 $1a TextNewLine
.db $26 $08 $0c $27 $15 $02 $09 $41 $00 $07 $10 $19 $00 $24 $1f $05 $08 $16 TextButton
text9c0f:
.db $0a $19 $1e $0c $19 $00 $39 $31 $03 $20 $2e $00 $40 $3c $28 $01 $2e $19 $21 $27 $33 $00 $01 $29 $0f $03 $26 $4c TextButtonEnd
; WaTaSi KoNoHoSiNoKoToHa[Line break]
; YoKuSiRaNaIKeDo KiTaNo YaMaOKuNi[Wait for button press and blank text]
; KoNoHoSiNo ZiyuUMiN DeZoRiANNoMuRaGa ARuSoUYo.[Exit after button press]

text9c2c:
.db $15 $16 $00 $27 $0c $4d $08 $2d $00 $10 $05 $0d $2e $3d $14 $4c TextNewLine
.db $0f $2a $15 $27 $42 $00 $27 $0a $16 $01 $40 $00 $40 $07 $10 TextButton
text9c4d:
.db $0f $4d $41 $00 $01 $08 $0d $00 $0c $4d $29 $41 $00 $01 $4d $1f $4d TextNewLine
.db $2d $00 $0f $2b $04 $15 $0b $2a $4c TextButton
text9c69:
.db $0a $2a $27 $19 $00 $44 $07 $1a $00 $0b $02 $07 $32 $03 $19 TextNewLine
.db $11 $06 $27 $2d $00 $1a $2f $07 $0d $29 $3d $2b $03 $4c TextButton
text9c88:
.db $44 $39 $2d $00 $02 $19 $2f $13 $02 $29 $4c TextButtonEnd
; NaNi RaSi-KuWo TaOSuNDaTo.[Line break]
; SoReNaRaBa RaKoNiADe DeKiTa[Wait for button press and blank text]
; So-Do AKuSu Si-RuDo A-Ma-[Line break]
; Wo SoRoENaSaRe.[Wait for button press and blank text]
; KoReRaNo BuKiHa SaIKiyoUNo[Line break]
; TiKaRaWo HatuKiSuRuDaRoU.[Wait for button press and blank text]
; BuZiWo INotuTeIRu.[Exit after button press]

text9c94:
.db $27 $0a $16 $01 $40 $00 $40 $07 $10 $00 $44 $07 $1a $00 $0e $02 $15 $29 $11 $06 $27 $2d $00 $1b $22 $13 $02 $29 $2e $3d $4c TextButton
text9cb4:
.db $27 $0c $4d $08 $1a $00 $0f $2a $2d $00 $07 $27 $2f $13 TextNewLine
.db $01 $29 $37 $29 $00 $10 $02 $26 $03 $09 $02 $19 $00 $2c $08 $0e $02 $19 TextButton
text9cd6:
.db $01 $11 $0a $11 $16 $00 $06 $08 $0c $13 $0c $1f $2f $10 $14 $02 $03 $4c TextButtonEnd
; RaKoNiADe DeKiTa BuKiHa SeINaRuTiKaRaWo HiMeTeIRuNDa.[Wait for button press and blank text]
; RaSi-KuHa SoReWo KiRatuTe[Line break]
; ARuGoRu TaIYoUKeINo WaKuSeINo[Wait for button press and blank text]
; ATiKoTiNi KaKuSiTeSiMatuTaToIU.[Exit after button press]

text9ce9:
.db $40 $3c $28 $0d $0e $02 $1a $00 $0a $05 $28 $19 $1e $0c $40 $0d $4c TextButtonEnd
; DeZoRiSuSeIHa KoORiNoHoSiDeSu.[Exit after button press]

text9cfb:
.db $0a $05 $28 $19 $00 $24 $1f $19 $15 $06 $16 $1a TextNewLine
.db $08 $3a $2a $24 $0d $02 $14 $0a $2b $23 $00 $01 $29 $26 $03 $40 $0d $4c TextButtonEnd
; KoORiNo YaMaNoNaKaNiHa[Line break]
; KuZuReYaSuIToKoRoMo ARuYoUDeSu.[Exit after button press]

text9d1b:
.db $01 $29 $11 $49 $27 $19 $0a $03 $36 $2e $1a $00 $1f $2c $28 $2d TextNewLine
.db $0a $05 $28 $19 $00 $24 $1f $16 $00 $06 $0a $1f $2a $13 $02 $1f $0d $4c TextButtonEnd
; ARuTiPuRaNoKoUGeNHa MaWaRiWo[Line break]
; KoORiNo YaMaNi KaKoMaReTeIMaSu.[Exit after button press]

text9d3f:
.db $0a $19 $1e $0c $1a $00 $1b $30 $08 $18 $2e $16 $00 $02 $11 $41 TextNewLine
.db $16 $2f $0c $32 $08 $33 $00 $01 $28 $1f $0d $4c TextButton
text9d5d:
.db $0f $19 $14 $07 $16 $00 $14 $23 $0b $2a $10 $00 $1e $19 $05 $1a TextNewLine
.db $02 $08 $28 $49 $0d $14 $4d $11 $14 $00 $26 $42 $2a TextButton
text9d7c:
.db $0c $2e $0e $02 $15 $29 $00 $1e $19 $05 $14 $0c $13 TextNewLine
.db $40 $3c $28 $01 $2e $16 $00 $1f $12 $27 $2a $13 $02 $29 $19 $40 $0d $4c TextButtonEnd
; KoNoHoSiHa HiyaKuNeNNi ITiDo[Line break]
; NituSiyoKuGa ARiMaSu.[Wait for button press and blank text]
; SoNoToKiNi ToMoSaReTa HoNoOHa[Line break]
; IKuRiPuSuTo-TiTo YoBaRe[Wait for button press and blank text]
; SiNSeINaRu HoNoOToSiTe[Line break]
; DeZoRiANNi MaTuRaReTeIRuNoDeSu.[Exit after button press]

text9d9d:
.db $35 $01 $27 $2e $19 $00 $0c $10 $02 $05 $07 $42 $19 TextNewLine
.db $0c $16 $2e $33 $00 $26 $20 $33 $04 $2f $10 $0f $03 $3d $4c TextButton
text9dbb:
.db $05 $0f $2b $0c $24 $4c TextButtonEnd
; GuARaNNo SiTaIOKiBaNo[Line break]
; SiNiNGa YoMiGaEtuTaSoUDa.[Wait for button press and blank text]
; OSoRoSiYa.[Exit after button press]

text9dc2:
.db $14 $15 $28 $19 $00 $44 $27 $08 $1a TextNewLine
.db $03 $0f $12 $07 $42 $06 $28 $3d $4c $07 $2d $12 $09 $15 $26 $4c TextButtonEnd
; ToNaRiNo BuRaKuHa[Line break]
; USoTuKiBaKaRiDa.KiWoTuKeNaYo.[Exit after button press]

text9ddd:
.db $0a $19 $21 $27 $19 $00 $07 $10 $19 $00 $24 $1f $19 $21 $0a $03 $16 TextNewLine
.db $0a $2b $15 $19 $14 $03 $33 $00 $01 $29 $3a $27 $4c TextButtonEnd
; KoNoMuRaNo KiTaNo YaMaNoMuKoUNi[Line break]
; KoRoNaNoToUGa ARuZuRa.[Exit after button press]

text9dfd:
.db $0a $2b $15 $19 $14 $03 $19 $00 $16 $0c $16 $1a $00 $40 $3c $28 $0d $19 $41 $03 $08 $12 $33 $00 $01 $29 $3a $27 $4c TextButton
text9e1b:
.db $2c $0c $27 $19 $00 $15 $06 $1f $33 $00 $02 $29 $3a $27 $4c TextNewLine
.db $26 $2b $0c $08 $3a $27 $4c TextButtonEnd
; KoRoNaNoToUNo NiSiNiHa DeZoRiSuNoDoUKuTuGa ARuZuRa.[Wait for button press and blank text]
; WaSiRaNo NaKaMaGa IRuZuRa.[Line break]
; YoRoSiKuZuRa.[Exit after button press]

text9e33:
.db $27 $04 $29 $1f $12 $28 $4d $16 $1a $00 $27 $04 $29 $1f $45 $28 $4d TextNewLine
.db $14 $02 $03 $00 $07 $19 $20 $33 $00 $15 $29 $3a $27 $26 $4c TextButton
text9e55:
.db $01 $19 $00 $07 $19 $20 $1a $00 $05 $02 $0c $02 $06 $27 TextNewLine
.db $2c $0c $27 $19 $00 $0c $32 $08 $28 $32 $03 $16 $00 $0c $10 $02 $09 $41 TextButton
text9e77:
.db $27 $0a $16 $01 $19 $00 $12 $46 $16 $00 $02 $2a $15 $02 $14 TextNewLine
.db $1b $06 $27 $43 $13 $0c $1f $03 $3a $27 $26 $4c TextButtonEnd
; RaERuMaTuRi-NiHa RaERuMaBeRi-[Line break]
; ToIU KiNoMiGa NaRuZuRaYo.[Wait for button press and blank text]
; ANo KiNoMiHa OISiIKaRa[Line break]
; WaSiRaNo SiyoKuRiyoUNi SiTaIKeDo[Wait for button press and blank text]
; RaKoNiANo TuBoNi IReNaITo[Line break]
; HiKaRaBiTeSiMaUZuRaYo.[Exit after button press]

text9e94:
.db $04 $01 $2b $49 $28 $3a $21 $00 $14 $02 $03 $19 $2d TextNewLine
.db $0c $2f $13 $29 $3a $27 $06 $4c TextEnd
; EARoPuRiZuMu ToIUNoWo[Line break]
; SituTeRuZuRaKa.[Exit immediately]

text9eab:
.db $0a $19 $26 $14 $00 $11 $33 $03 $00 $0e $06 $02 $33 TextNewLine
.db $20 $04 $29 $0f $03 $3a $27 $26 $4c TextButtonEnd
; KoNoYoTo TiGaU SeKaIGa[Line break]
; MiERuSoUZuRaYo.[Exit after button press]

text9ec3:
.db $02 $11 $41 $00 $20 $13 $20 $10 $02 $23 $19 $3a $27 $26 $4c TextButtonEnd
; ITiDo MiTeMiTaIMoNoZuRaYo.[Exit after button press]

text9ed3:
.db $0a $19 $44 $27 $08 $19 $00 $20 $2e $15 $1a $00 $47 $29 $1f $19 TextNewLine
.db $1b $14 $43 $14 $2d $00 $07 $27 $2f $13 $29 $3a $27 $4c TextButtonEnd
; KoNoBuRaKuNo MiNNaHa PaRuMaNo[Line break]
; HiToBiToWo KiRatuTeRuZuRa.[Exit after button press]

text9ef3:
.db $0a $2b $15 $19 $14 $03 $16 $1a $00 $02 $19 $11 $19 $02 $3a $20 $33 TextNewLine
.db $01 $29 $2e $3d $0d $4c TextButtonEnd
; KoRoNaNoToUNiHa INoTiNoIZuMiGa[Line break]
; ARuNDaSu.[Exit after button press]

text9f0c:
.db $40 $3c $28 $0d $19 $00 $41 $03 $08 $12 $19 $00 $11 $06 TextNewLine
.db TextNumber $06 $02 $40 $00 $2c $4d $49 $40 $07 $29 $2e $3d $0d $26 $4c TextButtonEnd
; DeZoRiSuNo DoUKuTuNo TiKa[Line break]
; [number]KaIDe Wa-PuDeKiRuNDaSuYo.[Exit after button press]

text9f2c:
.db $27 $04 $29 $1f $45 $28 $4d $1a $00 $01 $05 $02 $02 $2b $2d $0c $10 TextNewLine
.db $07 $19 $20 $40 $00 $0e $2e $28 $32 $03 $16 $00 $12 $06 $03 $3d $0d $4c TextButtonEnd
; RaERuMaBeRi-Ha AOIIRoWoSiTa[Line break]
; KiNoMiDe SeNRiyoUNi TuKaUDaSu.[Exit after button press]

text9f51:
.db $27 $04 $29 $1f $12 $28 $4d $19 $00 $1f $04 $40 $00 $08 $28 $0d $10 $29 $2d $00 $12 $06 $03 $14 $00 $20 $33 $00 $15 $29 $2e $3d $0d $4c TextButtonEnd
; RaERuMaTuRi-No MaEDe KuRiSuTaRuWo TuKaUTo MiGa NaRuNDaSu.[Exit after button press]

text9f74:
.db $0a $19 $44 $27 $08 $1a $00 $47 $29 $1f $19 $00 $1b $14 $43 $14 $2d TextNewLine
.db $06 $2e $36 $02 $0c $1f $0d $4c TextButtonEnd
; KoNoBuRaKuHa PaRuMaNo HiToBiToWo[Line break]
; KaNGeISiMaSu.[Exit after button press]

text9f8f:
.db $0a $19 $21 $27 $1a $00 $0f $48 $01 $14 $00 $02 $02 $1f $0d $4c TextButton
.db $41 $08 $33 $0d $19 $00 $15 $06 $2d TextNewLine
.db $26 $03 $0a $0f $00 $0a $27 $2a $1f $0c $10 $4c TextButtonEnd
; KoNoMuRaHa SoPiATo IIMaSu.[Wait for button press and blank text]
; DoKuGaSuNo NaKaWo[Line break]
; YoUKoSo KoRaReMaSiTa.[Exit after button press]

text9fb7:
.db $2c $10 $0c $1a $00 $0a $19 $21 $27 $19 $00 $0f $2e $11 $32 $03 TextNewLine
.db $40 $0d $4c $0a $19 $00 $07 $28 $19 $0e $02 $40 $00 $1e $06 $19 TextButton
text9fd9:
.db $1f $11 $24 $00 $21 $27 $06 $27 $00 $14 $38 $0b $2a $10 $00 $0f $48 $01
.db $1a $00 $14 $13 $23 $00 $1f $3a $0c $02 $19 $40 $0d $4c TextButton
text9ffa:
.db $41 $03 $06 $00 TextNumber $22 $0e $10 $00 $07 $1c $0c $13 TextNewLine
.db $08 $3d $0b $02 $4c TextEnd
; WaTaSiHa KoNoMuRaNo SoNTiyoU[Line break]
; DeSu.KoNo KiRiNoSeIDe HoKaNo[Wait for button press and blank text]
; MaTiYa MuRaKaRa ToZaSaReTa SoPiAHa ToTeMo MaZuSiINoDeSu.[Wait for button press and blank text]
; DoUKa [number]MeSeTa KiHuSiTe[Line break]
; KuDaSaI.[Exit immediately]

texta00e:
.db $0f $03 $40 $0d $06 $4c $38 $2e $18 $2e $40 $0d $4c $03 $03 $2f $4c TextButtonEnd
; SoUDeSuKa.ZaNNeNDeSu.UUtu.[Exit after button press]

texta020:
.db $05 $10 $33 $02 $16 $00 $1f $3a $0c $02 $19 $40 $0d $18 $4c TextNewLine
.db $0b $43 $0c $02 $00 $26 $19 $15 $06 $40 $0d $4c TextButtonEnd
; OTaGaINi MaZuSiINoDeSuNe.[Line break]
; SaBiSiI YoNoNaKaDeSu.[Exit after button press]

texta03d:
.db $01 $28 $33 $14 $03 $4c TextNewLine
.db $2c $2a $2c $2a $19 $00 $02 $02 $12 $10 $04 $16 $26 $2a $42 TextButton
texta054:
.db $4a $29 $0e $03 $0d $33 $00 $22 $40 $31 $4d $0b $2d TextNewLine
.db $10 $05 $0d $14 $07 $16 $00 $12 $06 $2f $10 $00 $10 $13 $33 TextButton
texta072:
.db $20 $3a $03 $20 $16 $01 $29 $00 $0c $1f $19 $00 $0b $46 $13 $2e $19 TextNewLine
.db $0c $10 $16 $00 $03 $22 $13 $01 $29 $0f $03 $40 $0d $4c TextButtonEnd
; ARiGaToU.[Line break]
; WaReWaReNo IITuTaENiYoReBa[Wait for button press and blank text]
; PeRuSeUSuGa MeDeyu-SaWo[Line break]
; TaOSuToKiNi TuKatuTa TaTeGa[Wait for button press and blank text]
; MiZuUMiNiARu SiMaNo SaBoTeNNo[Line break]
; SiTaNi UMeTeARuSoUDeSu.[Exit after button press]

texta093:
.db $01 $10 $0c $00 $36 $4d $1f $4d $19 $00 $20 $07 $11 $30 $2e $26 $4c TextNewLine
.db $01 $15 $10 $00 $1f $0d $10 $4d $0c $0d $13 $21 $00 $06 $2f $10 $4c TextEnd
; ATaSi Ge-Ma-No MiKiTiyaNYo.[Line break]
; ANaTa MaSuTa-SiSuTeMu KatuTa.[Exit immediately]

texta0b7:
.db $1f $01 $00 $01 $10 $0c $14 $05 $2e $15 $39 $00 $36 $4d $1f $4d $18 $4c $24 $2f $47 $00 $04 $1c $04 $21 $05 $2e $36 $2e $1a $00 $35 $4d $18 $4c TextButtonEnd
; MaA ATaSiToONNaZi Ge-Ma-Ne.YatuPa EHuEMuONGeNHa Gu-Ne.[Exit after button press]

texta0dc:
.db $24 $2f $3d $4d $00 $01 $15 $10 $00 $1a $24 $08 $00 $06 $2f $13 TextNewLine
.db $27 $2f $0c $30 $02 $26 $4d $00 $23 $4d $00 $49 $2e $00 $49 $2e $4c TextButtonEnd
; YatuDa- ANaTa HaYaKu KatuTe[Line break]
; RatuSiyaIYo- Mo- PuN PuN.[Exit after button press]

texta0ff:
.db $27 $0c $4d $08 $33 $00 $09 $2e $28 $32 $08 $2d $00 $16 $34 $29 TextNewLine
.db $1f $04 $1a $00 $0a $19 $21 $27 $23 $00 $25 $10 $06 $3d $2f $10 $4c TextButtonEnd
; RaSi-KuGa KeNRiyoKuWo NiGiRu[Line break]
; MaEHa KoNoMuRaMo YuTaKaDatuTa.[Exit after button press]

texta122:
.db $20 $3a $03 $20 $19 $00 $20 $15 $20 $19 $00 $24 $1f $19 $00 $15 $06 $16 $10 $39 $21 $00 $14 $02 $03 $00 $41 $03 $0c $33 $00 $02 $1f $0d $4c TextButtonEnd
; MiZuUMiNo MiNaMiNo YaMaNo NaKaNiTaZiMu ToIU DoUSiGa IMaSu.[Exit after button press]

texta146:
.db $47 $29 $1f $0e $02 $1a $00 $07 $2a $02 $15 $00 $1e $0c $3d $14 TextNewLine
.db $07 $07 $1f $0c $10 $33 $00 $1e $2e $14 $03 $40 $0d $06 $4c TextEnd
; PaRuMaSeIHa KiReINa HoSiDaTo[Line break]
; KiKiMaSiTaGa HoNToUDeSuKa.[Exit immediately]

texta167:
.db $02 $2f $13 $20 $10 $02 $15 $4d $4c TextButtonEnd
; ItuTeMiTaINa-.[Exit after button press]

texta171:
.db $0f $03 $40 $0d $06 $4c $2c $10 $0c $1a $00 $23 $2f $14 TextNewLine
.db $08 $03 $07 $19 $00 $07 $2a $02 $15 $14 $0a $2b $1d $02 $07 $10 $02 $4c TextButtonEnd
; SoUDeSuKa.WaTaSiHa MotuTo[Line break]
; KuUKiNo KiReINaToKoRoHeIKiTaI.[Exit after button press]

texta193:
.db $01 $28 $33 $14 $03 $4c TextButton
.db $1f $10 $07 $13 $18 $4c TextButtonEnd
; ARiGaToU.[Wait for button press and blank text]
; MaTaKiTeNe.[Exit after button press]

texta1a1:
.db $09 $11 $4c TextButtonEnd
; KeTi.[Exit after button press]

texta1a5:
.db $42 $06 $16 $0d $2e $40 $18 $04 $4c TextButtonEnd
; BaKaNiSuNDeNeE.[Exit after button press]

texta1af:
.db $4c $4c $4c $4c $4c $4c $4c $4c $4c TextButtonEnd
; .........[Exit after button press]

texta1b9:
.db $0f $03 $06 $4c $0f $2a $40 $0a $0f $00 $01 $29 $37 $29 $05 $03 $19 TextNewLine
.db $21 $0d $22 $3d $4c TextButton
.db $2c $10 $0c $23 $00 $13 $12 $3d $2c $0e $13 $23 $27 $03 $26 $4c TextButtonEnd
; SoUKa.SoReDeKoSo ARuGoRuOUNo[Line break]
; MuSuMeDa.[Wait for button press and blank text]
; WaTaSiMo TeTuDaWaSeTeMoRaUYo.[Exit after button press]

texta1e2:
.db $05 $05 $00 $01 $2e $10 $23 $00 $14 $39 $0a $22 $27 $2a $10 $19 $06 TextNewLine
.db $06 $2c $02 $0f $03 $16 $4c TextButton
texta1fc:
.db $0f $14 $16 $40 $29 $00 $1e $03 $1e $03 $1a $00 $01 $29 $2e $39 $30 $33 $2c $0c $1a $00 $0a $0a $16 $00 $02 $29 $1e $03 $33 TextButton
.db $07 $27 $08 $40 $00 $02 $02 $2c $02 $4c TextButtonEnd
; OO ANTaMo ToZiKoMeRaReTaNoKa[Line break]
; KaWaISoUNi.[Wait for button press and blank text]
; SoToNiDeRu HoUHoUHa ARuNZiyaGaWaSiHa KoKoNi IRuHoUGa[Wait for button press and blank text]
; KiRaKuDe IIWaI.[Exit after button press]

texta227:
.db $0a $19 $0b $07 $1d $1a $00 $02 $06 $15 $02 $1e $03 $33 TextNewLine
.db $02 $02 $26 $4c $00 $09 $02 $43 $1d $02 $33 $00 $02 $29 $2e $3d $4c TextButtonEnd
; KoNoSaKiHeHa IKaNaIHoUGa[Line break]
; IIYo. KeIBiHeIGa IRuNDa.[Exit after button press]

texta248:
.db $1b $07 $06 $04 $0d $15 $27 $00 $02 $1f $19 $03 $11 $39 $30 $3c $4c TextButtonEnd
; HiKiKaESuNaRa IMaNoUTiZiyaZo.[Exit after button press]

texta25a:
.db $2b $4d $41 $47 $0d $2d $00 $23 $2f $13 $02 $29 $06 $4c TextEnd
; Ro-DoPaSuWo MotuTeIRuKa.[Exit immediately]

texta269:
.db $41 $2a $41 $2a TextNewLine
.db $2e $00 $0a $2a $1a $00 $16 $0e $23 $19 $3d $4c TextButton
texta27b:
.db $2b $46 $2f $14 $3d $14 $00 $05 $23 $2f $13 $00 $15 $22 $29 $15 $26 $4c $2b $03 $16 $00 $44 $11 $0a $2e $40 $24 $29 $4c TextButtonEnd
; DoReDoRe[Line break]
; N KoReHa NiSeMoNoDa.[Wait for button press and blank text]
; RoBotuToDaTo OMotuTe NaMeRuNaYo.RoUNi BuTiKoNDeYaRu.[Exit after button press]

texta29a:
.db $05 $2a $2d $00 $0a $0a $06 $27 $00 $3d $0c $13 $08 $2a $29 $19 $06 $4c $40 $23 $00 $21 $3d $3d $26 $4c TextButtonEnd
; OReWo KoKoKaRa DaSiTeKuReRuNoKa.DeMo MuDaDaYo.[Exit after button press]

texta2b5:
.db $27 $0c $4d $08 $2d $00 $10 $05 $0f $03 $15 $2e $13 TextNewLine
.db $21 $46 $03 $3d $26 $4c TextButtonEnd
; RaSi-KuWo TaOSoUNaNTe[Line break]
; MuBoUDaYo.[Exit after button press]

texta2ca:
.db $2c $10 $0c $10 $11 $1a $00 $27 $0c $4d $08 $19 $00 $02 $09 $16 $04 $16 $0b $2a $13 $0c $1f $03 $19 $26 $4c $00 $03 $2f $03 $03 $4c TextButtonEnd
; WaTaSiTaTiHa RaSi-KuNo IKeNiENiSaReTeSiMaUNoYo. UtuUU.[Exit after button press]

texta2ec:
.db $35 $01 $27 $2e $16 $01 $29 $00 $26 $2b $02 $2d TextNewLine
.db $13 $16 $02 $2a $10 $06 $02 $4c TextEnd
; GuARaNNiARu YoRoIWo[Line break]
; TeNiIReTaKaI.[Exit immediately]

texta302:
.db $0f $2a $1a $00 $05 $14 $0c $01 $15 $19 $00 $21 $0a $03 $33 $2c $16 TextNewLine
.db $01 $29 $2e $3d $26 $4c TextButtonEnd
; SoReHa OToSiANaNo MuKoUGaWaNi[Line break]
; ARuNDaYo.[Exit after button press]

texta31b:
.db $07 $20 $2f $13 $00 $0d $37 $02 $18 $4c TextButtonEnd
; KiMituTe SuGoINe.[Exit after button press]

texta326:
.db $27 $0c $4d $08 $16 $00 $40 $01 $2f $10 $23 $19 $1a $00 $20 $15 TextNewLine
.db $0f $19 $00 $1f $28 $32 $08 $40 TextButton
.db $10 $1f $0c $02 $2d $00 $03 $42 $2c $2a $29 $0f $03 $3d $26 $4c TextButtonEnd
; RaSi-KuNi DeAtuTaMoNoHa MiNa[Line break]
; SoNo MaRiyoKuDe[Wait for button press and blank text]
; TaMaSiIWo UBaWaReRuSoUDaYo.[Exit after button press]

texta351:
.db $0f $03 $06 $4c $0f $2a $23 $00 $26 $06 $2b $03 $4c TextNewLine
.db $1f $10 $00 $02 $12 $40 $23 $00 $23 $41 $2f $13 $08 $29 $33 $02 $02 $4c TextButtonEnd
; SoUKa.SoReMo YoKaRoU.[Line break]
; MaTa ITuDeMo MoDotuTeKuRuGaII.[Exit after button press]

texta372:
.db $42 $24 $1f $4d $2a $19 $00 $05 $06 $19 $03 $04 $16 $1a TextNewLine
.db $14 $03 $33 $01 $29 $4c TextButton
.db $01 $19 $14 $03 $16 $00 $1b $20 $12 $33 $00 $06 $08 $0b $2a $13 TextNewLine
.db $02 $29 $16 $11 $33 $02 $15 $02 $4c TextButtonEnd
; BaYaMa-ReNo OKaNoUENiHa[Line break]
; ToUGaARu.[Wait for button press and blank text]
; ANoToUNi HiMiTuGa KaKuSaReTe[Line break]
; IRuNiTiGaINaI.[Exit after button press]

texta3a3:
.db $15 $16 $0c $16 $07 $10 $3d $4c $00 $05 $22 $04 $10 $11 TextNewLine
.db $2c $29 $0b $00 $0d $2e $40 $18 $04 $3c $4c TextButtonEnd
; NaNiSiNiKiTaDa. OMeETaTi[Line break]
; WaRuSa SuNDeNeEZo.[Exit after button press]

texta3be:
.db $02 $24 $15 $00 $26 $06 $2e $33 $0d $29 $4c TextButtonEnd
; IYaNa YoKaNGaSuRu.[Exit after button press]

texta3ca:
.db $0a $2a $06 $27 $00 $0b $07 $1a $00 $07 $2d $12 $09 $13 $4c TextNewLine
.db $2c $06 $2a $20 $11 $2d $00 $1b $3d $28 $1d $00 $02 $07 $15 $0b $02 $4c TextButtonEnd
; KoReKaRa SaKiHa KiWoTuKeTe.[Line break]
; WaKaReMiTiWo HiDaRiHe IKiNaSaI.[Exit after button press]

texta3ed:
.db $0a $0a $3d $09 $19 $00 $1a $15 $0c $3d $33 $00 $3d $23 $01 TextNewLine
.db $14 $02 $03 $00 $03 $27 $15 $02 $0c $19 $00 $23 $2f $13 $02 $29 TextButton
texta40e:
.db $08 $28 $0d $10 $29 $2d $00 $27 $0c $4d $08 $0b $1f $1a TextNewLine
.db $07 $27 $2f $13 $05 $27 $2a $29 $4c TextButton
.db $15 $16 $06 $00 $1b $20 $12 $33 $00 $01 $29 $16 $11 $33 $02 $15 $02 $4c TextButtonEnd
; KoKoDaKeNo HaNaSiDaGa DaMoA[Line break]
; ToIU URaNaISiNo MotuTeIRu[Wait for button press and blank text]
; KuRiSuTaRuWo RaSi-KuSaMaHa[Line break]
; KiRatuTeORaReRu.[Wait for button press and blank text]
; NaNiKa HiMiTuGa ARuNiTiGaINaI.[Exit after button press]

texta43a:
.db $0a $19 $00 $1b $1a $00 $1b $30 $08 $18 $2e $16 $00 $02 $11 $41 TextNewLine
.db $19 $00 $16 $2f $0c $32 $08 $19 $00 $14 $07 $16 $00 $12 $09 $10 TextButton
texta45c:
.db $23 $19 $3d $4c $00 $41 $27 $37 $2e $19 $00 $23 $2f $13 $02 $29 TextNewLine
.db $1e $03 $0e $07 $2d $00 $08 $2a $29 $15 $27 $42 $00 $0d $0a $0c TextButton
texta47e:
.db $2c $09 $13 $00 $01 $36 $13 $23 $00 $26 $02 $33 $00 $41 $03 $3d $4c TextEnd
; KoNo HiHa HiyaKuNeNNi ITiDo[Line break]
; No NituSiyoKuNo ToKiNi TuKeTa[Wait for button press and blank text]
; MoNoDa. DoRaGoNNo MotuTeIRu[Line break]
; HoUSeKiWo KuReRuNaRaBa SuKoSi[Wait for button press and blank text]
; WaKeTe AGeTeMo YoIGa DoUDa.[Exit immediately]

texta490:
.db $40 $1a $00 $02 $08 $28 $49 $0d $14 $4d $11 $2d TextNewLine
.db $03 $09 $14 $29 $33 $02 $02 $4c TextButtonEnd
; DeHa IKuRiPuSuTo-TiWo[Line break]
; UKeToRuGaII.[Exit after button press]

texta4a6:
.db $02 $27 $15 $02 $19 $06 $4c $0f $2a $39 $30 $01 $00 $05 $22 $04 $1a TextNewLine
.db $15 $16 $0c $16 $00 $07 $10 $2e $3d $4c TextButtonEnd
; IRaNaINoKa.SoReZiyaA OMeEHa[Line break]
; NaNiSiNi KiTaNDa.[Exit after button press]

texta4c3:
.db $1e $03 $0e $07 $2d $00 $23 $2f $13 $15 $02 $40 $1a $15 $02 $06 $4c TextNewLine
.db $15 $22 $29 $15 $26 $4c TextButtonEnd
; HoUSeKiWo MotuTeNaIDeHaNaIKa.[Line break]
; NaMeRuNaYo.[Exit after button press]

texta4dc:
.db $0a $2e $15 $14 $0a $2b $16 $00 $05 $20 $0e $33 $00 $01 $2f $13 TextNewLine
.db $37 $22 $2e $15 $0b $02 $4c TextButton
.db $0c $32 $4d $14 $09 $4d $07 $2d $00 TextNumber $22 $0e $10 $40 TextNewLine
.db $02 $06 $33 $40 $0d $06 $4c TextEnd
; KoNNaToKoRoNi OMiSeGa AtuTe[Line break]
; GoMeNNaSaI.[Wait for button press and blank text]
; Siyo-ToKe-KiWo [number]MeSeTaDe[Line break]
; IKaGaDeSuKa.[Exit immediately]

texta50c:
.db $05 $05 $00 $2c $33 $40 $0c $00 $29 $12 $26 $4c $00 $12 $02 $16 TextNewLine
.db $27 $0c $4d $08 $2d $00 $10 $05 $0d $00 $10 $43 $16 $40 $29 $06 $4c TextButtonEnd
; OO WaGaDeSi RuTuYo. TuINi[Line break]
; RaSi-KuWo TaOSu TaBiNiDeRuKa.[Exit after button press]

texta52f:
.db $40 $1a $00 $0f $12 $34 $32 $03 $19 $00 $0c $09 $2e $2d $00 $0c $13 TextNewLine
.db $24 $2b $03 $4c $2c $0c $14 $00 $10 $10 $06 $03 $33 $26 $02 $4c TextButtonEnd
; DeHa SoTuGiyoUNo SiKeNWo SiTe[Line break]
; YaRoU.WaSiTo TaTaKaUGaYoI.[Exit after button press]

texta552:
.db $12 $26 $08 $15 $2f $10 $19 $03 $4c $29 $12 $26 $4c TextButton
.db $0f $2a $3d $09 $19 $11 $06 $27 $33 $00 $01 $2a $42 $26 $02 $4c TextButton
texta571:
.db $2c $0c $06 $27 $19 $00 $05 $08 $28 $23 $19 $14 $0c $13 TextNewLine
.db $1c $27 $4d $41 $1f $2e $14 $2d $00 $12 $06 $2c $0f $03 $4c TextButton
texta590:
.db $05 $1f $04 $19 $00 $06 $27 $3d $2d $00 $1f $23 $2f $13 $08 $2a $29 TextNewLine
.db $39 $30 $2b $03 $4c $00 $40 $1a $00 $25 $08 $33 $26 $02 $4c TextButtonEnd
; TuYoKuNatuTaNoU.RuTuYo.[Wait for button press and blank text]
; SoReDaKeNoTiKaRaGa AReBaYoI.[Wait for button press and blank text]
; WaSiKaRaNo OKuRiMoNoToSiTe[Line break]
; HuRa-DoMaNToWo TuKaWaSoU.[Wait for button press and blank text]
; OMaENo KaRaDaWo MaMotuTeKuReRu[Line break]
; ZiyaRoU. DeHa YuKuGaYoI.[Exit after button press]

texta5b2:
.db $1f $3d $1f $3d $00 $0c $31 $34 $32 $03 $33 $00 $10 $28 $2e $19 $03 $4c $40 $15 $05 $0c $13 $08 $29 $33 $26 $02 $4c TextButtonEnd
; MaDaMaDa SiyuGiyoUGa TaRiNNoU.DeNaOSiTeKuRuGaYoI.[Exit after button press]

texta5d0:
.db $23 $03 $00 $2c $0c $33 $00 $05 $0c $04 $29 $0a $14 $1a $00 $15 $02 $4c TextButtonEnd
; MoU WaSiGa OSiERuKoToHa NaI.[Exit after button press]

texta5e3:
.db $05 $1f $04 $0b $2e $33 $10 $1a $00 $41 $15 $10 $06 $15 $4c TextNewLine
.db $1f $1a $29 $19 $00 $41 $03 $08 $12 $16 $00 $2c $0c $19 $00 $40 $0c $19 TextButton
texta606:
.db $29 $12 $33 $00 $05 $29 $4c $0c $2f $13 $05 $29 $06 $4c TextEnd
; OMaESaNGaTaHa DoNaTaKaNa.[Line break]
; MaHaRuNo DoUKuTuNi WaSiNo DeSiNo[Wait for button press and blank text]
; RuTuGa ORu.SituTeORuKa.[Exit immediately]

texta615:
.db $29 $12 $16 $00 $12 $10 $04 $18 $42 $00 $15 $27 $17 $0a $14 $33 TextNewLine
.db $01 $29 $4c $00 $12 $2a $13 $07 $13 $1a $00 $08 $2a $1f $02 $06 $4c TextButtonEnd
; RuTuNi TuTaENeBa NaRaNuKoToGa[Line break]
; ARu. TuReTeKiTeHa KuReMaIKa.[Exit after button press]

texta638:
.db $0f $03 $06 $4c $00 $15 $27 $42 $00 $02 $2f $13 $23 TextNewLine
.db $0c $06 $10 $19 $15 $02 $0a $14 $39 $30 $19 $03 $4c TextButtonEnd
; SoUKa. NaRaBa ItuTeMo[Line break]
; SiKaTaNoNaIKoToZiyaNoU.[Exit after button press]

texta654:
.db $05 $1f $04 $10 $11 $19 $00 $0a $03 $41 $03 $1a TextNewLine
.db $0d $45 $13 $05 $20 $14 $05 $0c $3d $4c TextButton
texta66c:
.db $06 $06 $2f $13 $08 $29 $33 $00 $02 $02 $4c TextButtonEnd
; OMaETaTiNo KoUDoUHa[Line break]
; SuBeTeOMiToOSiDa.[Wait for button press and blank text]
; KaKatuTeKuRuGa II.[Exit after button press]

texta678:
.db $05 $2a $1a $00 $27 $0c $4d $08 $0b $1f $19 TextNewLine
.db $06 $36 $21 $0c $30 $3d $4c TextButton
texta68c:
.db $05 $2a $2d $10 $05 $0c $10 $14 $0a $2b $40 TextNewLine
.db $41 $03 $16 $23 $15 $27 $15 $02 $19 $0b $4c $00 $1b $2f $1b $2f $4c TextButtonEnd
; OReHa RaSi-KuSaMaNo[Line break]
; KaGeMuSiyaDa.[Wait for button press and blank text]
; OReWoTaOSiTaToKoRoDe[Line break]
; DoUNiMoNaRaNaINoSa. HituHitu.[Exit after button press]

texta6aa:
.db $27 $0c $4d $08 $0b $1f $16 $00 $0b $06 $27 $03 $15 $4c TextButtonEnd
; RaSi-KuSaMaNi SaKaRaUNa.[Exit after button press]

texta6b9:
.db $14 $03 $14 $03 $00 $0a $0a $1f $40 $00 $07 $10 $06 $4c TextNewLine
.db $03 $2e $19 $00 $02 $02 $24 $12 $27 $22 $4c TextButton
.db $0f $2e $15 $16 $00 $2c $0c $2d $00 $10 $05 $0c $10 $02 $19 $06 $4c TextEnd
; ToUToU KoKoMaDe KiTaKa.[Line break]
; UNNo IIYaTuRaMe.[Wait for button press and blank text]
; SoNNaNi WaSiWo TaOSiTaINoKa.[Exit immediately]

texta6e6:
.db $0f $03 $06 $4c $0f $2a $15 $27 $42 TextButton
.db $0f $19 $00 $06 $2e $33 $04 $33 $00 $1f $11 $33 $2f $13 $02 $10 TextNewLine
.db $0a $14 $2d $00 $05 $23 $02 $0c $29 $33 $02 $02 $4c TextButtonEnd
; SoUKa.SoReNaRaBa[Wait for button press and blank text]
; SoNo KaNGaEGa MaTiGatuTeITa[Line break]
; KoToWo OMoISiRuGaII.[Exit after button press]

texta70f:
.db $0a $19 $37 $16 $00 $05 $26 $2e $40 TextNewLine
.db $1c $38 $09 $10 $24 $12 $27 $3d $4c TextButton
.db $0a $03 $06 $02 $0b $0e $13 $24 $29 $4c TextButtonEnd
; KoNoGoNi OYoNDe[Line break]
; HuZaKeTaYaTuRaDa.[Wait for button press and blank text]
; KoUKaISaSeTeYaRu.[Exit after button press]

texta72e:
.db $05 $05 $4c $20 $2e $15 $00 $0d $1f $15 $06 $2f $10 $4c TextButton
.db $2c $10 $0c $19 $00 $0a $0a $2b $14 $00 $06 $27 $3d $1a TextButton
texta74c:
.db $41 $03 $24 $27 $00 $01 $0c $07 $00 $1f $28 $32 $08 $16 TextNewLine
.db $05 $06 $0b $2a $13 $02 $10 $27 $0c $02 $4c TextButton
texta767:
.db $26 $08 $3c $00 $0a $19 $26 $2d $00 $0d $08 $2f $13 $08 $2a $10 $4c TextNewLine
.db $23 $03 $0d $0a $0c $00 $05 $0f $06 $2f $10 $27 TextButton
texta786:
.db $10 $02 $1d $2e $15 $0a $14 $16 $00 $15 $2f $13 $02 $10 $3d $2b $03 $4c
.db $0a $0a $2b $06 $27 $00 $2a $02 $2d $00 $02 $03 $3c $4c TextButton
.db $01 $28 $0b $26 $4c TextNewLine
.db $05 $1f $04 $16 $00 $1a $15 $0c $10 $02 $0a $14 $33 $01 $29 $4c TextButton
.db $39 $12 $1a $00 $05 $1f $04 $19 $00 $11 $11 $1a TextNewLine
.db $01 $29 $37 $29 $19 $00 $05 $03 $3d $2f $10 $4c TextButton
.db $01 $08 $1f $19 $00 $0c $2b $1a $00 $08 $3a $2a $0b $28 TextNewLine
.db $27 $0c $4d $08 $00 $15 $07 $00 $02 $1f $00 $05 $1f $04 $1a TextButton
.db $11 $11 $19 $00 $01 $14 $2d $00 $12 $34 $00 $01 $29 $37 $29 $19 TextNewLine
.db $39 $32 $03 $05 $03 $14 $00 $15 $29 $06 $4c TextEnd
; OO.MiNNa SuMaNaKatuTa.[Wait for button press and blank text]
; WaTaSiNo KoKoRoTo KaRaDaHa[Wait for button press and blank text]
; DoUYaRa ASiKi MaRiyoKuNi[Line break]
; OKaSaReTeITaRaSiI.[Wait for button press and blank text]
; YoKuZo KoNoYoWo SuKutuTeKuReTa.[Line break]
; MoUSuKoSi OSoKatuTaRa[Wait for button press and blank text]
; TaIHeNNaKoToNi NatuTeITaDaRoU.KoKoRoKaRa ReIWo IUZo.[Wait for button press and blank text]
; ARiSaYo.[Line break]
; OMaENi HaNaSiTaIKoToGaARu.[Wait for button press and blank text]
; ZiTuHa OMaENo TiTiHa[Line break]
; ARuGoRuNo OUDatuTa.[Wait for button press and blank text]
; AKuMaNo SiRoHa KuZuReSaRi[Line break]
; RaSi-Ku NaKi IMa OMaEHa[Wait for button press and blank text]
; TiTiNo AToWo TuGi ARuGoRuNo[Line break]
; ZiyoUOUTo NaRuKa.[Exit immediately]

texta814:
.db $2c $10 $0c $00 $05 $13 $33 $20 $00 $11 $04 $11 $30 $2e $26 $4c TextNewLine
.db $02 $12 $23 $00 $05 $10 $26 $28 $00 $01 $28 $33 $14 $03 $4c TextButton
.db $0a $19 $36 $4d $21 $19 $00 $06 $2e $0f $03 $2d TextNewLine
.db $07 $06 $0e $13 $18 $4c $00 $1f $2f $13 $29 $2c $4c TextButtonEnd
; WaTaSi OTeGaMi TiETiyaNYo.[Line break]
; ITuMo OTaYoRi ARiGaToU.[Wait for button press and blank text]
; KoNoGe-MuNo KaNSoUWo[Line break]
; KiKaSeTeNe. MatuTeRuWa.[Exit after button press]

texta850:
.db $0a $0a $06 $27 $00 $0b $07 $1a $00 $46 $08 $19 TextNewLine
.db $15 $2c $42 $28 $3d $06 $27 $00 $14 $05 $0e $15 $02 $26 $4d $3d $4c TextButtonEnd
; KoKoKaRa SaKiHa BoKuNo[Line break]
; NaWaBaRiDaKaRa ToOSeNaIYo-Da.[Exit after button press]

texta86f:
.db $29 $45 $19 $1a $06 $0e $33 $00 $02 $03 $19 $3d $2f $10 $27 TextNewLine
.db $0c $32 $03 $33 $15 $02 $4c $00 $14 $05 $2f $13 $23 $02 $02 $26 $4c TextButtonEnd
; RuBeNoHaKaSeGa IUNoDatuTaRa[Line break]
; SiyoUGaNaI. ToOtuTeMoIIYo.[Exit after button press]

texta891:
.db $23 $10 $43 $01 $0e $02 $16 $1a $00 $23 $10 $43 $01 $2e TextNewLine
.db $40 $3c $28 $0d $0e $02 $16 $1a $00 $40 $3c $28 $01 $2e $00 $14 $02 $03 TextButton
.db $0e $02 $39 $2e $33 $00 $0d $2e $40 $02 $29 $0f $03 $3d $26 $4c TextNewLine
.db $02 $11 $41 $00 $01 $2f $13 $00 $1a $15 $0c $13 $20 $10 $02 $15 $4c TextButtonEnd
; MoTaBiASeINiHa MoTaBiAN[Line break]
; DeZoRiSuSeINiHa DeZoRiAN ToIU[Wait for button press and blank text]
; SeIZiNGa SuNDeIRuSoUDaYo.[Line break]
; ITiDo AtuTe HaNaSiTeMiTaINa.[Exit after button press]

texta8d6:
.db $06 $0c $0a $02 $00 $23 $2e $0d $10 $4d $16 $1a TextNewLine
.db $23 $2e $0d $10 $4d $0a $14 $42 $33 $00 $01 $29 $0f $03 $3d $4c TextButtonEnd
; KaSiKoI MoNSuTa-NiHa[Line break]
; MoNSuTa-KoToBaGa ARuSoUDa.[Exit after button press]

texta8f4:
.db $27 $0a $16 $01 $2e $4b $2f $14 $1a $00 $14 $13 $23 $00 $10 $06 $08 TextNewLine
.db $03 $2a $10 $26 $4c $00 $01 $28 $33 $14 $0b $2e $4c TextButtonEnd
; RaKoNiANPotuToHa ToTeMo TaKaKu[Line break]
; UReTaYo. ARiGaToSaN.[Exit after button press]

texta914:
.db $26 $0c $00 $0a $2a $40 $00 $0d $10 $2f $1c $1a TextNewLine
.db $0f $2b $2f $10 $26 $03 $3d $4c $00 $0f $0a $40 TextButton
texta92e:
.db $0e $02 $0b $08 $1b $33 $00 TextNumber $22 $0e $10 TextNewLine
.db $06 $06 $29 $2e $39 $30 $33 $00 $2c $0c $16 $00 $08 $2a $2e $06 $4c TextEnd
; YoSi KoReDe SuTatuHuHa[Line break]
; SoRotuTaYoUDa. SoKoDe[Wait for button press and blank text]
; SeISaKuHiGa [number]MeSeTa[Line break]
; KaKaRuNZiyaGa WaSiNi KuReNKa.[Exit immediately]

texta94c:
.db $01 $28 $33 $14 $03 $4c $40 $1a $00 $0e $02 $0b $08 $2d TextNewLine
.db $1a $39 $22 $26 $03 $4c $0d $0a $0c $1f $2f $13 $08 $2a $4c TextButtonEnd
; ARiGaToU.DeHa SeISaKuWo[Line break]
; HaZiMeYoU.SuKoSiMatuTeKuRe.[Exit after button press]

texta96b:
.db $01 $2c $13 $13 $23 $00 $02 $02 $23 $19 $1a $00 $40 $07 $2e $3c $26 $4c $23 $03 $00 $0d $0a $0c $19 $0c $2e $46 $03 $39 $30 $4c TextButtonEnd
; AWaTeTeMo IIMoNoHa DeKiNZoYo.MoU SuKoSiNoSiNBoUZiya.[Exit after button press]

texta98c:
.db $26 $0c $4c $0a $2a $40 $00 $29 $45 $19 $37 $03 $16 $00 $19 $2f $13 TextNewLine
.db $03 $11 $31 $03 $1d $00 $14 $43 $3d $0e $29 $4c TextButton
.db $21 $27 $19 $00 $0f $14 $1d $00 $40 $13 $20 $29 $33 $02 $02 $4c TextNewLine
.db $15 $06 $15 $06 $19 $00 $40 $07 $3d $26 $4c TextButtonEnd
; YoSi.KoReDe RuBeNoGoUNi NotuTe[Line break]
; UTiyuUHe ToBiDaSeRu.[Wait for button press and blank text]
; MuRaNo SoToHe DeTeMiRuGaII.[Line break]
; NaKaNaKaNo DeKiDaYo.[Exit after button press]

texta9c8:
.db $05 $02 $00 $0f $0a $19 $00 $18 $0a $4c TextNewLine
.db $0a $2f $11 $1d $00 $0a $02 $4c TextEnd
; OI SoKoNo NeKo.[Line break]
; KotuTiHe KoI.[Exit immediately]

texta9dc:
.db $09 $2f $09 $2f $09 $4c $05 $1f $04 $27 $23 $00 $0c $16 $10 $02 $06 $4c TextButtonEnd
; KetuKetuKe.OMaERaMo SiNiTaIKa.[Exit after button press]

texta9ef:
.db $2c $0c $19 $00 $39 $30 $1f $2d $00 $0d $29 $24 $12 $1a TextNewLine
.db $0a $2b $0c $13 $24 $29 $4c TextButtonEnd
; WaSiNo ZiyaMaWo SuRuYaTuHa[Line break]
; KoRoSiTeYaRu.[Exit after button press]

textaa06:
.db $15 $33 $02 $10 $43 $40 $00 $12 $06 $2a $10 $3d $2b $03 $4c TextNewLine
.db $0a $0a $40 $00 $25 $2f $08 $28 $00 $24 $0d $21 $33 $02 $02 $4c TextButtonEnd
; NaGaITaBiDe TuKaReTaDaRoU.[Line break]
; KoKoDe YutuKuRi YaSuMuGaII.[Exit after button press]

textaa27:
.db $23 $03 $00 $02 $2f $0a $08 $19 $00 $25 $03 $26 $23 TextNewLine
.db $25 $29 $0b $2a $15 $02 $4c TextButton
.db $0a $0a $2b $0c $13 $00 $06 $06 $29 $33 $26 $02 $4c TextNewLine
.db $44 $39 $2d $00 $02 $19 $2f $13 $02 $29 $4c TextButtonEnd
; MoU ItuKoKuNo YuUYoMo[Line break]
; YuRuSaReNaI.[Wait for button press and blank text]
; KoKoRoSiTe KaKaRuGaYoI.[Line break]
; BuZiWo INotuTeIRu.[Exit after button press]

textaa57:
.db $1c $06 $02 $00 $18 $21 $28 $16 $00 $12 $02 $10 $4c TextPauseEnd
; HuKaI NeMuRiNi TuITa.[Exit after pause]

textaa65:
.db $05 $0f $2b $0c $02 $00 $25 $22 $3d $2f $10 $4c TextButtonEnd
; OSoRoSiI YuMeDatuTa.[Exit after button press]

;textaa72:
textAlisasHouse:
.db $0a $0a $1a $00 $01 $28 $0b $19 $00 $03 $11 $40 $0d $4c TextNewLine
.db $3d $2a $23 $00 $02 $1f $0e $2e $4c TextButtonEnd
; KoKoHa ARiSaNo UTiDeSu.[Line break]
; DaReMo IMaSeN.[Exit after button press]
; This is Alisa’s house. Nobody is here.

textaa8b:
.db $05 $24 $4c $26 $03 $0d $33 $00 $1d $2e $3d $4c TextButton
.db $0f $03 $14 $08 $1a $00 $41 $0a $1d $00 $02 $2f $10 $2e $3d $2b $03 $4c TextButtonEnd
; OYa.YoUSuGa HeNDa.[Wait for button press and blank text]
; SoUToKuHa DoKoHe ItuTaNDaRoU.[Exit after button press]

textaaab:
.db $05 $24 $4c $0c $2e $40 $05 $29 $19 $06 $4c $15 $0b $09 $15 $02 $4c TextNewLine
.db $02 $07 $06 $04 $2f $13 $00 $40 $15 $05 $0d $33 $02 $02 $4c TextButtonEnd
; OYa.SiNDeORuNoKa.NaSaKeNaI.[Line break]
; IKiKaEtuTe DeNaOSuGaII.[Exit after button press]

textaacd:
.db $27 $0c $4d $08 $1a $00 $10 $05 $2a $10 $4c TextButton
.db $01 $28 $0b $19 $00 $18 $33 $02 $1a $00 $06 $15 $04 $27 $2a $10 $4c TextButton
.db $13 $2e $37 $08 $19 $00 $18 $2b $23 $00 $07 $2f $14 TextNewLine
.db $26 $2b $0a $2e $40 $02 $29 $0a $14 $3d $2b $03 $4c TextButton
.db $0b $01 $00 $47 $0e $05 $19 $00 $0f $03 $14 $08 $19 $00 $23 $14 $1d TextNewLine
.db $02 $0f $37 $03 $4c TextButtonEnd
; RaSi-KuHa TaOReTa.[Wait for button press and blank text]
; ARiSaNo NeGaIHa KaNaERaReTa.[Wait for button press and blank text]
; TeNGoKuNo NeRoMo KituTo[Line break]
; YoRoKoNDeIRuKoToDaRoU.[Wait for button press and blank text]
; SaA PaSeONo SoUToKuNo MoToHe[Line break]
; ISoGoU.[Exit after button press]

textab1f:
.db TextEnemyName $1a $00 TextCharacterName $19 TextNewLine
.db $0a $03 $36 $07 $2d $00 $06 $2c $0c $10 $4c TextPauseEnd
; [enemy name]Ha [character name]No[Line break]
; KoUGeKiWo KaWaSiTa.[Exit after pause]

textab31:
.db TextCharacterName $1a $00 TextEnemyName $19 TextNewLine
.db $0a $03 $36 $07 $2d $00 $06 $2c $0c $10 $4c TextPauseEnd
; [character name]Ha [enemy name]No[Line break]
; KoUGeKiWo KaWaSiTa.[Exit after pause]

textab43:
.db TextCharacterName $1a $00 $1a $15 $0c $06 $09 $10 $4c TextEnd
; [character name]Ha HaNaSiKaKeTa.[Exit immediately]

textab4e:
.db TextEnemyName $1a $00 $0a $10 $04 $10 $4c TextPauseEnd
; [enemy name]Ha KoTaETa.[Exit after pause]

textab57:
.db $12 $03 $39 $15 $06 $2f $10 $4c TextPauseEnd
; TuUZiNaKatuTa.[Exit after pause]

textab60:
.db TextEnemyName $1a $00 $16 $36 $20 $11 $16 TextNewLine
.db $10 $11 $1c $0b $33 $2f $10 $4c TextPauseEnd
; [enemy name]Ha NiGeMiTiNi[Line break]
; TaTiHuSaGatuTa.[Exit after pause]

textab72:
.db TextCharacterName $19 $00 $1f $39 $2f $08 $1a TextNewLine
.db $0a $03 $06 $33 $00 $15 $06 $2f $10 $4c TextPauseEnd
; [character name]No MaZituKuHa[Line break]
; KoUKaGa NaKatuTa.[Exit after pause]

textab86:
.db TextEnemyName $19 $00 $1f $39 $2f $08 $1a TextNewLine
.db $0a $03 $06 $33 $00 $15 $06 $2f $10 $4c TextPauseEnd
; [enemy name]No MaZituKuHa[Line break]
; KoUKaGa NaKatuTa.[Exit after pause]

textab9a:
.db $22 $19 $1f $04 $16 $00 $20 $04 $15 $02 $00 $1f $1e $03 $19 TextNewLine
.db $06 $45 $33 $00 $40 $07 $10 $4c TextPauseEnd
; MeNoMaENi MiENaI MaHoUNo[Line break]
; KaBeGa DeKiTa.[Exit after pause]

textabb3:
.db TextEnemyName $19 $00 $0a $03 $36 $07 $1a TextNewLine
.db $1f $1e $03 $19 $00 $06 $45 $16 $00 $1a $18 $06 $04 $0b $2a $10 $4c TextPauseEnd
; [enemy name]No KoUGeKiHa[Line break]
; MaHoUNo KaBeNi HaNeKaESaReTa.[Exit after pause]

textabce:
.db TextEnemyName $19 $00 $1f $39 $2f $08 $1a TextNewLine
.db $1f $1e $03 $19 $00 $06 $45 $16 $00 $1a $18 $06 $04 $0b $2a $10 $4c TextPauseEnd
; [enemy name]No MaZituKuHa[Line break]
; MaHoUNo KaBeNi HaNeKaESaReTa.[Exit after pause]

textabe9:
.db $20 $04 $15 $02 $00 $06 $45 $19 $00 $0a $03 $06 $33 TextNewLine
.db $15 $08 $15 $2f $10 $4c TextPauseEnd
; MiENaI KaBeNo KoUKaGa[Line break]
; NaKuNatuTa.[Exit after pause]

textabfe:
.db TextCharacterName $19 $00 $10 $02 $28 $32 $08 $33 TextNewLine
.db $06 $02 $1c $08 $0c $10 $4c TextPauseEnd
; [character name]No TaIRiyoKuGa[Line break]
; KaIHuKuSiTa.[Exit after pause]

textac10:
.db TextEnemyName $19 $00 $10 $02 $28 $32 $08 $33 TextNewLine
.db $06 $02 $1c $08 $0c $10 $4c TextPauseEnd
; [enemy name]No TaIRiyoKuGa[Line break]
; KaIHuKuSiTa.[Exit after pause]

textac22:
.db TextEnemyName $2d TextNewLine
.db $06 $15 $0c $42 $28 $16 $0c $10 $4c TextPauseEnd
; [enemy name]Wo[Line break]
; KaNaSiBaRiNiSiTa.[Exit after pause]

textac2f:
.db TextCharacterName $1a $00 $06 $15 $0c $42 $28 $16 $00 $01 $2f $10 $4c TextPauseEnd
; [character name]Ha KaNaSiBaRiNi AtuTa.[Exit after pause]

textac3e:
.db TextCharacterName $1a $00 $03 $37 $09 $15 $02 $4c TextPauseEnd
; [character name]Ha UGoKeNaI.[Exit after pause]

textac48:
.db TextEnemyName $1a $00 $03 $37 $09 $15 $02 $4c TextPauseEnd
; [enemy name]Ha UGoKeNaI.[Exit after pause]

textac52:
.db TextCharacterName $1a $00 $06 $15 $0c $42 $28 $33 $00 $14 $09 $10 $4c TextPauseEnd
; [character name]Ha KaNaSiBaRiGa ToKeTa.[Exit after pause]

textac61:
.db TextEnemyName $1a TextNewLine
.db $06 $15 $0c $42 $28 $33 $00 $14 $09 $10 $4c TextPauseEnd
; [enemy name]Ha[Line break]
; KaNaSiBaRiGa ToKeTa.[Exit after pause]

textac70:
.db TextCharacterName $1a $00 $06 $27 $3d $16 $00 $11 $06 $27 $33 TextNewLine
.db $20 $15 $34 $29 $19 $2d $00 $06 $2e $39 $10 $4c TextPauseEnd
; [character name]Ha KaRaDaNi TiKaRaGa[Line break]
; MiNaGiRuNoWo KaNZiTa.[Exit after pause]

textac8a:
.db TextEnemyName $1a $00 $0a $2c $08 $15 $2f $13 TextNewLine
.db $0c $28 $37 $20 $0c $10 $4c TextPauseEnd
; [enemy name]Ha KoWaKuNatuTe[Line break]
; SiRiGoMiSiTa.[Exit after pause]

textac9c:
.db TextEnemyName $1a $00 $16 $36 $01 $0c $19 TextNewLine
.db $1a $24 $0b $16 $00 $05 $41 $2b $02 $10 $4c TextPauseEnd
; [enemy name]Ha NiGeASiNo[Line break]
; HaYaSaNi ODoRoITa.[Exit after pause]

textacb1:
.db $2c $15 $39 $30 $15 $06 $2f $10 $4c TextButtonEnd
; WaNaZiyaNaKatuTa.[Exit after button press]

textacbb:
.db $01 $44 $15 $02 $00 $14 $0a $2b $3d $2f $10 $4c TextCharacterName $1a TextNewLine
.db $2c $15 $2d $00 $20 $24 $44 $2f $13 $00 $1a $3a $0c $10 $4c TextButtonEnd
; ABuNaI ToKoRoDatuTa.[character name]Ha[Line break]
; WaNaWo MiYaButuTe HaZuSiTa.[Exit after button press]

textacda:
.db TextCharacterName $1a $00 TextItem $2d TextNewLine
.db $12 $06 $2f $10 $4c TextPauseEnd
; [character name]Ha [item]Wo[Line break]
; TuKatuTa.[Exit after pause]

textace6:
.db TextCharacterName $1a $00 TextItem $2d TextNewLine
.db $0f $03 $43 $0c $10 $4c TextEnd
; [character name]Ha [item]Wo[Line break]
; SoUBiSiTa.[Exit immediately]

textacf3:
.db TextCharacterName $1a $00 TextItem $2d TextNewLine
.db $0d $13 $13 $0c $1f $2f $10 $4c TextButtonEnd
; [character name]Ha [item]Wo[Line break]
; SuTeTeSiMatuTa.[Exit after button press]

textad02:
.db $0c $06 $0c $00 $0a $03 $06 $1a $00 $15 $06 $2f $10 $4c TextPauseEnd
; SiKaSi KoUKaHa NaKatuTa.[Exit after pause]

textad11:
.db $0c $06 $0c $00 $0a $0a $40 $00 TextItem $1a TextNewLine
.db $24 $08 $16 $00 $10 $10 $15 $02 $4c TextButtonEnd
; SiKaSi KoKoDe [item]Ha[Line break]
; YaKuNi TaTaNaI.[Exit after button press]

textad26:
.db $0a $0a $40 $00 $05 $28 $29 $2c $09 $16 $1a $00 $02 $06 $15 $02 $4c TextButtonEnd
; KoKoDe ORiRuWaKeNiHa IKaNaI.[Exit after button press]

textad38:
.db TextItem $16 $00 $19 $28 $0a $2e $3d $4c TextPauseEnd
; [item]Ni NoRiKoNDa.[Exit after pause]

textad42:
.db TextItem $06 $27 $00 $14 $43 $05 $28 $10 $4c TextPauseEnd
; [item]KaRa ToBiORiTa.[Exit after pause]

textad4d:
.db $0c $06 $0c $00 $15 $16 $23 $00 $05 $07 $15 $06 $2f $10 $4c TextPauseEnd
; SiKaSi NaNiMo OKiNaKatuTa.[Exit after pause]

textad5d:
.db TextEnemyName $1a $00 $1c $04 $19 $18 $2d TextNewLine
.db $07 $02 $13 $00 $05 $14 $15 $0c $08 $15 $2f $10 $4c TextPauseEnd
; [enemy name]Ha HuENoNeWo[Line break]
; KiITe OToNaSiKuNatuTa.[Exit after pause]

textad74:
.db TextEnemyName $1a $00 $22 $33 $00 $03 $12 $2b $3d $4c TextPauseEnd
; [enemy name]Ha MeGa UTuRoDa.[Exit after pause]

textad80:
.db $0c $06 $0c $00 $02 $1f $1a $00 $0f $2e $15 $0a $14 $2d TextNewLine
.db $0c $13 $02 $29 $42 $01 $02 $39 $30 $00 $15 $02 $26 $03 $3d $4c TextPauseEnd
; SiKaSi IMaHa SoNNaKoToWo[Line break]
; SiTeIRuBaAIZiya NaIYoUDa.[Exit after pause]

textada0:
.db TextCharacterName $1a $00 TextItem $2d TextNewLine
.db $14 $28 $3d $0c $10 $4c TextPauseEnd
; [character name]Ha [item]Wo[Line break]
; ToRiDaSiTa.[Exit after pause]

textadad:
.db $45 $12 $16 $00 $0a $2c $2a $13 $15 $02 $26 $03 $3d $4c TextButtonEnd
; BeTuNi KoWaReTeNaIYoUDa.[Exit after button press]

textadbc:
.db $1f $2f $08 $27 $40 $00 $0d $0d $21 $0a $14 $33 $00 $40 $07 $15 $02 $4c TextButtonEnd
; MatuKuRaDe SuSuMuKoToGa DeKiNaI.[Exit after button press]

textadcf:
.db $0f $0c $13 $00 $43 $2e $19 $00 $1c $10 $2d $00 $01 $09 $13 TextNewLine
.db $0c $3a $06 $16 $00 $10 $27 $0c $10 $4c TextPauseEnd
; SoSiTe BiNNo HuTaWo AKeTe[Line break]
; SiZuKaNi TaRaSiTa.[Exit after pause]

textadea:
.db $0c $06 $0c $00 $20 $30 $03 $1a $00 $43 $2e $19 $00 $1c $10 $2d TextNewLine
.db $01 $09 $29 $0a $14 $33 $00 $40 $07 $15 $06 $2f $10 $4c TextButtonEnd
; SiKaSi MiyaUHa BiNNo HuTaWo[Line break]
; AKeRuKoToGa DeKiNaKatuTa.[Exit after button press]

textae0a:
.db $02 $12 $00 $06 $02 $40 $20 $13 $23 $00 $02 $24 $15 TextNewLine
.db $16 $05 $02 $33 $00 $0d $29 $4c TextButtonEnd
; ITu KaIDeMiTeMo IYaNa[Line break]
; NiOIGa SuRu.[Exit after button press]

textae21:
.db TextCharacterName $1a $00 $14 $13 $23 TextNewLine
.db $02 $24 $15 $00 $26 $06 $2e $33 $0c $10 $4c TextButtonEnd
; [character name]Ha ToTeMo[Line break]
; IYaNa YoKaNGaSiTa.[Exit after button press]

textae34:
.db TextCharacterName $1a $00 $15 $16 $23 $00 $06 $2e $39 $15 $06 $2f $10 $4c TextButtonEnd
; [character name]Ha NaNiMo KaNZiNaKatuTa.[Exit after button press]

textae44:
.db TextEnemyName $1a $00 $01 $06 $02 $00 $1e $15 $05 $2d TextNewLine
.db $20 $13 $00 $05 $39 $09 $3a $02 $10 $4c TextPauseEnd
; [enemy name]Ha AKaI HoNaOWo[Line break]
; MiTe OZiKeZuITa.[Exit after pause]

textae5b:
.db TextCharacterName $1a $00 TextItem $2d TextNewLine
.db $13 $2e $16 $00 $06 $38 $0c $10 $4c TextPauseEnd
; [character name]Ha [item]Wo[Line break]
; TeNNi KaZaSiTa.[Exit after pause]

textae6b:
.db TextCharacterName $1a $00 $27 $04 $29 $1f $45 $28 $4d $2d $00 $14 $2f $13 TextNewLine
.db $27 $0a $16 $01 $2e $4b $2f $14 $16 $00 $02 $2a $10 $4c TextButtonEnd
; [character name]Ha RaERuMaBeRi-Wo TotuTe[Line break]
; RaKoNiANPotuToNi IReTa.[Exit after button press]

textae8a:
.db $27 $04 $29 $1f $45 $28 $4d $2d $00 $14 $2f $13 $20 $10 $33 TextNewLine
.db $0c $42 $27 $08 $0d $29 $14 $00 $1b $06 $27 $43 $13 $0c $1f $2f $10 $4c TextButtonEnd
; RaERuMaBeRi-Wo TotuTeMiTaGa[Line break]
; SiBaRaKuSuRuTo HiKaRaBiTeSiMatuTa.[Exit after button press]

textaead:
.db $1f $46 $2b $0c $19 $00 $04 $01 $2b $07 $30 $2f $0d $29 $33 TextNewLine
.db $05 $05 $3c $27 $16 $00 $0d $33 $10 $2d $00 $01 $27 $2c $0c $10 $4c TextButtonEnd
; MaBoRoSiNo EARoKiyatuSuRuGa[Line break]
; OOZoRaNi SuGaTaWo ARaWaSiTa.[Exit after button press]

textaecf:
.db $05 $15 $06 $33 $00 $0d $02 $13 $15 $06 $2f $10 $19 $40 TextNewLine
.db $23 $14 $16 $00 $23 $41 $0c $10 $4c TextButtonEnd
; ONaKaGa SuITeNaKatuTaNoDe[Line break]
; MoToNi MoDoSiTa.[Exit after button press]

textaee8:
.db $1a $49 $0d $43 $4d $1a $00 $02 $24 $02 $24 $2d $0c $10 $4c TextButtonEnd
; HaPuSuBi-Ha IYaIYaWoSiTa.[Exit after button press]

textaef8:
.db $1a $49 $0d $43 $4d $19 $00 $01 $10 $1f $1a $00 $06 $10 $02 $4c TextButtonEnd
; HaPuSuBi-No ATaMaHa KaTaI.[Exit after button press]

textaf09:
.db $0f $2a $1a $00 $12 $06 $2c $15 $08 $13 $23 TextNewLine
.db $07 $07 $22 $33 $00 $01 $29 $4c TextButtonEnd
; SoReHa TuKaWaNaKuTeMo[Line break]
; KiKiMeGa ARu.[Exit after button press]

textaf1e:
.db $14 $08 $16 $00 $06 $2c $2f $10 $14 $0a $2b $1a TextNewLine
.db $15 $02 $26 $03 $3d $4c TextButtonEnd
; ToKuNi KaWatuTaToKoRoHa[Line break]
; NaIYoUDa.[Exit after button press]

textaf32:
.db TextItem $2d $00 $20 $12 $09 $10 $4c TextButtonEnd
; [item]Wo MiTuKeTa.[Exit after button press]

textaf3b:
.db $15 $2e $3d $06 $00 $06 $27 $3d $33 $00 $06 $29 $08 $15 $2f $10 $4c TextPauseEnd
; NaNDaKa KaRaDaGa KaRuKuNatuTa.[Exit after pause]

textaf4d:
.db TextCharacterName $19 $00 $10 $1f $0c $02 $1a TextNewLine
.db $26 $20 $33 $04 $2f $10 $4c TextButtonEnd
; [character name]No TaMaSiIHa[Line break]
; YoMiGaEtuTa.[Exit after button press]

textaf5e:
.db $10 $02 $2b $2e $1a $00 $1f $39 $2f $08 $2d $00 $12 $06 $04 $15 $02 $4c TextPauseEnd
; TaIRoNHa MaZituKuWo TuKaENaI.[Exit after pause]

textaf71:
.db TextCharacterName $1a $00 $1f $3d $00 $1f $39 $2f $08 $2d TextNewLine
.db $05 $46 $04 $13 $02 $15 $02 $4c TextPauseEnd
; [character name]Ha MaDa MaZituKuWo[Line break]
; OBoETeINaI.[Exit after pause]

textaf86:
.db TextCharacterName $1a $00 TextItem $2d TextNewLine
.db $0f $03 $43 $00 $40 $07 $15 $02 $4c TextButtonEnd
; [character name]Ha [item]Wo[Line break]
; SoUBi DeKiNaI.[Exit after button press]

textaf96:
.db $0f $2a $1a $00 $0f $03 $43 $0c $15 $08 $13 $23 $02 $02 $4c TextButtonEnd
; SoReHa SoUBiSiNaKuTeMoII.[Exit after button press]

textafa6:
.db $09 $02 $09 $2e $11 $33 $00 TextNumber $4b $02 $2e $14 TextNewLine
.db $01 $33 $2f $10 $4c TextButtonEnd
; KeIKeNTiGa [number]PoINTo[Line break]
; AGatuTa.[Exit after button press]

textafb9:
.db TextCharacterName $1a $00 $2a $45 $29 $01 $2f $49 $0c $10 $4c TextButtonEnd
; [character name]Ha ReBeRuAtuPuSiTa.[Exit after button press]

textafc6:
.db TextCharacterName $1a $00 $1f $39 $2f $08 $2d TextNewLine
.db $1b $14 $12 $00 $20 $16 $12 $09 $10 $4c TextButtonEnd
; [character name]Ha MaZituKuWo[Line break]
; HiToTu MiNiTuKeTa.[Exit after button press]

textafda:
.db TextNumber $22 $0e $10 $00 $1a $02 $2f $13 $02 $10 $4c TextButtonEnd
; [number]MeSeTa HaItuTeITa.[Exit after button press]

textafe7:
.db $01 $09 $13 $20 $29 $06 $4c TextEnd
; AKeTeMiRuKa.[Exit immediately]

textafef:
.db $06 $27 $2f $4b $3d $2f $10 $4c TextButtonEnd
; KaRatuPoDatuTa.[Exit after button press]

textaff8:
.db $0a $2a $02 $39 $32 $03 $00 $23 $19 $2d $00 $23 $13 $15 $02 TextNewLine
.db $15 $16 $06 $2d $00 $0d $13 $29 $06 $4c TextEnd
; KoReIZiyoU MoNoWo MoTeNaI[Line break]
; NaNiKaWo SuTeRuKa.[Exit immediately]

textb013:
.db $41 $2a $2d $00 $0d $13 $29 $06 $4c TextEnd
; DoReWo SuTeRuKa.[Exit immediately]

textb01d:
.db TextItem $2d $00 $0d $13 $13 TextButtonEnd
; [item]Wo SuTeTe[Exit after button press]

textb024:
.db TextItem $2d $00 $13 $16 $02 $2a $10 $4c TextButtonEnd
; [item]Wo TeNiIReTa.[Exit after button press]

textb02e:
.db TextItem $1a $00 $02 $27 $15 $02 $19 $06 $4c TextEnd
; [item]Ha IRaNaINoKa.[Exit immediately]

textb039:
.db TextItem $2d $00 $01 $07 $27 $22 $10 $4c TextButtonEnd
; [item]Wo AKiRaMeTa.[Exit after button press]

textb043:
.db TextItem $2d TextNewLine
.db $0d $13 $29 $2c $09 $16 $1a $00 $02 $06 $15 $02 $4c TextButtonEnd
; [item]Wo[Line break]
; SuTeRuWaKeNiHa IKaNaI.[Exit after button press]

textb054:
.db $1f $39 $2f $08 $4b $02 $2e $14 $33 $00 $10 $28 $15 $02 $4c TextPauseEnd
; MaZituKuPoINToGa TaRiNaI.[Exit after pause]

textb064:
.db TextCharacterName $1a $00 $1f $3d $00 $02 $07 $13 $02 $29 $4c TextPauseEnd
; [character name]Ha MaDa IKiTeIRu.[Exit after pause]

textb071:
.db TextEnemyName $2d $00 $24 $2f $12 $09 $10 $4c TextButtonEnd
; [enemy name]Wo YatuTuKeTa.[Exit after button press]

textb07b:
.db TextCharacterName $1a $00 $0c $2e $40 $0c $1f $2f $10 $4c TextPauseEnd
; [character name]Ha SiNDeSiMatuTa.[Exit after pause]

textb087:
.db TextCharacterName $1a $00 $23 $03 $00 $0c $2e $40 $02 $29 $4c TextPauseEnd
; [character name]Ha MoU SiNDeIRu.[Exit after pause]

textb094:
.db $20 $30 $03 $1a $00 $27 $04 $29 $1f $45 $28 $4d $2d TextNewLine
.db $06 $39 $2f $10 $4c TextButtonEnd
; MiyaUHa RaERuMaBeRi-Wo[Line break]
; KaZituTa.[Exit after button press]

textb0a8:
.db $41 $0a $1d $00 $02 $07 $1f $0d $06 $4c TextEnd
; DoKoHe IKiMaSuKa.[Exit immediately]

textb0b3:
.db $40 $3c $28 $0d $0e $02 $19 $00 $0d $08 $2a $19 $1f $11 $1d TextNewLine
.db $02 $07 $1f $0d $4c $02 $02 $40 $0d $06 $4c TextEnd
; DeZoRiSuSeINo SuKuReNoMaTiHe[Line break]
; IKiMaSu.IIDeSuKa.[Exit immediately]

textb0cf:
.db $23 $10 $43 $01 $0e $02 $19 $00 $03 $4d $3c $19 $21 $27 $1d TextNewLine
.db $02 $07 $1f $0d $4c $02 $02 $40 $0d $06 $4c TextEnd
; MoTaBiASeINo U-ZoNoMuRaHe[Line break]
; IKiMaSu.IIDeSuKa.[Exit immediately]

textb0eb:
.db $47 $29 $1f $0e $02 $19 $00 $33 $0c $0a $19 $21 $27 $1d TextNewLine
.db $02 $07 $1f $0d $4c $02 $02 $40 $0d $06 $4c TextEnd
; PaRuMaSeINo GaSiKoNoMuRaHe[Line break]
; IKiMaSu.IIDeSuKa.[Exit immediately]

textb106:
.db $0a $0a $1a $00 $0d $08 $2a $00 $40 $0d $4c TextEnd
; KoKoHa SuKuRe DeSu.[Exit immediately]

textb112:
.db $0a $0a $1a $00 $03 $4d $3c $00 $40 $0d $4c TextEnd
; KoKoHa U-Zo DeSu.[Exit immediately]

textb11e:
.db $0a $0a $1a $00 $33 $0c $0a $00 $40 $0d $4c TextEnd
; KoKoHa GaSiKo DeSu.[Exit immediately]

textb12a:
.db $0c $31 $2f $47 $4d $12 $4c TextPauseEnd
; SiyutuPa-Tu.[Exit after pause]

textb132:
.db $23 $28 $19 $15 $06 $40 $00 $20 $11 $16 $00 $1f $26 $2f $13 TextNewLine
.db $0c $1f $2f $10 $4c TextButtonEnd
; MoRiNoNaKaDe MiTiNi MaYotuTe[Line break]
; SiMatuTa.[Exit after button press]

textb148:
.db $0a $0a $1a $00 $01 $4d $1f $4d $0c $32 $2f $49 $40 $0d $4c TextNewLine
.db $15 $16 $06 $00 $06 $02 $1f $0d $06 $4c TextEnd
; KoKoHa A-Ma-SiyotuPuDeSu.[Line break]
; NaNiKa KaIMaSuKa.[Exit immediately]

textb163:
.db $0f $03 $40 $0d $06 $4c $1f $10 $07 $13 $08 $3d $0b $02 $4c TextButtonEnd
; SoUDeSuKa.MaTaKiTeKuDaSaI.[Exit after button press]

textb173:
.db $41 $2a $2d $00 $06 $02 $1f $0d $06 $4c TextEnd
; DoReWo KaIMaSuKa.[Exit immediately]

textb17e:
.db $01 $28 $33 $14 $03 $4c $23 $2f $14 $00 $06 $02 $1f $0d $06 $4c TextEnd
; ARiGaToU.MotuTo KaIMaSuKa.[Exit immediately]

textb18f:
.db $0f $2a $02 $39 $32 $03 $00 $23 $13 $15 $02 $26 $03 $40 $0d $18 $4c TextNewLine
.db $1f $10 $07 $13 $08 $3d $0b $02 $4c TextButtonEnd
; SoReIZiyoU MoTeNaIYoUDeSuNe.[Line break]
; MaTaKiTeKuDaSaI.[Exit after button press]

textb1ab:
.db $0a $0a $1a $00 $41 $27 $2f $35 $0d $14 $01 $40 $0d $4c TextNewLine
.db $15 $16 $06 $00 $06 $02 $1f $0d $06 $4c TextEnd
; KoKoHa DoRatuGuSuToADeSu.[Line break]
; NaNiKa KaIMaSuKa.[Exit immediately]

textb1c5:
.db $0a $0a $1a $00 $12 $4d $29 $0c $32 $2f $49 $40 $0d $4c TextNewLine
.db $41 $2e $15 $00 $37 $26 $03 $40 $0d $06 $4c TextEnd
; KoKoHa Tu-RuSiyotuPuDeSu.[Line break]
; DoNNa GoYoUDeSuKa.[Exit immediately]

textb1e0:
.db $41 $2a $2d $00 $03 $28 $1f $0d $06 $4c TextEnd
; DoReWo URiMaSuKa.[Exit immediately]

textb1eb:
.db TextItem $40 $0d $18 $4c TextNewLine
.db TextNumber $22 $0e $10 $40 $00 $02 $02 $40 $0d $06 $4c TextEnd
; [item]DeSuNe.[Line break]
; [number]MeSeTaDe IIDeSuKa.[Exit immediately]

textb1fe:
.db $01 $28 $33 $14 $03 $00 $23 $2f $14 $03 $28 $1f $0d $06 $4c TextEnd
; ARiGaToU MotuToURiMaSuKa.[Exit immediately]

textb20e:
.db $0a $0a $1a $00 $1e $0d $48 $10 $29 $40 $0d $4c TextNewLine
.db $11 $28 $32 $03 $2d $00 $03 $09 $1f $0d $06 $4c TextEnd
; KoKoHa HoSuPiTaRuDeSu.[Line break]
; TiRiyoUWo UKeMaSuKa.[Exit immediately]

textb228:
.db $0c $2e $0b $12 $14 $00 $11 $28 $32 $03 $1b TextNewLine
.db TextNumber $22 $0e $10 $40 $0d $4c $26 $2b $0c $02 $40 $0d $06 $4c TextEnd
; SiNSaTuTo TiRiyoUHi[Line break]
; [number]MeSeTaDeSu.YoRoSiIDeSuKa.[Exit immediately]

textb244:
.db $1e $06 $16 $00 $11 $28 $32 $03 $2d $00 $03 $09 $10 $02 $06 $10 $1a TextNewLine
.db $02 $1f $0d $06 $4c TextEnd
; HoKaNi TiRiyoUWo UKeTaIKaTaHa[Line break]
; IMaSuKa.[Exit immediately]

textb25c:
.db $41 $15 $10 $33 $00 $11 $28 $32 $03 $2d $00 $03 $09 $1f $0d $06 $4c TextEnd
; DoNaTaGa TiRiyoUWo UKeMaSuKa.[Exit immediately]

textb26e:
.db $05 $1f $11 $41 $03 $0b $1f $4c TextNewLine
.db $41 $03 $3c $00 $05 $3d $02 $39 $16 $4c TextButtonEnd
; OMaTiDoUSaMa.[Line break]
; DoUZo ODaIZiNi.[Exit after button press]

textb282:
.db $0f $03 $40 $0d $06 $00 $05 $13 $12 $3d $02 $40 $07 $15 $08 $13 TextNewLine
.db $38 $2e $18 $2e $40 $0d $4c $40 $1a $00 $05 $07 $2d $12 $09 $13 $4c TextButtonEnd
; SoUDeSuKa OTeTuDaIDeKiNaKuTe[Line break]
; ZaNNeNDeSu.DeHa OKiWoTuKeTe.[Exit after button press]

textb2a5:
.db TextCharacterName $0b $2e $1a $00 $02 $39 $26 $03 TextNewLine
.db $01 $28 $1f $0e $2e $18 $4c TextButtonEnd
; [character name]SaNHa IZiYoU[Line break]
; ARiMaSeNNe.[Exit after button press]

textb2b7:
.db $0a $0a $1a $00 $07 $32 $03 $06 $02 $40 $0d $4c $00 $3d $2a $06 $19 TextNewLine
.db $10 $1f $0c $02 $2d $00 $26 $43 $23 $41 $0b $2a $1f $0d $06 $4c TextEnd
; KoKoHa KiyoUKaIDeSu. DaReKaNo[Line break]
; TaMaSiIWo YoBiMoDoSaReMaSuKa.[Exit immediately]

textb2da:
.db $40 $1a $00 $01 $15 $10 $19 $10 $22 $16 TextNewLine
.db $05 $02 $19 $28 $2d $00 $0b $0b $36 $1f $0d $4c TextButtonEnd
; DeHa ANaTaNoTaMeNi[Line break]
; OINoRiWo SaSaGeMaSu.[Exit after button press]

textb2f2:
.db $0f $2a $40 $1a $00 $39 $31 $23 $2e $2d $00 $14 $15 $04 $1f $0d $4c TextPauseEnd
; SoReDeHa ZiyuMoNWo ToNaEMaSu.[Exit after pause]

textb304:
.db $01 $29 $13 $21 $1a $21 $27 $21 $00 $01 $29 $13 $21 $1a $21 $1a $21 TextNewLine
.db $0d $14 $27 $14 $4b $2e $4c TextPauseEnd
; ARuTeMuHaMuRaMu ARuTeMuHaMuHaMu[Line break]
; SuToRaToPoN.[Exit after pause]

textb31e:
.db $41 $15 $10 $19 $00 $10 $1f $0c $02 $40 $0c $32 $03 $4c TextEnd
; DoNaTaNo TaMaSiIDeSiyoU.[Exit immediately]

textb32d:
.db $1e $06 $19 $06 $10 $1a $00 $02 $06 $33 $40 $0d $06 $4c TextEnd
; HoKaNoKaTaHa IKaGaDeSuKa.[Exit immediately]

textb33c:
.db TextNumber $22 $0e $10 $00 $06 $06 $28 $1f $0d $33 TextNewLine
.db $26 $2b $0c $02 $40 $0d $06 $4c TextEnd
; [number]MeSeTa KaKaRiMaSuGa[Line break]
; YoRoSiIDeSuKa.[Exit immediately]

textb351:
.db $0a $2a $06 $27 $00 $2a $45 $29 $01 $2f $49 $0d $29 $10 $22 $16 $1a TextButtonEnd
; KoReKaRa ReBeRuAtuPuSuRuTaMeNiHa[Exit after button press]

textb363:
.db TextCharacterName $1a $00 TextNumber $4b $02 $2e $14 TextNewLine
.db $1b $12 $26 $03 $40 $0d $4c TextButtonEnd
; [character name]Ha [number]PoINTo[Line break]
; HiTuYoUDeSu.[Exit after button press]

textb374:
.db $01 $15 $10 $33 $10 $19 $00 $25 $08 $0d $04 $16 TextNewLine
.db $06 $20 $19 $00 $22 $35 $20 $33 $00 $01 $28 $1f $0d $26 $03 $16 $4c TextButtonEnd
; ANaTaGaTaNo YuKuSuENi[Line break]
; KaMiNo MeGuMiGa ARiMaSuYoUNi.[Exit after button press]

textb393:
.db TextCharacterName $1a $00 $02 $07 $13 $02 $1f $0d $26 $4c TextEnd
; [character name]Ha IKiTeIMaSuYo.[Exit immediately]

textb39f:
.db $0e $4d $44 $2d $00 $05 $0a $15 $02 $1f $0d $4c TextNewLine
.db $42 $2e $37 $03 $2d $00 $04 $27 $2e $40 $08 $3d $0b $02 $4c TextEnd
; Se-BuWo OKoNaIMaSu.[Line break]
; BaNGoUWo ERaNDeKuDaSaI.[Exit immediately]

textb3bc:
TextConfirmSlotSelection:
.db TextNumber $42 $2e $40 $00 $02 $02 $40 $0d $06 $4c TextEnd
; [number]BaNDe IIDeSuKa.[Exit immediately]
; You chose x, OK?

textb3c8:
.db $40 $1a $00 TextNumber $42 $2e $16 $00 $0e $4d $44 $0c $1f $0d $4c TextPauseEnd
; DeHa [number]BaNNi Se-BuSiMaSu.[Exit after pause]

textb3d8:
.db $05 $2c $28 $1f $0c $10 $4c TextButtonEnd
; OWaRiMaSiTa.[Exit after button press]

textb3e0:
.db $2c $10 $0c $10 $11 $1a $00 $47 $29 $1f $19 $00 $1b $14 $10 $11 $14 TextNewLine
.db $15 $06 $26 $08 $00 $0c $10 $02 $4c TextButtonEnd
; WaTaSiTaTiHa PaRuMaNo HiToTaTiTo[Line break]
; NaKaYoKu SiTaI.[Exit after button press]

textb3fc:
.db $27 $04 $29 $1f $45 $28 $4d $33 $00 $10 $45 $10 $02 $15 $01 $4c TextButtonEnd
; RaERuMaBeRi-Ga TaBeTaINaA.[Exit after button press]

textb40d:
.db $27 $0c $4d $08 $0b $1f $16 $1a TextNewLine
.db $0b $06 $27 $2c $15 $02 $1e $03 $33 $00 $02 $02 $26 $4c TextButtonEnd
; RaSi-KuSaMaNiHa[Line break]
; SaKaRaWaNaIHoUGa IIYo.[Exit after button press]

textb425:
.db $05 $2f $4c $2c $10 $0c $10 $11 $19 $00 $0a $14 $42 $33 TextNewLine
.db $2c $06 $29 $2e $3d $18 $4c TextButtonEnd
; Otu.WaTaSiTaTiNo KoToBaGa[Line break]
; WaKaRuNDaNe.[Exit after button press]

textb43c:
.db $24 $2f $1e $4d $4c TextButtonEnd
; YatuHo-.[Exit after button press]

textb442:
.db $3d $2e $39 $32 $2e $40 $1a $00 $05 $14 $0c $01 $15 $16 TextNewLine
.db $07 $2d $12 $09 $15 $26 $4c TextButtonEnd
; DaNZiyoNDeHa OToSiANaNi[Line break]
; KiWoTuKeNaYo.[Exit after button press]

textb459:
.db $10 $06 $27 $42 $0a $1a $00 $21 $24 $20 $16 TextNewLine
.db $01 $09 $29 $14 $00 $09 $33 $2d $0d $29 $26 $4c TextButtonEnd
; TaKaRaBaKoHa MuYaMiNi[Line break]
; AKeRuTo KeGaWoSuRuYo.[Exit after button press]

textb472:
.db $0a $19 $00 $05 $02 $1a $34 $24 $2b $03 $4c TextButtonEnd
; KoNo OIHaGiYaRoU.[Exit after button press]

textb47e:
.db $2c $10 $0c $10 $11 $1a $00 $41 $03 $0e TextNewLine
.db $16 $08 $1f $2a $23 $19 $3d $26 $4c TextButtonEnd
; WaTaSiTaTiHa DoUSe[Line break]
; NiKuMaReMoNoDaYo.[Exit after button press]

textb493:
.db $0d $4d $3a $1c $29 $4d $14 $19 $00 $18 $02 $2b $1a TextNewLine
.db $02 $02 $15 $01 $4c TextButtonEnd
; Su-ZuHuRu-ToNo NeIRoHa[Line break]
; IINaA.[Exit after button press]

textb4a7:
.db $01 $02 $0d $40 $2f $06 $4d $00 $14 $02 $03 $00 $19 $28 $23 $19 $1a TextNewLine
.db $0a $05 $28 $23 $00 $09 $3a $2a $29 $2e $3d $2f $13 $4c TextButtonEnd
; AISuDetuKa- ToIU NoRiMoNoHa[Line break]
; KoORiMo KeZuReRuNDatuTe.[Exit after button press]

textb4c8:
.db $27 $0c $4d $08 $0b $1f $1a $00 $0f $27 $19 $03 $04 $16 TextNewLine
.db $02 $27 $2f $0c $30 $29 $2e $3d $4c TextButtonEnd
; RaSi-KuSaMaHa SoRaNoUENi[Line break]
; IRatuSiyaRuNDa.[Exit after button press]

textb4e1:
.db $01 $43 $05 $2e $19 $00 $1f $2f $41 $41 $08 $10 $4d $33 TextNewLine
.db $27 $0d $0a $16 $01 $2e $4b $2f $14 $2d $00 $23 $2f $13 $10 $3b $4c TextButtonEnd
; ABiONNo MatuDoDoKuTa-Ga[Line break]
; RaSuKoNiANPotuToWo MotuTeTaZe.[Exit after button press]

textb502:
.db $0f $27 $19 $00 $03 $04 $16 $1a $00 $03 $11 $31 $03 $0e $2e $40 $23 TextNewLine
.db $02 $09 $15 $02 $14 $0a $2b $33 $01 $29 $3b $4c TextButtonEnd
; SoRaNo UENiHa UTiyuUSeNDeMo[Line break]
; IKeNaIToKoRoGaARuZe.[Exit after button press]

textb521:
.db $27 $04 $29 $1f $45 $28 $4d $2d $00 $20 $19 $27 $0e $29 $10 $22 $16 $1a $01 $29 $23 $19 $33 $00 $1b $12 $26 $03 $3d $4c TextButtonEnd
; RaERuMaBeRi-Wo MiNoRaSeRuTaMeNiHaARuMoNoGa HiTuYoUDa.[Exit after button press]

textb540:
.db $3d $2e $39 $32 $2e $19 $00 $22 $02 $2b $16 $1a TextNewLine
.db $06 $08 $0c $14 $43 $27 $33 $00 $01 $29 $2e $3d $3b $4c TextButtonEnd
; DaNZiyoNNo MeIRoNiHa[Line break]
; KaKuSiToBiRaGa ARuNDaZe.[Exit after button press]

textb55c:
.db $20 $27 $08 $29 $07 $4d $1a $00 $1f $1e $03 $19 $41 $01 $40 $23 TextNewLine
.db $01 $09 $29 $0a $14 $33 $00 $40 $07 $29 $3c $4c TextButtonEnd
; MiRaKuRuKi-Ha MaHoUNoDoADeMo[Line break]
; AKeRuKoToGa DeKiRuZo.[Exit after button press]

textb57a:
.db $40 $3c $28 $01 $2e $16 $1a $00 $03 $0f $12 $07 $23 $00 $02 $29 $06 $27 $07 $2d $12 $09 $15 $26 $4c TextButtonEnd
; DeZoRiANNiHa USoTuKiMo IRuKaRaKiWoTuKeNaYo.[Exit after button press]

textb594:
.db $2c $10 $0c $16 $00 $1a $15 $0c $06 $09 $29 $14 $1a TextNewLine
.db $25 $03 $07 $33 $00 $01 $29 $18 $04 $4c $00 $33 $2e $42 $2a $26 $4c TextButtonEnd
; WaTaSiNi HaNaSiKaKeRuToHa[Line break]
; YuUKiGa ARuNeE. GaNBaReYo.[Exit after button press]

textb5b4:
.db TextEnemyName $1a $00 $06 $27 $3d $16 TextNewLine
.db $11 $06 $27 $33 $00 $20 $15 $34 $29 $19 $2d $06 $2e $39 $10 $4c TextPauseEnd
; [enemy name]Ha KaRaDaNi[Line break]
; TiKaRaGa MiNaGiRuNoWoKaNZiTa.[Exit after pause]

textb5cd:
.db TextEnemyName $1a $00 $10 $06 $27 $42 $0a $2d TextNewLine
.db $23 $2f $13 $02 $10 $4c TextEnd
; [enemy name]Ha TaKaRaBaKoWo[Line break]
; MotuTeITa.[Exit immediately]

textb5de:
.db $02 $1f $00 $1b $33 $0c $2d $21 $02 $13 $02 $29 $4c TextButtonEnd
; IMa HiGaSiWoMuITeIRu.[Exit after button press]

textb5ec:
.db $02 $1f $00 $16 $0c $2d $00 $21 $02 $13 $02 $29 $4c TextButtonEnd
; IMa NiSiWo MuITeIRu.[Exit after button press]

textb5fa:
.db $02 $1f $00 $07 $10 $2d $00 $21 $02 $13 $02 $29 $4c TextButtonEnd
; IMa KiTaWo MuITeIRu.[Exit after button press]

textb608:
.db $02 $1f $00 $20 $15 $20 $2d $00 $21 $02 $13 $02 $29 $4c TextButtonEnd
; IMa MiNaMiWo MuITeIRu.[Exit after button press]

textb617:
.db $01 $28 $0b $10 $11 $1a $00 $3b $2e $22 $12 $0c $10 $4c TextButtonEnd
; ARiSaTaTiHa ZeNMeTuSiTa.[Exit after button press]

textb626:
.db $01 $28 $0b $19 $00 $18 $33 $02 $1a $00 $27 $0c $4d $08 $19 TextNewLine
.db $24 $46 $03 $19 $00 $1f $04 $16 TextButton
.db $21 $15 $0c $08 $00 $07 $04 $0b $2f $10 $4c TextNewLine
.db $0a $0a $40 $00 $46 $03 $09 $2e $1a $00 $05 $2c $28 $40 $0d $4c TextButtonEnd
; ARiSaNo NeGaIHa RaSi-KuNo[Line break]
; YaBoUNo MaENi[Wait for button press and blank text]
; MuNaSiKu KiESatuTa.[Line break]
; KoKoDe BoUKeNHa OWaRiDeSu.[Exit after button press]

textb65c:
.db $05 $06 $18 $33 $00 $10 $28 $15 $02 $26 $03 $40 $0d $18 $4c TextNewLine
.db $1f $10 $07 $13 $08 $3d $0b $02 $4c TextButtonEnd
; OKaNeGa TaRiNaIYoUDeSuNe.[Line break]
; MaTaKiTeKuDaSaI.[Exit after button press]

textb676:
.db $0f $2a $1a $00 $01 $14 $40 $00 $24 $08 $16 $10 $11 $1f $0d $26 $4c TextButtonEnd
; SoReHa AToDe YaKuNiTaTiMaSuYo.[Exit after button press]

textb688:
.db $10 $06 $27 $42 $0a $2d $00 $20 $12 $09 $10 $4c TextEnd
; TaKaRaBaKoWo MiTuKeTa.[Exit immediately]

textb695:
.db $01 $29 $13 $21 $1a $21 $27 $21 $00 $01 $00 $03 $2f $4c TextNewLine
.db $37 $1e $2f $4c $37 $1e $2f $4c TextButton
.db $37 $22 $2e $15 $0b $02 $4c TextNewLine
.db $41 $03 $24 $27 $00 $0c $2f $47 $02 $0c $10 $26 $03 $40 $0d $4c TextButtonEnd
; ARuTeMuHaMuRaMu A Utu.[Line break]
; GoHotu.GoHotu.[Wait for button press and blank text]
; GoMeNNaSaI.[Line break]
; DoUYaRa SituPaISiTaYoUDeSu.[Exit after button press]

textb6c6:
.db $23 $10 $43 $01 $00 $25 $07 $40 $0d $4c $19 $28 $1f $0d $06 $4c TextEnd
; MoTaBiA YuKiDeSu.NoRiMaSuKa.[Exit immediately]

textb6d7:
.db $47 $29 $1f $00 $25 $07 $40 $0d $4c $19 $28 $1f $0d $06 $4c TextEnd
; PaRuMa YuKiDeSu.NoRiMaSuKa.[Exit immediately]

textb6e7:
.db TextCharacterName $1a $00 $23 $03 TextNewLine
.db $11 $06 $27 $02 $2f $47 $02 $40 $0d $4c TextButtonEnd
; [character name]Ha MoU[Line break]
; TiKaRaItuPaIDeSu.[Exit after button press]

textb6f8:
TextChooseWhichToContinue:
.db $36 $4d $21 $19 $00 $12 $3f $07 $2d $00 $24 $28 $1f $0d $4c TextNewLine
.db $42 $2e $37 $03 $2d $00 $04 $27 $2e $40 $08 $3d $0b $02 $4c TextEnd
; Ge-MuNo TuDuKiWo YaRiMaSu.[Line break]
; BaNGoUWo ERaNDeKuDaSaI.[Exit immediately]
; Choose which game to continue.

textb718:
TextContinuingGameX:
.db $40 $1a $00 TextNumber $42 $2e $19 $36 $4d $21 $2d $00 $1a $39 $22 $1f $0d $4c TextPauseEnd
; DeHa [number]BaNNoGe-MuWo HaZiMeMaSu.[Exit after pause]
; Continuing game x...

textb72b:
.db $47 $0d $2c $4d $41 $33 $00 $11 $33 $02 $1f $0d $4c TextNewLine
.db $23 $03 $02 $11 $41 $00 $10 $0c $06 $22 $13 $08 $3d $0b $02 $4c TextButtonEnd
; PaSuWa-DoGa TiGaIMaSu.[Line break]
; MoUITiDo TaSiKaMeTeKuDaSaI.[Exit after button press]

textb74a:
TextContinueOrDelete:
.db $36 $4d $21 $19 $12 $3f $07 $2d $00 $24 $29 $4c $4d $4d $00 $1a $02 TextNewLine
.db $36 $4d $21 $2d $00 $09 $0d $4c $4d $4d $4d $4d $4d $4d $00 $02 $02 $04 TextEnd
; Ge-MuNoTuDuKiWo YaRu.-- HaI[Line break]
; Ge-MuWo KeSu.------ IIE[Exit immediately]
; Continue -> Yes
; Delete -> No

textb76f:
TextConfirmDelete:
.db $0e $4d $44 $0c $10 $00 $36 $4d $21 $2d $00 $09 $0c $1f $0d $4c TextNewLine
.db $02 $02 $40 $0d $06 $4c TextEnd
; Se-BuSiTa Ge-MuWo KeSiMaSu.[Line break]
; IIDeSuKa.[Exit immediately]
; This will delete, OK?

textb787:
TextChooseWhichToDelete:
.db $15 $2e $42 $2e $19 $00 $36 $4d $21 $2d $00 $09 $0c $1f $0d $06 $4c TextEnd
; NaNBaNNo Ge-MuWo KeSiMaSuKa.[Exit immediately]
; Delete: select number

textb799:
TextGameXHasBeenDeleted:
.db TextNumber $42 $2e $19 $00 $36 $4d $21 $2d $00 $09 $0c $1f $0c $10 $4c TextButtonEnd
; [number]BaNNo Ge-MuWo KeSiMaSiTa.[Exit after button press]
; Game x has been deleted.

textb7aa:
.db TextCharacterName $1a $00 $02 $0c $16 $00 $15 $2f $13 $0c $1f $2f $10 $4c TextButtonEnd
; [character name]Ha ISiNi NatuTeSiMatuTa.[Exit after button press]

textb7ba:
.db TextItem $1a $00 $02 $1f $00 $3d $2a $06 $33 TextNewLine
.db $12 $06 $2f $13 $0c $1f $2f $10 $4c TextButtonEnd
; [item]Ha IMa DaReKaGa[Line break]
; TuKatuTeSiMatuTa.[Exit after button press]

textb7cf:
.db $0c $3d $02 $16 $00 $0f $27 $33 $00 $01 $06 $29 $08 $15 $2f $13 $02 $07 $1b $14 $43 $14 $23 $00 $1d $02 $2c $2d $00 $14 $28 $23 $41 $0c $10 $4c TextEnd
; SiDaINi SoRaGa AKaRuKuNatuTeIKiHiToBiToMo HeIWaWo ToRiMoDoSiTa.[Exit immediately]

textb7f4:
.db $02 $1f $00 $42 $24 $1f $4d $2a $1a $00 $0b $2c $24 $06 $15 TextNewLine
.db $0f $26 $06 $3b $16 $00 $12 $12 $1f $2a $13 $02 $29 $4c TextEnd
; IMa BaYaMa-ReHa SaWaYaKaNa[Line break]
; SoYoKaZeNi TuTuMaReTeIRu.[Exit immediately]

textb813:
.db $06 $2a $27 $19 $00 $15 $33 $08 $00 $08 $29 $0c $06 $2f $10 $10 $43 $2d $0f $26 $06 $3b $1a $00 $0c $2f $13 $02 $29 $19 $3d $2b $03 $06 $4c TextEnd
; KaReRaNo NaGaKu KuRuSiKatuTaTaBiWoSoYoKaZeHa SituTeIRuNoDaRoUKa.[Exit immediately]

textb837:
.db $20 $30 $03 $16 $00 $19 $2f $13 $02 $10 $00 $01 $28 $0b $10 $11 $1a TextNewLine
.db $0f $27 $16 $00 $1e $03 $28 $3d $0b $2a $13 $0c $1f $2f $10 $4c TextButtonEnd
; MiyaUNi NotuTeITa ARiSaTaTiHa[Line break]
; SoRaNi HoURiDaSaReTeSiMatuTa.[Exit after button press]

textb85a:
.db $0f $19 $14 $07 $00 $01 $28 $0b $19 $00 $10 $1f $0c $02 $1a TextNewLine
.db $18 $2b $19 $0a $04 $2d $00 $07 $02 $10 $4c TextButton
.db $05 $1f $04 $1a $00 $1c $10 $10 $43 $00 $02 $07 $13 TextNewLine
.db $1d $02 $2c $19 $10 $22 $16 $00 $12 $08 $0d $33 $02 $02 $4c TextButton
.db $01 $28 $0b $19 $00 $10 $1f $0c $02 $1a $00 $26 $20 $33 $04 $2f $10 $4c TextButtonEnd
; SoNoToKi ARiSaNo TaMaSiIHa[Line break]
; NeRoNoKoEWo KiITa.[Wait for button press and blank text]
; OMaEHa HuTaTaBi IKiTe[Line break]
; HeIWaNoTaMeNi TuKuSuGaII.[Wait for button press and blank text]
; ARiSaNo TaMaSiIHa YoMiGaEtuTa.[Exit after button press]

textb8a7:
.db $0a $0a $2b $33 $00 $15 $37 $21 $26 $03 $15 TextNewLine
.db $03 $12 $08 $0c $02 $00 $18 $02 $2b $3d $4c TextButtonEnd
; KoKoRoGa NaGoMuYoUNa[Line break]
; UTuKuSiI NeIRoDa.[Exit after button press]

;textb8bf:
TextIntro1:
.db $27 $0c $4d $08 $0b $1f $19 $00 $0a $14 $2d $00 $0a $0f $0a $0f $14 TextNewLine
.db $06 $34 $1f $2c $28 $24 $33 $2f $13 $4c TextNewLine
.db $0a $2a $06 $27 $1a $00 $0e $02 $3b $02 $00 $05 $14 $15 $0c $08 TextNewLine
.db $0c $13 $02 $29 $0a $14 $3d $15 $4c TextButton
.db $16 $02 $0b $2e $4c TextNewLine
.db $15 $16 $33 $00 $01 $2f $10 $19 $4c TextNewLine
.db $0c $2f $06 $28 $0c $13 $4c TextButtonEnd
; RaSi-KuSaMaNo KoToWo KoSoKoSoTo[Line break]
; KaGiMaWaRiYaGatuTe.[Line break]
; KoReKaRaHa SeIZeI OToNaSiKu[Line break]
; SiTeIRuKoToDaNa.[Wait for button press and blank text]
; NiISaN.[Line break]
; NaNiGa AtuTaNo.[Line break]
; SituKaRiSiTe.[Exit after button press]
; You little bastard - poking your nose into LaShiec's business like that!
; Maybe from now on you'll try to mind your manners!
; Nero! What happened?! Hang on!

;textb90f:
TextIntro2:
.db $01 $28 $0b $4c $07 $02 $13 $08 $2a $4c TextNewLine
.db $27 $0c $4d $08 $1a $00 $0a $19 $1e $0c $16 $00 $07 $32 $3d $02 $15 TextNewLine
.db $2c $38 $2c $02 $2d $00 $1f $18 $02 $13 $0c $1f $2f $10 $4c TextNewLine
.db $0e $06 $02 $1a $00 $1a $22 $12 $16 $00 $21 $06 $2f $13 $02 $29 $4c TextButton
.db $05 $2a $1a $00 $27 $0c $4d $08 $33 $00 $15 $16 $2d $00 $10 $08 $27 $2e $40 TextNewLine
.db $02 $29 $19 $06 $00 $0b $35 $2f $13 $02 $10 $2e $3d $4c TextNewLine
.db $09 $41 $00 $05 $2a $1b $14 $28 $40 $1a $00 $41 $03 $0d $29 $0a $14 $23 TextNewLine
.db $40 $07 $15 $06 $2f $10 $4c TextButton
.db $10 $43 $19 $00 $14 $11 $31 $03 $00 $10 $02 $2b $2e $00 $14 $02 $03 TextNewLine
.db $12 $26 $02 $00 $05 $14 $0a $19 $00 $03 $2c $0b $2d $00 $07 $02 $10 $4c TextNewLine
.db $06 $2a $14 $00 $02 $2f $0c $32 $15 $27 $00 $27 $0c $4d $08 $2d $00 $10 $05 $0c TextNewLine
.db $1d $02 $2c $2d $00 $14 $28 $23 $41 $0d $0a $14 $33 $40 $07 $29 $3d $2b $03 $4c TextButton
.db $01 $28 $0b $4c TextNewLine
.db $05 $2a $1a $00 $23 $03 $00 $3d $22 $3d $4c TextNewLine
.db $05 $1f $04 $00 $1b $14 $28 $2d $00 $19 $0a $0c $13 $02 $08 $00 $05 $2a $2d TextNewLine
.db $25 $29 $0c $13 $08 $2a $4c TextButtonEnd
; ARiSa.KiITeKuRe.[Line break]
; RaSi-KuHa KoNoHoSiNi KiyoDaINa[Line break]
; WaZaWaIWo MaNeITeSiMatuTa.[Line break]
; SeKaIHa HaMeTuNi MuKatuTeIRu.[Wait for button press and blank text]
; OReHa RaSi-KuGa NaNiWo TaKuRaNDe[Line break]
; IRuNoKa SaGutuTeITaNDa.[Line break]
; KeDo OReHiToRiDeHa DoUSuRuKoToMo[Line break]
; DeKiNaKatuTa.[Wait for button press and blank text]
; TaBiNo ToTiyuU TaIRoN ToIU[Line break]
; TuYoI OToKoNo UWaSaWo KiITa.[Line break]
; KaReTo ItuSiyoNaRa RaSi-KuWo TaOSi[Line break]
; HeIWaWo ToRiMoDoSuKoToGaDeKiRuDaRoU.[Wait for button press and blank text]
; ARiSa.[Line break]
; OReHa MoU DaMeDa.[Line break]
; OMaE HiToRiWo NoKoSiTeIKu OReWo[Line break]
; YuRuSiTeKuRe.[Exit after button press]
; ...Alisa... listen...
; ...LaShiec has brought an enormous calamity upon our world...
; ...The world is facing ruin...
; ...I tried to find out what LaShiec is planning...
; ...But by myself, I wasn't able to do anything...
; ...I heard rumours of a mighty warrior named 'Tairon' during my journey...
; ...If you combine forces, you might be able to defeat LaShiec... and restore peace...
; ...Alisa...
; ...It's too late for me...
; ...Please forgive me... for leaving you alone...

;textba08:
TextIntro3:
.db $01 $28 $0b $1a $00 $16 $02 $0b $2e $19 $00 $02 $19 $11 $2d $00 $21 $3d $16 TextNewLine
.db $0c $15 $02 $10 $22 $16 $00 $10 $10 $06 $02 $16 $00 $02 $07 $1f $0d $4c TextNewLine
.db $07 $2f $14 $00 $20 $1f $23 $2f $13 $02 $13 $18 $4c TextNewLine
.db $16 $02 $0b $2e $4c TextButtonEnd
; ARiSaHa NiISaNNo INoTiWo MuDaNi[Line break]
; SiNaITaMeNi TaTaKaINi IKiMaSu.[Line break]
; KituTo MiMaMotuTeITeNe.[Line break]
; NiISaN.[Exit after button press]
; I will go and fight to ensure that my brother did not die in vain!
; I know he will be watching over me...

textba43:
.db $07 $32 $03 $06 $27 $00 $15 $06 $1f $18 $4c TextNewLine
.db $2c $10 $0c $1a $00 $01 $28 $0b $4c TextNewLine
.db $01 $15 $10 $19 $00 $15 $1f $04 $2d $00 $05 $0c $04 $13 $4c TextButtonEnd
; KiyoUKaRa NaKaMaNe.[Line break]
; WaTaSiHa ARiSa.[Line break]
; ANaTaNo NaMaEWo OSiETe.[Exit after button press]

textba69:
.db $20 $30 $03 $4c TextButtonEnd
; MiyaU.[Exit after button press]

textba6e:
.db $18 $04 $00 $20 $30 $03 $4c TextNewLine
.db $10 $02 $2b $2e $19 $00 $0a $14 $00 $15 $2e $3d $09 $41 $00 $15 $16 $06 TextNewLine
.db $0c $2f $13 $02 $10 $27 $00 $05 $0c $04 $13 $4c TextButtonEnd
; NeE MiyaU.[Line break]
; TaIRoNNo KoTo NaNDaKeDo NaNiKa[Line break]
; SituTeITaRa OSiETe.[Exit after button press]

textba96:
.db $10 $02 $2b $2e $00 $02 $0c $16 $00 $15 $2f $11 $30 $2f $10 $19 $4c TextNewLine
.db $0a $19 $00 $08 $0d $28 $00 $06 $09 $2a $42 $00 $15 $05 $29 $2e $3d $4c TextNewLine
.db $09 $41 $00 $20 $30 $03 $00 $43 $2e $19 $00 $1c $10 TextNewLine
.db $01 $09 $27 $2a $15 $02 $19 $4c TextButtonEnd
; TaIRoN ISiNi NatuTiyatuTaNo.[Line break]
; KoNo KuSuRi KaKeReBa NaORuNDa.[Line break]
; KeDo MiyaU BiNNo HuTa[Line break]
; AKeRaReNaINo.[Exit after button press]

textbad2:
.db $0f $2f $06 $4c TextNewLine
.db $39 $30 $00 $02 $2f $0c $32 $16 $00 $10 $02 $2b $2e $2d TextNewLine
.db $10 $0d $09 $16 $00 $02 $07 $1f $0c $32 $03 $4c TextButtonEnd
; SotuKa.[Line break]
; Ziya ItuSiyoNi TaIRoNWo[Line break]
; TaSuKeNi IKiMaSiyoU.[Exit after button press]

textbaf3:
.db $01 $28 $33 $14 $03 $4c $10 $0d $06 $2f $10 $26 $4c TextNewLine
.db $0c $06 $0c $00 $22 $40 $31 $4d $0b $16 TextNewLine
.db $0c $13 $24 $27 $2a $29 $26 $03 $40 $1a $00 $27 $0c $4d $08 $1a TextNewLine
.db $10 $05 $0e $0f $03 $16 $00 $15 $02 $15 $4c TextButtonEnd
; ARiGaToU.TaSuKatuTaYo.[Line break]
; SiKaSi MeDeyu-SaNi[Line break]
; SiTeYaRaReRuYoUDeHa RaSi-KuHa[Line break]
; TaOSeSoUNi NaINa.[Exit after button press]

textbb29:
.db $2c $10 $0c $19 $00 $16 $02 $0b $2e $23 $00 $27 $0c $4d $08 $2d TextNewLine
.db $10 $05 $0f $03 $14 $0c $13 $00 $0c $2e $40 $0c $1f $2f $10 $2c $4c TextNewLine
.db $0c $17 $1f $04 $16 $00 $01 $15 $10 $19 $00 $15 $1f $04 $2d TextNewLine
.db $02 $02 $19 $0a $0c $13 $4c TextButtonEnd
; WaTaSiNo NiISaNMo RaSi-KuWo[Line break]
; TaOSoUToSiTe SiNDeSiMatuTaWa.[Line break]
; SiNuMaENi ANaTaNo NaMaEWo[Line break]
; IINoKoSiTe.[Exit after button press]

textbb64:
.db $0f $03 $3d $2f $10 $19 $06 $4c TextNewLine
.db $26 $0c $00 $07 $20 $19 $00 $16 $02 $0b $2e $19 $00 $10 $22 $16 $23 TextNewLine
.db $11 $06 $27 $2d $00 $01 $2c $0e $13 $00 $27 $0c $4d $08 $2d TextNewLine
.db $10 $05 $0f $03 $4c TextButtonEnd
; SoUDatuTaNoKa.[Line break]
; YoSi KiMiNo NiISaNNo TaMeNiMo[Line break]
; TiKaRaWo AWaSeTe RaSi-KuWo[Line break]
; TaOSoU.[Exit after button press]

textbb95:
.db $0f $2a $26 $28 $00 $15 $3b $00 $22 $40 $31 $4d $0b $2d TextNewLine
.db $10 $05 $0f $03 $14 $00 $0c $10 $19 $4c TextButtonEnd
; SoReYoRi NaZe MeDeyu-SaWo[Line break]
; TaOSoUTo SiTaNo.[Exit after button press]

textbbaf:
.db $22 $40 $31 $4d $0b $33 $00 $23 $2f $13 $02 $29 $00 $40 $2e $0e $12 $19 TextNewLine
.db $05 $19 $33 $00 $1e $0c $06 $2f $10 $2e $3d $09 $41 TextNewLine
.db $16 $36 $27 $2a $11 $1f $2f $10 $4c TextNewLine
.db $08 $24 $0c $02 $15 $01 $4c TextButton
.db $0f $03 $02 $04 $42 $00 $05 $2a $00 $0a $19 $00 $41 $03 $08 $12 $19 TextNewLine
.db $02 $07 $41 $1f $28 $16 $00 $0a $2e $47 $0d $2d TextNewLine
.db $06 $08 $0c $13 $05 $02 $10 $2e $3d $2f $09 $4c TextNewLine
.db $14 $28 $16 $00 $02 $0a $03 $3b $4c TextButtonEnd
; MeDeyu-SaGa MotuTeIRu DeNSeTuNo[Line break]
; ONoGa HoSiKatuTaNDaKeDo[Line break]
; NiGeRaReTiMatuTa.[Line break]
; KuYaSiINaA.[Wait for button press and blank text]
; SoUIEBa ORe KoNo DoUKuTuNo[Line break]
; IKiDoMaRiNi KoNPaSuWo[Line break]
; KaKuSiTeOITaNDatuKe.[Line break]
; ToRiNi IKoUZe.[Exit after button press]

textbc18:
.db $0f $03 $14 $08 $06 $27 $19 $00 $13 $33 $20 $2d $00 $01 $3a $06 $2f $13 TextNewLine
.db $07 $1f $0c $10 $4c TextNewLine
.db $26 $2e $40 $02 $10 $3d $09 $1f $0e $2e $06 $4c TextButtonEnd
; SoUToKuKaRaNo TeGaMiWo AZuKatuTe[Line break]
; KiMaSiTa.[Line break]
; YoNDeITaDaKeMaSeNKa.[Exit after button press]

textbc3e:
.db $2c $06 $28 $1f $0c $10 $4c TextNewLine
.db $20 $2e $15 $40 $00 $0a $19 $00 $01 $29 $37 $29 $10 $02 $26 $03 $09 $02 $2d TextNewLine
.db $01 $08 $19 $00 $13 $06 $27 $00 $1f $23 $28 $1f $0c $32 $03 $4c TextButton
.db $0f $19 $10 $22 $16 $1a $00 $1f $3a $33 $0c $0a $19 $00 $23 $28 $1d TextNewLine
.db $02 $2f $13 $00 $29 $45 $19 $1a $06 $0e $16 $00 $01 $02 $10 $02 $4c TextNewLine
.db $10 $0c $06 $00 $1f $2e $1e $4d $29 $2d $00 $14 $05 $2f $13 TextNewLine
.db $02 $09 $10 $1a $3a $40 $0d $4c TextButtonEnd
; WaKaRiMaSiTa.[Line break]
; MiNNaDe KoNo ARuGoRuTaIYoUKeIWo[Line break]
; AKuNo TeKaRa MaMoRiMaSiyoU.[Wait for button press and blank text]
; SoNoTaMeNiHa MaZuGaSiKoNo MoRiHe[Line break]
; ItuTe RuBeNoHaKaSeNi AITaI.[Line break]
; TaSiKa MaNHo-RuWo ToOtuTe[Line break]
; IKeTaHaZuDeSu.[Exit after button press]

textbca8:
.db $27 $04 $29 $1f $45 $28 $4d $2d $00 $06 $39 $29 $14 TextNewLine
.db $20 $30 $03 $19 $00 $06 $27 $3d $1a $00 $18 $12 $2d $00 $05 $43 TextNewLine
.db $1f $42 $25 $02 $00 $1b $06 $28 $16 $00 $12 $12 $1f $2a $10 $4c TextButtonEnd
; RaERuMaBeRi-Wo KaZiRuTo[Line break]
; MiyaUNo KaRaDaHa NeTuWo OBi[Line break]
; MaBaYuI HiKaRiNi TuTuMaReTa.[Exit after button press]

textbcd8:
.db $0f $0c $13 $00 $20 $29 $20 $29 $00 $03 $11 $16 $00 $20 $30 $03 $1a TextNewLine
.db $05 $05 $07 $15 $00 $12 $42 $0b $2d $00 $23 $2f $10 $00 $03 $12 $08 $0c $02 TextNewLine
.db $09 $23 $19 $1d $14 $00 $06 $2c $2f $10 $4c TextButton
.db $20 $30 $03 $1a $00 $14 $08 $02 $0f $03 $16 $00 $1b $14 $12 TextNewLine
.db $1a $42 $13 $02 $13 $00 $20 $0e $10 $4c TextButtonEnd
; SoSiTe MiRuMiRu UTiNi MiyaUHa[Line break]
; OOKiNa TuBaSaWo MotuTa UTuKuSiI[Line break]
; KeMoNoHeTo KaWatuTa.[Wait for button press and blank text]
; MiyaUHa ToKuISoUNi HiToTu[Line break]
; HaBaTeITe MiSeTa.[Exit after button press]

textbd25:
.db $00 TextNewLine
.db $00 $00 $00 $00 $00 $01 $28 $0b TextPauseEnd
;  [Line break]
;      ARiSa[Exit after pause]

textbd30:
.db $00 TextNewLine
.db $00 $00 $00 $00 $00 $10 $02 $2b $2e TextPauseEnd
;  [Line break]
;      TaIRoN[Exit after pause]

textbd3c:
.db $00 TextNewLine
.db $00 $00 $00 $00 $00 $29 $12 TextPauseEnd
;  [Line break]
;      RuTu[Exit after pause]

textbd46:
.db $00 TextNewLine
.db $00 $00 $00 $00 $00 $0f $0c $13 $00 $20 $30 $03 TextPauseEnd
;  [Line break]
;      SoSiTe MiyaU[Exit after pause]

textbd55:
.db $00 $00 $00 $00 $24 $20 $19 $00 $07 $05 $08 $33 $00 $07 $04 $13 $23 TextNewLine
.db $00 $00 $00 $00 $06 $2a $27 $19 $00 $15 $1f $04 $1a TextNewLine
.db $00 $00 $00 $00 $1b $14 $43 $14 $19 $00 $0a $0a $2b $16 TextNewLine
.db $00 $00 $00 $00 $19 $0a $28 $12 $3f $09 $29 $3d $2b $03 $4c TextPauseEnd
;     YaMiNo KiOKuGa KiETeMo[Line break]
;     KaReRaNo NaMaEHa[Line break]
;     HiToBiToNo KoKoRoNi[Line break]
;     NoKoRiTuDuKeRuDaRoU.[Exit after pause]

; text lookup table for items
ItemTextTable: ; $bd94
.db $00 $00 $00 $00 $00 $00 $00 $00
.db $03 $2f $41 $09 $02 $2e TextButtonEnd $00         ; UtuDoKeIN         Wood Cane
.db $0c $32 $4d $14 $0f $4d $41 TextButtonEnd         ; Siyo-ToSo-Do      Short Sword
.db $01 $02 $01 $2e $0f $4d $41 TextButtonEnd         ; AIANSo-Do         Iron Sword (not in retranslation?)
.db $0b $02 $0a $03 $05 $2e $41 TextButtonEnd         ; SaIKoUONDo        Psycho (Ultimate) Wand
.db $0c $29 $42 $4d $10 $0d $08 TextButtonEnd         ; SiRuBa-TaSuKu     Silver Tusk
.db $01 $02 $01 $2e $01 $08 $0d TextButtonEnd         ; AIANAKuSu         Iron Axe
.db $11 $10 $16 $03 $21 $0f $4d $41                   ; TiTaNiUMuSo-Do    Titanium Sword
.db $0e $27 $20 $2f $08 $0f $4d $41                   ; SeRaMituKuSo-Do   Ceramic Sword
.db $16 $4d $41 $29 $33 $2e TextButtonEnd $00         ; Ni-DoRuGaN        Needle Gun
.db $0b $4d $45 $29 $08 $2b $4d TextButtonEnd         ; Sa-BeRuKuRo-      Sabre Claw
.db $1b $4d $14 $33 $2e TextButtonEnd $00 $00         ; Hi-ToGaN          Heat Gun
.db $27 $02 $14 $0e $02 $42 $4d TextButtonEnd         ; RaIToSeIBa-       Light Sabre
.db $2a $4d $38 $4d $33 $2e TextButtonEnd $00         ; Re-Za-GaN         Laser Gun
.db $27 $0a $16 $01 $2e $0f $4d $41                   ; RaKoNiANSo-Do     Laconian Sword
.db $27 $0a $16 $01 $2e $01 $08 $0d                   ; RaKoNiANAKuSu     Laconian Axe
.db $2a $38 $4d $08 $2b $0d TextButtonEnd $00         ; ReZa-KuRoSu       Leather Clothes
.db $1e $2c $02 $14 $1f $2e $14 TextButtonEnd         ; HoWaIToMaNTo      White Mantle (Cloak)
.db $27 $02 $14 $0d $4d $12 TextButtonEnd $00         ; RaIToSu-Tu        Light Suit
.db $01 $02 $01 $2e $01 $4d $1f $4d                   ; AIANA-Ma-         Iron Armour
.db $14 $36 $28 $0d $19 $09 $33 $2c                   ; ToGeRiSuNoKeGaWa  Spiky Squirrel Fur
.db $39 $29 $0a $16 $01 $22 $02 $29                   ; ZiRuKoNiAMeIRu    Zirconain Mail
.db $3d $02 $24 $19 $26 $2b $02 TextButtonEnd         ; DaIYaNoYoRoI      Diamond Armour
.db $27 $0a $16 $01 $01 $4d $1f $4d                   ; RaKoNiAA-Ma-      Laconian Armour
.db $1c $27 $4d $41 $1f $2e $14 TextButtonEnd         ; HuRa-DoMaNTo      ?
.db $2a $38 $4d $0c $4d $29 $41 TextButtonEnd         ; ReZa-Si-RuDo      Leather Shield
.db $01 $02 $01 $2e $0c $4d $29 $41                   ; AIANSi-RuDo       Iron Shield
.db $46 $2b $2e $0c $4d $29 $41 TextButtonEnd         ; BoRoNSi-RuDo      Boron/Bronze Shield
.db $0e $27 $20 $2f $08 $19 $10 $13                   ; SeRaMituKuNoTaTe  Ceramic Shield
.db $01 $16 $1f $29 $35 $27 $44 TextButtonEnd         ; ANiMaRuGuRaBu     Animal Glove
.db $2a $4d $38 $4d $42 $28 $01 TextButtonEnd         ; Re-Za-BaRiA       Laser Barrier
.db $4a $29 $0e $03 $0d $19 $10 $13                   ; PeRuSeUSuNoTaTe   Shield of Perseus
.db $27 $0a $16 $01 $0c $4d $29 $41                   ; RaKoNiASi-RuDo    Laconian Shield
.db $27 $2e $41 $1f $0d $10 $4d TextButtonEnd         ; RaNDoMaSuTa-      LandMaster
.db $1c $2b $4d $21 $4d $42 $4d TextButtonEnd         ; HuRo-Mu-Ba-       FlowMover
.db $01 $02 $0d $40 $2f $06 $4d TextButtonEnd         ; AISuDetuKa-       IceDecker
.db $4a $2b $28 $4d $22 $02 $14 TextButtonEnd         ; PeRoRi-MeITo      ?  
.db $29 $05 $34 $16 $2e TextButtonEnd $00 $00         ; RuOGiNiN          Ruoginin
.db $0d $4d $3a $1c $29 $4d $14 TextButtonEnd         ; Su-ZuHuRu-To      Soothe Flute
.db $0b $4d $11 $27 $02 $14 TextButtonEnd $00         ; Sa-TiRaITo        Searchlight
.db $04 $0d $09 $4d $49 $08 $2b $0d                   ; ESuKe-PuKuRoSu    Escape Cloth
.db $14 $27 $2e $06 $4d $4a $2f $14                   ; ToRaNKa-PetuTo    TranCarpet
.db $1f $39 $2f $08 $1a $2f $14 TextButtonEnd         ; MaZituKuHatuTo    Magic Hat
.db $01 $29 $0c $31 $28 $2e TextButtonEnd $00         ; ARuSiyuRiN        Alsuline
.db $4b $28 $22 $13 $27 $4d $29 TextButtonEnd         ; PoRiMeTeRa-Ru     Polymeteral/Poly Metal All
.db $3d $2e $39 $32 $2e $07 $4d TextButtonEnd         ; DaNZiyoNKi-       Dungeon Key
.db $13 $2a $47 $0c $4d $46 $4d $29                   ; TeRePaSi-Bo-Ru    Telepathy Ball
.db $02 $08 $28 $49 $0d $14 $4d $11                   ; IKuRiPuSuTo-Ti    Eclipse Torch
.db $04 $01 $2b $49 $28 $3a $21 TextButtonEnd         ; EARoPuRiZuMu      Aeroprism
.db $27 $04 $29 $1f $45 $28 $4d TextButtonEnd         ; RaERuMaBeRi-      Laerma Berries
.db $1a $49 $0d $43 $4d TextButtonEnd $00 $00         ; HaPuSuBi-         Hapsby
.db $2b $4d $41 $47 $0d TextButtonEnd $00 $00         ; Ro-DoPaSu         Roadpass
.db $47 $0d $4b $4d $14 TextButtonEnd $00 $00         ; PaSuPo-To         Passport
.db $0a $2e $47 $0d TextButtonEnd $00 $00 $00         ; KoNPaSu           Compass
.db $0c $32 $4d $14 $09 $4d $07 TextButtonEnd         ; Siyo-ToKe-Ki      Shortcake
.db $0f $03 $14 $08 $19 $13 $33 $20                   ; SoUToKuNoTeGaMi   Commander-General's Letter
.db $27 $0a $16 $01 $2e $4b $2f $14                   ; RaKoNiANPotuTo    Laconian Pot
.db $27 $02 $14 $4a $2e $3d $2e $14                   ; RaIToPeNDaNTo     Light Pendant
.db $06 $4d $42 $2e $08 $29 $01 $02                   ; Ka-BaNKuRuAI      Carbunckle Eye
.db $33 $0d $08 $28 $01 TextButtonEnd $00 $00         ; GaSuKuRiA         GasClear
.db $3d $23 $01 $08 $28 $0d $10 $29                   ; DaMoAKuRiSuTaRu   Damoa's Crystal
.db $1f $0d $10 $4d $0c $0d $13 $21                   ; MaSuTa-SiSuTeMu   Master System
.db $20 $27 $08 $29 $07 $4d TextButtonEnd $00         ; MiRaKuRuKi-       Miracle Key
.db $39 $28 $05 $2e TextButtonEnd $00 $00 $00         ; ZiRiON            Zillion
.db $1b $20 $12 $19 $23 $19 TextButtonEnd $00         ; HiMiTuNoMoNo      ?

