; Lookup table into script

ScriptLookup:
.dw textSuelo1,textSuelo1a,textSuelo2,textNekise1,textNekise1a,textNekise1b,textNekise1c
.dw textNekise2,textCamineet1,tetxCamineet2,textCamineet3,textCamineet4,textCamineet4,textCamineet5,textCamineet6
.dw textCamineet7,textCamineet8,textCamineet9,textParolit1,textParolit2,textParolit3,textParolit3a,textParolit4
.dw textParolit5,textParolit6,textShion1,textShion1a,textShion1b,textShion1c,textShion2,textShion2a
.dw textShion2b,textShion3,textShion4,textShion5,textShion6,textShion7,textShion8,textEppi1
.dw textEppi2,textEppi3,textEppi4,textEppi5,textEppi6,textEppi6a,textEppi7,textEppi7a
.dw textEppi7b_NeverMind,textCamineetAlgolStarSystem,textCamineetAlgolStarSystem_No,textCamineetAlgolStarSystem_No_a,textCamineetAlgolStarSystem_No_b,textPalmaSpaceport1,textPalmaSpaceport2,textPalmaSpaceport3
.dw textPalmaSpaceport4,textPalmaSpaceport5,textPalmaSpaceport5a,textPalmaSpaceport5b,textPalmaSpaceport5c,textPalmaSpaceport5d,textPalmaSpaceport5e,textPalmaSpaceport5f
.dw textPaseoSpaceport1,textPaseoSpaceport2,text8afc,textPaseo1,textPaseo2,textPaseo3,textPaseo4,textPaseo5
.dw textPaseo6,textPaseoTrader,textPaseoTrader_Yes,textPaseoTrader_No,textPaseoTrader_No_a,textPaseoTrader_No_Yes,textPaseoGuard1,textPaseoGuard1_Yes
.dw textPaseoGuard1_Yes_NoShortcake,textPaseoGuard1_No,textGovernorGeneral1,textGovernorGeneral1a,textGovernorGeneral1b,textGovernorGeneral1c,textMahalCave_NoLutz,textMahalCave_Lutz_NoLetter
.dw textMahalCave_Lutz_NoLetter_a,textMahalCave_WithLutz,textPaseoPassageGuard1,textGuestHouse1,textGuestHouse1a,textGothic1,textGothic1_Yes,textGothic1_Yes_a
.dw textGothic1_Yes_b,textGothic1_No,textGothic2_Yes,textGothic2_Yes_a,textGothic2_Yes_b,textDrLuveno1,textDrLuveno1a,textPalmaSpaceport4_No
.dw textDrLuveno1b,textDrLuveno1c,textDrLuvenoPrison_3_No,textDrLuveno1e,textDrLuveno2,textDrLuveno1g,text8fd1,textDrLuvenoPrison_1
.dw textDrLuvenoPrison_2,textDrLuvenoPrison_3,textDrLuvenoPrison_3_Yes,textTriada1,textTriada1_No,textTriada2_Yes,textTriada3,textTriada4
.dw textTriada5,textTriada6,textTriada7,text91a6,textMedusasTower1,textTylonCave1,textMedusasTower2,textMedusasTower3
.dw textMedusasTower4,textBartevo1,textDrLuveno1f,textBartevo2,text92fc,textBartevoCave,textLore1,textLore2
.dw text9374,textLore3,textLore4,textLore4_No,textLore5,textUnused1,textAvion1,textAvion2
.dw textAvion3,textAvion3a,textTriada3_No,textAvion4,textAvion5,textAvion5a,textHapsby1,textUzo1
.dw textUzo2,textUzo3,textUzo4,textUzo5,textUzo5a,textUzo6,textReallyWhatABore,textUzo6_No
.dw textUzo6_Noa,textScionTrader1,textScionTrader2,textScionTrader3,textDamoa1,textDamoa1a,textTriada6_Yes,textDamoa1_Yes
.dw textDamoa2,textDamoa1_No,textDamoa3,textDamoa4,textDamoa4_Yes,textDamoa5,textDamoa6,textDamoa6a
.dw text980d,text980dYes,text980dNo,textCasba1,textCasba2,textAeroCastle1,textCasba3,textCasba3a
.dw textCasba4,textCasba5,textCasba5Yes,textCasba5Yes_a,textShionFoundFlowMover,textShionFoundFlowMover_a,textCasba5No,textDrasgo1
.dw textDrasgo2,textDrasgo2a,textDrasgo3,textDrasgo4,textChokoOneesan,textChokoOneesan_a,textDrasgoCave1,textDrasgoCave1a
.dw textDrasgoCave2,textDrasgoCave2a,textDrasgoCave3,textDrasgoCave3a,textDrasgoCave3Yes,textDrasgoCave3Yes_NoMoney,textDrasgoCave3No,textSpaceportClosed
.dw textPassportConfiscated,textSkray1,textSkray2,textSkray3,textSkray3a,textSkray4,textSkray4a,textSkray4b
.dw textSkray4c,textSkray5,textSkray5a,textSkray5b,textSkray6,textSkray7,textSkray8,textSkray9
.dw textSkray9a,textSkray9b,textSkray10,textSkray10a,textHonestDezorian1,textHonestDezorian2,textHonestDezorian3,textHonestDezorian3a
.dw textHonestDezorian4,textHonestDezorian4a,textHonestDezorian4b,textHonestDezorian5,textHonestDezorian5_No,textHonestDezorian5_Yes,textHonestDezorian6,textDishonestDezorian1
.dw textDishonestDezorian2,textDishonestDezorian3,textDishonestDezorian4,textDishonestDezorian5,textSopia1,textSopia2,textSopia2a,textSopia2b
.dw textSopia2_No,textSopia2_Yes_NoMoney,textSopia2_Yes,textSopia2_Yes_a,textSopia2_Yes_b,textGamerMiki,textGamerMiki_Yes,textGamerMiki_No
.dw textSopia3,textSopia4,textSopia5,textSopia5_Yes,textSopia5_No,textSopia6_Yes,textSopia6_No,textSopia6_Yes_NoPelorieMate
.dw textAeroCastle2,textGovernorGeneral2_Yes,textBayaMarlayPrison1,textBayaMarlayPrison1a,textBayaMarlayPrison2,textAvionTower,textBayaMarlayPrison3,textBayaMarlayPrison3_Yes
.dw textBayaMarlayPrison3_Yes_a,textBayaMarlayPrison4,textBayaMarlayPrison5,textBayaMarlayPrison6,textBayaMarlayPrison7,textBayaMarlayPrison7_No,textBayaMarlayPrison7_Yes,textBayaMarlayPrison8
.dw textGovernorGeneral2_No,textBayaMarlayPrison9,textCoronaTower1,textUnused2,textCoronaTower2,textCoronaTower3,textCoronaTower3a,textCoronaTowerTorchbearer
.dw textCoronaTowerTorchbearer_a,textCoronaTowerTorchbearer_b,textCoronaTowerTorchbearer_Yes,textCoronaTowerTorchbearer_No,textCoronaTowerTorchbearer_Yes_NoCarbuncleEye,textNaulaCaveShortcakeSalesman,textTajim1,textTajim1a
.dw textTajim_Win,textTajim_Win_a,textTajim_Win_b,textTajim_Lose,textTajim2,textTajim_NoLutzYet,textTajim_NoLutzYet_a,textTajim_NoLutzYet_Yes
.dw textTajim_NoLutzYet_No,textShadowWarrior,textShadowWarrior_a,textShadowWarrior_Win,textShadowWarrior_Win_a,textAeroCastle3,textLaShiec,textLaShiec_Yes
.dw textLaShiec_No,textGovernorGeneral2,textGovernorGeneral2a,textGovernorGeneral2b,textGovernorGeneral2c,textOtegamiChieChan,textLuvenoGuard1,textLuvenoGuard1
.dw textLuvenoGuard1,textLuvenoGuard1,textLuvenoGuard2,textShion9,textPaseo6,textPaseoTrader_HaveMyau,textDrLuveno1h,textDrLuveno1i
.dw textDrLuveno1j,textDrLuveno1k,textDrLuveno1l,textMadDoctor,textMadDoctor_Yes,textMadDoctor_No,textGovernorGeneral3,textGovernorGeneral4
.dw textGuestHouse2,textGuestHouse2a,textAlisasHouse,textGovernorGeneral5,textTajim1_LutzDead,textLaShiec_Win

; Script

textSuelo1:
.stringmap script "ワタシハ　スエロ。アリサノ　キモチハ"
.stringmap script "ヨクワカルワ。モウダレモ　アナタヲ<wait more>"
textSuelo1a:
.stringmap script "トメルコトハ　デキナイ。　デモ　モシ"
.stringmap script "タタカイデ　キズツイタトキハ<wait>"
; My name is Suelo.
; I know how you feel, Alisa. No one will be able to stop you from doing what you must do.

textSuelo2:
.stringmap script "ココデ　ユックリ　ヤスンデ　オユキ。<wait more>"
.stringmap script "ムリヲ　シナイヨウニネ。<line>"
.stringmap script "マタ　イツデモ　イラッシャイ。<wait>"
; Please relax and recover.
; Don't overdo it, okay? You will always be welcome here.

textNekise1:
.stringmap script "ボクハ　ネキセ。<line>"
.stringmap script "キクトコロニ　ヨルト<wait more>"
textNekise1a:
.stringmap script "ユウシャ　タイロンハ　シオントイウ<line>"
.stringmap script "マチニ　イルラシイ。<wait more>"
textNekise1b:
.stringmap script "アッ。ソレト　ネロカラ<line>"
.stringmap script "ラコニアンポット　トイウ　ツボヲ<wait more>"
textNekise1c:
.stringmap script "アズカッテタンダ。アトデ　ヤクニ<line>"
.stringmap script "タツダロウカラ　モッテイクトイイヨ。<wait>"
; My name is Nekise.
; I just found out that the hero Tairon is staying in the town of Shion.
; Oh, and, your brother entrusted me with this jar - it's called a Laconian Pot.
; Here, you should take it with you. It may come in handy later on.

textNekise2:
.stringmap script "チカラニナレナクテ　ゴメン。<line>"
.stringmap script "ブジヲ　イノッテルヨ。<wait>"
; Forgive me, but there is nothing more I can do. May your journey be safe.

textCamineet1:
.stringmap script "コノ　カミニート　キョジュウクハ<line>"
.stringmap script "カイゲンレイガ　シカレテイルンダ。<wait>"
; The Camineet residential district is under martial law.

tetxCamineet2:
.stringmap script "カギノ　カカッタ　ドアヲ　アケルニハ"
.stringmap script "ダンジョンキーガ　ヒツヨウデス。<wait>"
; You need a ‘Dungeon Key’ to open locked doors.

textCamineet3:
.stringmap script "アカリガナイト　ススメナイ<line>"
.stringmap script "ダンジョンモ　アルヨ。<wait>"
; You will not be able to advance through certain dungeons if you don't have a light.

textCamineet4:
.stringmap script "カミニートノ　ニシハ　スペースポート"
.stringmap script "デス。<wait>"
; West of Camineet? That's the Spaceport.

textCamineet4:
.stringmap script "ミナトマチデハ　イロイロナ　トリヒキ"
.stringmap script "ガ　デキル　トイウ　ハナシダ。<wait>"
; They say that all sorts of business goes on in the port town.

textCamineet5:
.stringmap script "キョジュウクノ　ソトニハ　デナイホウ"
.stringmap script "ガ　ミノタメダ。<wait>"
; Stay inside the residential area if you know what's good for you.

textCamineet6:
.stringmap script "シニタクナカッタラ　ココニイルンダ。<wait>"
; Want to stay alive?  Then stay here!

textCamineet7:
.stringmap script "ココヲ　トオスワケニハ　イカナイ。<wait>"
; I can’t just let you pass through here!

textCamineet8:
.stringmap script "ロードパスノ　ナイモノハ　ココヲ<line>"
.stringmap script "トオレナイ。<wait>"
; Nobody gets through here without a 'Roadpass'.

textCamineet9:
.stringmap script "トオッテ　ヨシ。<wait>"
; Okay, you may pass.

textParolit1:
.stringmap script "ココハ　パロリト　キョジュウクヨ。<wait>"
; This is Parolit residential district.

textParolit2:
.stringmap script "モリノナカハ　トクニ<line>"
.stringmap script "キヲツケタホウガイイヨ。<wait>"
; When you're in the forest, you need to be especially cautious.

textParolit3:
.stringmap script "キョジュウクノ　ミナミノ　ドウクツニ"
.stringmap script "メデューサ　トイウ　マモノガ<wait more>"
textParolit3a:
.stringmap script "ヨミガエッタトイウ。スガタヲ<line>"
.stringmap script "ミタモノハ　イシニ　サレルソウダ。<wait>"
; I hear that the monster Medusa has returned to the cave South of the city. They say if you look at it, you'll turn to stone!

textParolit4:
.stringmap script "ヒガシヘ　イクト　シオン　トイウ<line>"
.stringmap script "ミナトマチガ　アルラシイ。<wait>"
; If you travel East, you will reach the port town of Shion.

textParolit5:
.stringmap script "スペースポートカラ　モタビアセイノ<line>"
.stringmap script "パセオ　マデ　イケルヨ。<wait>"
; You can travel to Paseo, on the planet Motavia, from the spaceport.

textParolit6:
.stringmap script "パロリトノ　ニシニアル　ガシコノモリ"
.stringmap script "ヘハ　チカツウロガ　アルラシイ。<wait>"
; I hear you can get to the Gothic Forest -- which is West of Parolit -- through an underground passageway.

textShion1:
.stringmap script "タイロンナラ　メデューサヲ　タオシニ"
.stringmap script "イッタヨ。　ヤツハ　コトバヲ　ハナス<wait more>"
textShion1a:
.stringmap script "ドウブツヲ　ツレテ　イタナア。<line>"
.stringmap script "ソノ　ドウブツハ　クビニ<wait more>"
textShion1b:
.stringmap script "クスリビンヲ　ブラサゲテイタガ<line>"
.stringmap script "ナニカノ　ヤクニ　タツノカネエ。<wait>"
; Tairon? He went to slay Medusa! That guy, he was with a TALKING ANIMAL! And the animal -- it had a bottle of medicine around it's neck. I wonder if it has any special purpose?

textShion1c:
.stringmap script "ラシーク　ヲ　タオシニイクンダッテ<line>"
.stringmap script "ナ。　ガンバレヨ。<wait>"
; You’re on a quest to defeat LaShiec, huh? Well, good luck!

textShion2:
.stringmap script "コノマエ　メデューサノ　ドウクツデ<line>"
.stringmap script "シャベル　ドウブツヲ　ヒロッタンダ。<wait more>"
textShion2a:
.stringmap script "パセオノ　ショウニンニ　タカク　ウリ"
.stringmap script "ツケテヤッタヨ。ヘッヘッヘ。<wait>"
; I found a talking animal in Medusa’s Cave earlier, see? Then I sold it off to a trader in Paseo and made a bundle! Heh, heh, heh!

textShion2b:
.stringmap script "サイキンハ　フケイキダネ。ドコカニ<line>"
.stringmap script "イイ　モウケバナシハ　ナイモノカネ。<wait>"
; Times have been rough lately, don’t you think? I wonder if there’s anywhere I can go to make money.

textShion3:
.stringmap script "シオンノ　ミナミノ　ハントウニハ<line>"
.stringmap script "イアラト　ヨバレル　ドウクツガアル。<wait>"
; On the peninsula South of Shion, you will find Iala Cave.

textShion4:
.stringmap script "ココハ　ミナトマチ　シオン。ムカシハ"
.stringmap script "ボウエキデ　ニギワッタモノダ。<wait>"
; This is the port town of Shion. This place used to be busy with trade.

textShion5:
.stringmap script "エピトイウ　マヨイノモリハ<line>"
.stringmap script "コンパスガナイト　トオレナイヨ。<wait>"
; The Eppi Woods are confusing. You need a ‘Compass’ just to pass through them.

textShion6:
.stringmap script "マホウノ　カカッタドアハ　マジックヲ"
.stringmap script "ツカワナイト　ヒラキマセン。<wait>"
; Magically-sealed doors can be opened only with magic.

textShion7:
.stringmap script "コノマチカラ　キタヘイクト　バヤ<line>"
.stringmap script "マーレ　トイウ　オカガ　アリマス。<wait more>"
.stringmap script "デモワレワレハ　ソノオカヘ<line>"
.stringmap script "チカヅクコトガ　デキマセン。<wait>"
; If you go North from this town you will reach the hill of Baya Mahrey. However, we aren’t able to get near to it.

textShion8:
.stringmap script "バヤマーレノ　キタノ　カイガンニ<line>"
.stringmap script "ナウラトイウ　ドウクツガ　アリマス。<wait>"
; On the beach North of Baya Mahrey, you will find Naula Cave.

textEppi1:
.stringmap script "モタビアノ　ソウトクハ　モシカシタラ"
.stringmap script "ミカタニ　ナッテクレルカモシレナイ。<wait>"
; I wonder if Motabia’s Governor-general might aid you in your quest.

textEppi2:
.stringmap script "モタビアニハ　スゴイ　エスパーガ<line>"
.stringmap script "イルラシイヨ。<wait>"
; On Motabia live the great ‘Espers’.

textEppi3:
.stringmap script "ガシコノモリニハ　ソノムカシ　ルベノ"
.stringmap script "ハカセノ　ケンキュウジョガ　アッタ。<wait>"
; A doctor named ‘Luveno’ used to have a laboratory in Gothic Forest.

textEppi4:
.stringmap script "エピノムラヘ　ヨウコソ。<wait>"
; Welcome to Eppi Village!

textEppi5:
.stringmap script "ソナタハ　ダンジョンキーノ　アリカヲ"
.stringmap script "サガシテ　イルノカナ。<end>"
; Are you by any chance searching for the ‘Dungeon Key’?

textEppi6:
.stringmap script "ダンジョンキーハ　カミニート<line>"
.stringmap script "キョジュウクノ　ハズレニアル<wait more>"
textEppi6a:
.stringmap script "ソウコノナカニ　ワシガ　コッソリ<line>"
.stringmap script "カクシテオイタゾヨ。<wait>"
; I hid the ‘Dungeon Key’ in a secret place, inside the warehouse located on the outskirts of Camineet residential area.

textEppi7:
.stringmap script "セカイデ　イチバン　カタクテ　ツヨ"
.stringmap script "イブッシツヲ　シッテイルカ。<end>"
; Do you know what the hardest, strongest material in the world is?

textEppi7a:
.stringmap script "ソレハ　ラコニア　ジャ。　ソレデ<line>"
.stringmap script "デキタ　ブキハ　サイキョウナンジャ。<wait>"
; It’s ‘Laconia’! Laconian weapons are the strongest [in the solar system].

textEppi7b_NeverMind: ; Used in three places
.stringmap script "ナラバ　ヨイ。<wait>"
; I see. Never mind.

textCamineetAlgolStarSystem:
.stringmap script "アルゴル　タイヨウケイノ　ワクセイヲ"
.stringmap script "シッテイルカナ。<end>"
; Do you know the planets in the Algol Solar System?

textCamineetAlgolStarSystem_No:
.stringmap script "パルマ　モタビア　デゾリス　ノ　<number>ツ"
.stringmap script "ノ　ワクセイガアル。<wait more>"
textCamineetAlgolStarSystem_No_a:
.stringmap script "パルマハ　ミドリノホシ。モタビアハ<line>"
.stringmap script "スナノホシ。デゾリスハ　コオリノ<wait more>"
textCamineetAlgolStarSystem_No_b:
.stringmap script "ホシジャ。アルゴル　タイヨウケイニハ"
.stringmap script "キキガ　セマッテイルノジャ。<wait>"
; There are three planets: Palma, Motabia, and Dezoris.
; Palma is a planet of greenery.
; Motavia is a planet of sand.
; Dezoris is a planet of ice.
; There is a crisis drawing near to Algol...

textPalmaSpaceport1:
.stringmap script "ココハ　パルマノ　スペースポートダ。"
.stringmap script "モタビアセイノ　パセオマデ　イケル。<wait>"
; This is Palma Spaceport. You can go to Paseo, on the planet Motavia.

textPalmaSpaceport2:
.stringmap script "パセオニハ　ソウトクガ　イル。モタビ"
.stringmap script "アセイ　ゼンブヲ　オサメテイルンダ。<wait>"
; The Governor-General lives in Paseo. He rules all of Motavia.

textPalmaSpaceport3:
.stringmap script "ガシコノ　ケンキュウジョデハ　ムカシ"
.stringmap script "スペースシップヲ　ツクッテタソウダ。<wait>"
; Rumor has it that the Gothic Laboratory was once used to build spaceships. Back in the old days, ships like these were built at the laboratory in Gothic.<wait>

textPalmaSpaceport4:
.stringmap script "パスポートヲ　モッテイルカ。<end>"
; Do you have a passport?

textPalmaSpaceport5:
.stringmap script "ココデ　パスポートノ　シンセイガ<line>"
.stringmap script "デキマス。シンセイヲシマスカ。<end>"
; You can apply for a ‘passport’ here. Would you like to apply?

textPalmaSpaceport5a:
.stringmap script "イママデニ　ワルイコトヲ　シタコトガ"
.stringmap script "アリマスカ。<end>"
; Up to today, have you ever done any bad things?

textPalmaSpaceport5b:
.stringmap script "イマ　アナタハ　ナニカ　ワルイ<line>"
.stringmap script "ビョウキニ　カカッテイマスカ。<end>"
; Are you suffering from an illness right now?

textPalmaSpaceport5c:
.stringmap script "テスウリョウ　<number>メセタデス。<line>"
.stringmap script "ヨロシイデスカ。<end>"
; The fee is 100 mesetas. Is that agreeable?

textPalmaSpaceport5d:
.stringmap script "デハ　パスポートヲ　ハッコウシマス。"
.stringmap script "オウケトリクダサイ。<wait>"
; Well then, we will issue you a passport. Here you go.

textPalmaSpaceport5e:
.stringmap script "ソウデスカ。デハ　オキヲツケテ。<wait>"
; I see. Well then, take care.

textPalmaSpaceport5f:
.stringmap script "ソレハ　ヨクナイデスネ。<line>"
.stringmap script "マタ　オコシクダサイ。<wait>"
; That's too bad. Please come back some other time.

textPaseoSpaceport1:
.stringmap script "ココハ　モタビアノ<line>"
.stringmap script "パセオ　スペースポート　ダヨ。<wait>"
; This is Paseo spaceport, on the planet Motabia.

textPaseoSpaceport2:
.stringmap script "サバクノ　ナカデハ　アリジゴクガ<line>"
.stringmap script "アバレテ　イルトイウ　ウワサダヨ。<wait>"
; I’ve heard rumors that there are vicious ‘Ant-lions’ in the desert!

text8afc: ; TODO confirm location?
.stringmap script "パルマセイノ<line>"
.stringmap script "ナウラ　トイウ　ドウクツニハ<wait more>"
.stringmap script "ケーキヤガ　アルンダッテネ。<wait>"
; THERE IS A CAKE SHOP IN THE CAVE CALLED NAULA ON PALMA!

textPaseo1:
.stringmap script "モタビアノ　ソウトクハ　ジツハ<line>"
.stringmap script "ラシークト　ナカガ　ワルイラシイヨ。<wait>"
; ..Actually, the Governor-General seems to be on very bad terms with LaShiec!

textPaseo2:
.stringmap script "ソウトクニ　アウニハ　オクリモノガ<line>"
.stringmap script "イルソウヨ。<wait>"
; You need to have a gift in order to meet with the Governor-General.

textPaseo3:
.stringmap script "ソウトクハ　アマイモノガ　ダイスキ。<wait>"
; The Governor-General loves sweets.

textPaseo4:
.stringmap script "マハル　トイウ　ドウクツガ　パセオ"
.stringmap script "ノキタノ　ヤマノ　ナカニ　アリマス。<wait>"
; Maharu Cave is located in the mountains to the north of Paseo.

textPaseo5:
.stringmap script "ココハ　モタビアノ　シュト<line>"
.stringmap script "パセオ　デス。<wait>"
; This is Paseo, capital of Motabia.

textPaseo6:
.stringmap script "アリジゴクハ　ヒトノ　アシデハ<line>"
.stringmap script "トテモ　トオレナイダロウ。<wait>"
; There’s no way to pass over those ant lions on FOOT, [but...].

textPaseoTrader:
.stringmap script "メズラシイ　ドウブツガ　イルンダケド"
.stringmap script "<number>オク　メセタデ　カワナイカ。<end>"
; I gotta real rare animal here. You can have it fer a billion mesetas. Whuddayuhsay?

textPaseoTrader_Yes:
.stringmap script "アンタ　ウソツキダネ。<wait>"
; Yeah, right. You gotta be kiddin’ me!

textPaseoTrader_No:
.stringmap script "オヤ　アンタ　メズラシイ　ツボヲ<line>"
.stringmap script "モッテイルネ。<wait more>"
textPaseoTrader_No_a:
.stringmap script "ソノ　ラコニアンポット　トナラ<line>"
.stringmap script "コウカンシテモ　イイヨ。　ドウカネ。<end>"
; Say... That’s a real unusual pot you got there... ...is 'dat a ‘Laconian Pot’?! How ‘bout I give you da animal, you give me the pot? Whuddayuhsay?

textPaseoTrader_No_Yes:
.stringmap script "ソレジャ　ツレテイキナ。<line>"
.stringmap script "カワイガッテ　ヤッテクレ。<wait>"
; Alri---ght, there yuh go. Take good care uv‘im.

textPaseoGuard1:
.stringmap script "ソウトクヘノ　オクリモノヲ<line>"
.stringmap script "モッテキタカ。<end>"
; Did you bring a present for the Governor-General?

textPaseoGuard1_Yes:
.stringmap script "デハ　ソノ　ショートケーキヲ<line>"
.stringmap script "アズカッテ　オコウ。<wait>"
; Well then, I’ll look after this ‘Shortcake’.

textPaseoGuard1_Yes_NoShortcake:
.stringmap script "オクリモノニ　ナルヨウナ　モノヲ<line>"
.stringmap script "モッテナイジャナイカ。<wait>"
; That is NOT a suitable gift.

textPaseoGuard1_No:
.stringmap script "サッサト　カエレ。<wait>"
; Leave at once!

textGovernorGeneral1:
.stringmap script "ワタシガ　コノホシノ　ソウトクダ。<line>"
.stringmap script "ラシークヲ　タオシニ　イクソウダナ。<wait more>"
textGovernorGeneral1a:
.stringmap script "ソノ　ユウキヲ　ホメテヤル。マハルノ"
.stringmap script "ドウクツニ　ルツ　トイウ　エスパーガ<wait more>"
textGovernorGeneral1b:
.stringmap script "イル。　ワタシノ　テガミヲ　モッテ<line>"
.stringmap script "アイニ　ユクガヨイ。<wait more>"
textGovernorGeneral1c:
.stringmap script "ラシークヲ　タオシテ　キット　ココヘ"
.stringmap script "モドッテクルコトヲ　シンジテイルゾ。<wait>"
; I am the Governor-General of this planet. I understand you are on a quest to defeat LaShiec. I commend you for your courage. In Maharu Cave you will find an Esper named Lutz (pronounced 'roots'). Please take this letter to him. I am absolutely certain that you will defeat LaShiec and return here.

textMahalCave_NoLutz:
.stringmap script "ルツハ　パセオノ　ソウトクノ<line>"
.stringmap script "メイレイナラバ　キクカモシレナイ。<wait>"
; Since the orders are from the Governor-General, Lutz will probably listen.

textMahalCave_Lutz_NoLetter:
.stringmap script "アナタガタハ　ダレデスカ。　ワタシハ"
.stringmap script "イマ　シュギョウチュウデス。<wait more>"
textMahalCave_Lutz_NoLetter_a:
.stringmap script "ジャマヲ　シナイデ　クダサイ。<wait>"
; Who are you? I'm in the middle of training right now. Please don’t interrupt.

textMahalCave_WithLutz:
.stringmap script "ヤッホー。<wait>"
; Yahoo!

textPaseoPassageGuard1:
.stringmap script "グウグウ。<wait>"
; zzz... zzz...

textGuestHouse1:
.stringmap script "ドウゾ　ヤスンデ　イッテネ。<wait>"
; Please rest before you go.

textGuestHouse1a:
.stringmap script "ドウカ　ブジニ　モドッテキテネ。<line>"
.stringmap script "イノッテルワ。<wait>"
; Good luck out there. You’re going to need it.<wait>

textGothic1:
.stringmap script "アンタ　オレニ　ペロリーメイトヲ<line>"
.stringmap script "ヒトツ　メグンデ　クレナイカ。<end>"
; Hey, you mind if I bum a ‘Perolimate’?

textGothic1_Yes:
.stringmap script "アリガトウ。ココハ　ムカシ　ルベノ<line>"
.stringmap script "トイウ　カガクシャノ　ケンキュウジョ<wait more>"
textGothic1_Yes_a:
.stringmap script "ダッタ。ダケド　ルベノハ　クルッテ<line>"
.stringmap script "イルトイウ　リユウデ　コノムラノ<wait more>"
textGothic1_Yes_b:
.stringmap script "ミナミニアル　トリアダ　トイウ<line>"
.stringmap script "ロウゴクニ　トジコメラレタンダ。<wait>"
; Thanks. This place used to be the lab of a scientist named ‘Luveno’. But he turned crazy, see, and got locked up in Toriada, the prison to the South of this village.

textGothic1_No:
.stringmap script "アンタニ　ハナスコトハ　ナイ。<line>"
.stringmap script "ドコカヘ　キエナ。<wait>"
; I ain’t talking to you, then. Get the hell away from me.

textGothic2_Yes:
.stringmap script "ガシコノモリカラ　ヤマヘ　ツウジル<line>"
.stringmap script "イッポンミチノ　オクニアル　トウニハ<wait more>"
textGothic2_Yes_a:
.stringmap script "チカヅクナ。ソコニハ　スガタヲ　ミタ"
.stringmap script "ダケデ　カラダガ　イシニナッテシマウ<wait more>"
textGothic2_Yes_b:
.stringmap script "トイウ　オソロシイ　マモノガ　スン"
.stringmap script "デイルラシイ。<wait>"
; In the heart of the mountains, there's a tower that can be reached by one of the roads leading out of Gothic. Inside the tower, they say, there's a freaky monster that, if you just LOOK at it, will turn yuh tuh stone!

textDrLuveno1:
.stringmap script "オオ。オソカッタノウ。<line>"
.stringmap script "サッソクジャガ　ワシノ　ジョシュヲ<wait more>"
textDrLuveno1a:
.stringmap script "ツレテキテクレ。チカツウロノ　ナカニ"
.stringmap script "カクレテオルハズジャ。<wait more>"
.stringmap script "ホントニ　アイツハ　ハズカシガリヤ"
.stringmap script "デコマッタモノジャ。<wait>"
; Ahh, you’re late! Quickly! Do me a favor and bring my assistant back here. He’s probably hiding in that underground tunnel. It really irritates me shy a person he is.

textPalmaSpaceport4_No:
.stringmap script "フザケルナ。<wait>"
; DON'T BE A FOOL!

textDrLuveno1b:
.stringmap script "タリナイノウ。　ワルイガ　オカネヲ<line>"
.stringmap script "アツメテキテクレンカ。<wait>"
; You don’t have enough? I’m sorry, but must get some more money.

textDrLuveno1c:
.stringmap script "ヨロコベ　ツイニ　ウチュウセン<line>"
.stringmap script "ルベノゴウガ　デキアガッタゾ。<wait>"
; At last, the spaceship is finished!  I’m pleased to present to you, the ‘Luveno’!

textDrLuvenoPrison_3_No:
.stringmap script "イウトオリニ　シナイナラ<line>"
.stringmap script "ヒキウケルワケニハ　イカナイ。<wait>"
; Well, if you won’t promise, then I’m afraid I can’t help you.

textDrLuveno1e:
.stringmap script "シカシ　オマエニハ　ルベノゴウハ<line>"
.stringmap script "ソウジュウデキン。<wait>"
; But you won’t be able to pilot the spaceship yourself.

textDrLuveno2:
.stringmap script "ルベノゴウノ　チョウシハ　ドウジャ。"
.stringmap script "ダイジニ　ツカッテ　オクレ。<wait>"
; How’s the ‘Luveno’ holding up? Please be careful with it.

textDrLuveno1g:
.stringmap script "ソレハ　ザンネンジャ。<line>"
.stringmap script "オマエノ　タビモ　ココマデカノウ。<wait>"
; What a shame. So your journey ends here, I suppose...

text8fd1: ; TODO where is this?
.stringmap script "イマ　イソガシインダ。<line>"
.stringmap script "ジャマシナイデクレ。<wait>"
; I’m busy right now, so please don’t interrupt.

textDrLuvenoPrison_1:
.stringmap script "ワシハ　ルベノジャ。タスケニ<line>"
.stringmap script "キタノナラ　ヨケイナコトジャ。<wait more>"
.stringmap script "カエルガイイ。<wait>"
; I’m Luveno. You came here to rescue me? That’s not really necessary. You should go home.

textDrLuvenoPrison_2:
.stringmap script "ナニ。ウチュウセンヲ　ツクレジャト。バカモ　ヤスミ　ヤスミ　イエ。<wait more>"
.stringmap script "ワシガ　ソンナコトヲ　ヒキウケルト<line>"
.stringmap script "オモウノカ。<wait>"
; What? Did you say 'build a spaceship?' [BAKA MO YASUMIYASUMI IE.]  Do you think I want to be responsible for something like that?

textDrLuvenoPrison_3:
.stringmap script "ウーム。コリナイヤツジャ。<line>"
.stringmap script "シカタガナイ。<wait more>"
.stringmap script "ワシノ　イウトオリニ　シテモラウガ<line>"
.stringmap script "ソレデモヨイカ。<end>"
; Hmmm... Didn’t I tell you to-- Aah, I give up! You must promise to do whatever I ask. Agreed?

textDrLuvenoPrison_3_Yes:
.stringmap script "ヨシ。ソレデハ　ヒトアシ　サキニ<line>"
.stringmap script "ガシコノ　ムラヘ　イッテ<wait more>"
.stringmap script "ジュンビスルカラ　アトカラ　コイ。<line>"
.stringmap script "ワシノコトナラ　シンパイムヨウジャ。<wait>"

textTriada1:
.stringmap script "ロードパスヲ　モッテイルカ。<end>"
; Do you have a Roadpass?

textTriada1_No:
.stringmap script "タイシタ　ドキョウダ。<line>"
.stringmap script "シンデモラウゾ。<wait>"
; You are very brave. Please allow me to kill you...

textTriada2_Yes:
.stringmap script "クモノ　カイブツハ　ホントウハ<line>"
.stringmap script "カシコインダヨ。<wait>"
; Thanks. Y’know, no matter what people say, spiders are actually very wise creatures.

textTriada3:
.stringmap script "ハプスビー　トイウ<line>"
.stringmap script "ロボットヲ　シッテルカイ。<end>"
; Do you know of a robot called ‘Hapsby’?

textTriada4:
.stringmap script "ヤマノ　ムコウハ　カザンノ　フンカデ"
.stringmap script "ヨウガンイケガ　デキテイルソウダヨ。<wait>"
; I hear that on the other side of the mountains there's a whole bunch of lava because of the volcanic eruptions.

textTriada5:
.stringmap script "ガシコノ　ヤマオクニアル　トウハ<line>"
.stringmap script "メデューサノトウト　ヨバレテイル。<wait>"
; The tower nestled in the Gothic Mountains is called ‘Medusa’s Tower.’

textTriada6:
.stringmap script "ヤア。ヒトニ　アウノハ<line>"
.stringmap script "ヒサシブリダ。オハナシシヨウヨ。<end>"
; Whassup? I haven’t seen any people in a long time! Let’s talk!

textTriada7:
.stringmap script "ポリメテラール　トイウ　クスリハ<wait more>"
.stringmap script "ラコニア　イガイノ　ブッシツハ<line>"
.stringmap script "スベテ　トカスソウダヨ。<wait>"
; There’s this chemical called ‘Polymeteral’ that they say will dissolve any material except laconia.

text91a6: ; TODO where is this?
.stringmap script "エーッ。　ルベノハカセガ　カエッテ<line>"
.stringmap script "キタノカイ。<wait more>"
.stringmap script "マタ　ウチュウセンヲ　ツクルノカ。<line>"
.stringmap script "ショウガネエヤ。スグイクヨ。<wait>"
; Huh? You say Dr. Luveno is back... and he’s going to build a spaceship?! Well, I guess I have no choice [but to help]. I’ll go there right away.

textMedusasTower1:
.stringmap script "オクノ　ヘヤヘ　ハイッテ　イキテ<line>"
.stringmap script "カエッタモノハ　イナイ。ヒッヒッヒ。<wait>"
; NO MAN THAT GOES INTO THE ROOM IN THE FAR CORNER HAS EVER COME OUT ALIVE! AHA-HA-HA!

textTylonCave1:
.stringmap script "イシニ　サレテシマッタ　ヒトラシイ。"
.stringmap script "モトニ　モドレルノダロウカ。<wait>"
; It seems that something turned this person into stone! Maybe he can be returned to normal...

textMedusasTower2:
.stringmap script "モハヤ　カクゴハ　デキテオル<line>"
.stringmap script "ジャロウナ。　フッフッフ。<wait>"
; YOU WILL SOON FIND OUT THE TRUTH!

textMedusasTower3:
.stringmap script "イキドマリジャ。　モドリナサイ。<line>"
.stringmap script "カエルナラ　イマノウチダ。<wait>"
; HALT! GO BACK! YOUR LAST CHANCE!

textMedusasTower4:
.stringmap script "オオ。ナント　ユウカンナ<line>"
.stringmap script "ワカモノヨ。　ワナニ　キヲツケテナ。<wait>"
; Oh, what a brave young lady you are! Beware of traps.

textBartevo1:
.stringmap script "バルテボハ　オレノ　ナワバリダ。<line>"
.stringmap script "アラスンジャナイゾ。<wait>"
; Bartevo is my territory. Don’t be screwin’ around!

textDrLuveno1f:
.stringmap script "ハプスビー　トイウ　ロボットヲ<line>"
.stringmap script "サガシテクルンジャ。<wait more>"
.stringmap script "アノ　ロボットナラ　ウチュウセンヲ<line>"
.stringmap script "ソウジュウ　デキルハズジャ。<wait>"
; YOU MUST FIND A ROBOT NAMED HAPSBY. HE CAN FLY A SPACESHIP.

textBartevo2:
.stringmap script "コノ　スクラップノナカニ　セイノウノイ"
.stringmap script "イ　ロボットガ　ステラレテイル<wait more>"
.stringmap script "トイウハナシダケド　ホントウカネー。<wait>"
; I heard that a high-performance robot got dumped inside one of these scrap piles. I wonder if it’s true?

textBartevoCave:
.stringmap script "アビオンノ　ムラニ　ポリメテラール<line>"
.stringmap script "トイウ　クスリガ　ウッテイルラシイ。<wait>"
; The drug store in Abion sells Polymeteral, I hear.

textLore1:
.stringmap script "ココハ　ロアー　トイウ　ムラデス。<line>"
.stringmap script "ラシークノセイデ　サビレテシマッタ。<wait>"
; This is the Village of Lore. Thanks to LaShiec, it’s become a wasteland.

textLore2:
.stringmap script "カーバンクルアイ　トイウ　ホウセキヲ"
.stringmap script "シッテイマスカ。<wait more>"
.stringmap script "カスバノ　ドラゴンガ　モッテイル<line>"
.stringmap script "トイウ　ウワサデス。<wait>"
; Do you know of a jewel called the ‘Carbuncle Eye’? Rumor has it that it’s being held by the Casba Dragon.

textLore3:
.stringmap script "コノシマノ　ニシノ　ハズレニハ<line>"
.stringmap script "アビオン　トイウ　ムラガ　アリマス。<wait>"
; On the West end of this island, there is a village called Abion.

textLore4:
.stringmap script "ラエルマツリー　トイウ　キヲ<line>"
.stringmap script "シッテイルカ。<end>"
; Do you know about the ‘Laerma Tree?'

textLore4_No:
.stringmap script "デゾリスセイノ　アルチプラノ<line>"
.stringmap script "トヨバレル　コウゲンニ<wait more>"
.stringmap script "オイシゲッテイルトカ。<wait>"
; I hear the Altiplano Plateau on Dezoris is totally covered by them.

textLore5:
.stringmap script "エッ　ラシークヲ　タオシニ　イクノ。"
.stringmap script "スゴイネエ。<wait>"
; Huh? You’re going to defeat LaShiec? Awesome!

textUnused1:
; Index $011a, seems to be unused.
.stringmap script "ウワサダケド　アル　クリスタルハ<line>"
.stringmap script "アシキ　マホウヲ　フウジルトカ。<wait>"
; Now this is just a rumor, but supposedly there are crystals that protect against evil magic.

textAvion1:
.stringmap script "コノムラハ　アビオン　トイウノヨ。<wait>"
; This village is called Abion.

textAvion2:
.stringmap script "ラシークノ　マノテハ　コノムラニモ<line>"
.stringmap script "ノビテキタ。　タスケテクレ。<wait>"
; The evil hand of LaShiec has extended to this village as well! Please help us!

textAvion3:
.stringmap script "コノムラニ　カワッタ　オトコガ<line>"
.stringmap script "ヒッコシテキタヨ。ドウブツジッケンヲ<wait more>"
textAvion3a:
.stringmap script "ヤッテルラシイガ　キミガワルイナア。"
.stringmap script "ツボ　ミタイナモノヲ　モッテタヨ。<wait>"
; Some weird freak just moved to this village, and he was carrying a jar or something. It seems he’s been doing experiments on animals. I gotta bad feeling about that guy.

textTriada3_No:
.stringmap script "ラコニアデ　デキタ　ロボットダヨ。<wait more>"
.stringmap script "デモ　スクラップニ　サレテ<line>"
.stringmap script "ステラレチマッタラシイヨ。<wait>"
; It’s a robot made out of laconia! But it seems to have been dumped into a scrap heap!

textAvion4:
.stringmap script "ワタシ　ウチュウノ　タビガ<line>"
.stringmap script "シテミタイワ。<wait>"
; I want to try and travel the stars.

textAvion5:
.stringmap script "ジャコウネコ　トイウ　ドウブツハ<line>"
.stringmap script "アル　キノミヲ　タベルト<wait more>"
textAvion5a:
.stringmap script "オオキクナッテ　ソラヲ　トベルヨウニ"
.stringmap script "ナルソウダヨ。　フシギダネ。<wait>"
; They say if an animal called a ‘Musk Cat’ eats a certain type of berry, it’ll grow large, and become able to fly! Weird, huh?

textHapsby1:
.stringmap script "ボクハ　ハプスビー。<wait more>"
.stringmap script "ミツケテクレテ　アリガトウ。　ルベノ"
.stringmap script "ゴウノ　ソウジュウハ　マカセテネ。<wait>"
; I am Hapsby. Thanks for getting me out of that scrap heap. Let me pilot the ‘Luveno’ for you, okay?

textUzo1:
.stringmap script "ココハ　モタビアセイノ　ウーゾ<line>"
.stringmap script "トイウ　ムラデス。<wait>"
; This is Uzo Village, on the planet Motavia.

textUzo2:
.stringmap script "アリジゴクハ　ランドマスター　トイウ"
.stringmap script "ノリモノヲ　ツカエバ　トオレマスヨ。<wait>"
; You can pass over antlions if you have a ‘LandMaster.’

textUzo3:
.stringmap script "ウーゾノ　ミナミニ　カスバ　トイウ<line>"
.stringmap script "ムラガ　アリマス。<wait>"

textUzo4:
.stringmap script "カスバノ　ドウクツニハ　ドラゴンガ<line>"
.stringmap script "スミツイタラシイデスヨ。<wait more>"
.stringmap script "ソノ　ドラゴンノ　アタマニハ<line>"
.stringmap script "ホウセキガ　ハイッテイルトカ。<wait>"
; It seems that a dragon has settled in Casba Cave! That dragon has a jewel or something embedded in its head!

textUzo5:
.stringmap script "フラードマント　トイウ　マントヲ<line>"
.stringmap script "シッテルカイ。　カルイケド<wait more>"
textUzo5a:
.stringmap script "スゴイ　ボウギョリョクガ<line>"
.stringmap script "アルソウダヨ。<wait>"
; Have you heard of the ‘Frad Cloak?' They say it’s light in weight, but has superb defensive power.

textUzo6:
.stringmap script "スーズフルート　トイウ　フエノコトヲ"
.stringmap script "シッテルカイ。<end>"
; Do you know about the ‘Soothe Flute?’

textReallyWhatABore:
.stringmap script "ソウカイ。ツマンネエノ。<wait>"

textUzo6_No:
.stringmap script "ナイショダケドサ　ボクガ　パルマセイ"
.stringmap script "ヘ　イッタトキニ　ガシコノムラノ<wait more>"
textUzo6_Noa:
.stringmap script "ハズレニ　ウメテキタンダ。ダレニモ<line>"
.stringmap script "イッチャダメダヨ。<wait>"
; Well, this is a secret, but when I went to Palma, I buried it on the outskirts of Gothic Village. Don’t tell anybody!

textScionTrader1:
.stringmap script "ダレニ　キイタカ　シラナイガ<line>"
.stringmap script "アキラメタホウガ　ミノタメダ。<wait>"
; Who the hell told you that? You’d better just forget about it if you know what’s good for you.

textScionTrader2:
.stringmap script "ダメナモノハ　ダメダ。<line>"
.stringmap script "サー　カエッタ。カエッタ。<wait>"
; Give it up, willya? Now get outta here!

textScionTrader3:
.stringmap script "シツコイヤツダ。ソンナニ　イウノナラ"
.stringmap script "シカタガナイ。ダレニモ　イウナヨ。<wait>"
; You just don't quit, do you? I give up. If you're gonna keep bugging me, then just [take it]. But don't tell anybody.

textDamoa1:
.stringmap script "ワシハ　セカイイチノ　ウラナイシ<line>"
.stringmap script "ダモアジャ。<wait more>"
textDamoa1a:
.stringmap script "ワシノ　ウラナイヲ　シンジルカ。<end>"
; I am the World’s Greatest Fortune Teller, Damoa! Do you believe in my amazing powers?

textTriada6_Yes:
.stringmap script "バルテボニハ　ボクノ　トモダチガ<line>"
.stringmap script "イルンダ。<wait more>"
.stringmap script "イマハ　ヨウガンイケノ　セイデ<line>"
.stringmap script "タイヘンダロウナア。<wait more>"
.stringmap script "アッタラ　ヨロシク　イットイテネ。<wait>"
; Y’know, I’ve got a friend in Bartevo. But those lava pools are making things real tough right now, I guess. If you see my friend, could you tell him I said ‘hi?’

textDamoa1_Yes:
.stringmap script "ヨシ。ヨシ。<wait>"
; Good. Good.

textDamoa2:
.stringmap script "オマエハ　サガシモノヲ　シテオル<line>"
.stringmap script "ジャロウ。<end>"
; I sense that you are looking for something, yes?

textDamoa1_No:
.stringmap script "ナンジャト。　　オマエハ<line>"
.stringmap script "スナオデナイ。　カエルガイイ。<wait>"
; What did you say? You are very disobedient. I think you should leave.

textDamoa3:
.stringmap script "オマエハ　アレックス　オサールヲ<line>"
.stringmap script "サガシテオルジャロウ。<end>"
; I see that you are looking for Alex Ossale, yes?

textDamoa4:
.stringmap script "ワシノ　イウコトハ　スベテ　タダシイ"
.stringmap script "ノジャ。　ワカッタカ。<end>"
; Everything I say is correct. Understand?

textDamoa4_Yes:
.stringmap script "デハ　マタクルガイイ。<wait>"
; In that case, perhaps you should come back later.

textDamoa5:
.stringmap script "ワシニ　サカラウノカ。<end>"
; Do you oppose me?

textDamoa6:
.stringmap script "ソウダロウ。オマエハ　ナカナカ<line>"
.stringmap script "ミドコロガアル。<wait more>"
textDamoa6a:
.stringmap script "ホウビニ　クリスタルヲ　ヤロウ。<wait>"
; Is that so... You show considerable promise. I shall give you this crystal as a reward.

text980d:
.stringmap script "ココヲ　バヤマーレノ　トウト<line>"
.stringmap script "シリナガラ　キタノカ。<end>"
; DO YOU COME IN FULL KNOWLEDGE OF THE TOWER OF BAYA MALAY?

text980dYes:
.stringmap script "カナラズヤ　テンノ　イカリニ<line>"
.stringmap script "フレヨウゾ。<wait>"
; YOU WILL SURELY INCUR THE WRATH OF THE HEAVENS!

text980dNo:
.stringmap script "ナラバ　ヒキカエスガヨイ。<wait>"
; GO BACK BEFORE IT IS TOO LATE.

textCasba1:
.stringmap script "ココハ　カスバ　トイウ　ムラデス。<wait>"
; This is Casba Village.

textCasba2:
.stringmap script "コノムラノ　ドウクツニ　ドラゴンガ<line>"
.stringmap script "スミツイタノ。ワタシ　コワーイ。<wait>"
; There’s a dragon living in Casba Cave! I’m so scared!

textAeroCastle1:
.stringmap script "ダンジョンノ　ナカデハ　オノレノ<line>"
.stringmap script "メヲ　シンジルデナイゾ。<wait>"
; You can't always trust your eyes in dungeons.

textCasba3:
.stringmap script "マワリヲ　キリニ　カコマレタ　ムラ<line>"
.stringmap script "ニハ　デンセツノ　タテノ　イイツタエ<wait more>"
textCasba3a:
.stringmap script "ガアル。ソノムカシ　ペルセウスガ<line>"
.stringmap script "マモノタイジニ　ツカッタトイウ。<wait>"
; The people in the village surrounded by gas tell a tale of a legendary shield. They say that a long time ago, [a man named] Perseus used that shield to confront a monster.

textCasba4:
.stringmap script "ボクガ　ミズウミノ　ニシヘ　イクト<wait more>"
.stringmap script "キリノヨウナ　オソロシイ　ドクガスガ"
.stringmap script "ヒロガッテイタンダ。<wait more>"
.stringmap script "ナントカ　シナイト<line>"
.stringmap script "トテモ　チカヨレナイヨ。<wait>"
; One time I traveled west of the lake, and a frightening, fog-like poison gas was spreading all over! Whatever you do, stay away from there!

textCasba5:
.stringmap script "フロームーバー　トイウ　ノリモノヲ<line>"
.stringmap script "シッテイルカイ。<end>"
; Do you know about the ‘FlowMover’?

textCasba5Yes:
.stringmap script "パルマセイノ　シオンノマチデ　カッタ"
.stringmap script "ンダケド　コワレチマッタミタイデ<wait more>"
textCasba5Yes_a:
.stringmap script "バルテボニ　ステチマッタヨ。<line>"
.stringmap script "モッタイナイコト　シチマッタ。<wait>"
; Well, I bought one on Palma, in the town of Shion, but it turned out to be broken, so I ditched it in Bartevo. What a waste!

textShionFoundFlowMover:
.stringmap script "フロームーバーヲ　ミツケタ。<wait more>"
.stringmap script "ハプスビーガ<line>"
.stringmap script "コワレタトコロヲ　ナオシタノデ<wait more>"
textShionFoundFlowMover_a:
.stringmap script "ツカエルヨウニ　ナッタゾ。<wait>"
; You found the ‘FlowMover’! Hapsby fixed the areas that were damaged, so you can use it now!

textCasba5No:
.stringmap script "アレハ　ベンリダヨ。　ミズノウエヲ<line>"
.stringmap script "スイスイ　イケルンダ。<wait>"
; With a FlowMover, you can glide smoothly across the the top of the water. They can really come in handy!

textDrasgo1:
.stringmap script "ココハ　ドラスゴー。　ウミノウエノ<line>"
.stringmap script "チイサナ　マチデス。<wait>"
; This is Drasgo, a tiny town on the sea.

textDrasgo2:
.stringmap script "イマ　ウミノ　ミチハ　トザサレテ<line>"
.stringmap script "フネサエ　ツカエナイノニ<wait more>"
textDrasgo2a:
.stringmap script "ヨクモマア　コノマチヘ<line>"
.stringmap script "タドリツキマシタネ。<wait>"
; Amazing! You managed to make it here even though they shut down the sea routes and we are no longer allowed to use boats!

textDrasgo3:
.stringmap script "アビオンノ　トウニハ　マリョクヲ<line>"
.stringmap script "フウジル　ケンガ　アルソウデス。<wait>"
; I hear that there's an enchanted sword in Abion Tower.

textDrasgo4:
.stringmap script "ワタシハ　ムカシ　ソラニ　ウカブ<line>"
.stringmap script "オオキナ　イワヲ　ミタコトガアル。<wait>"
; I once saw a huge floating rock in the sky!

textChokoOneesan:
.stringmap script "チョウコオネーサンデース。<wait more>"
textChokoOneesan_a:
.stringmap script "ガンバッテ　ボウケンヲ　ツヅケテネ。<wait>"
; It's me, Choko Oneesan! Be brave and strong as you continue your quest!

textDrasgoCave1:
.stringmap script "ワタシハ　ドクガスカラ　ミヲ　マモル"
.stringmap script "ガスクリアー　トイウ　ソウチガ<wait more>"
textDrasgoCave1a:
.stringmap script "ココニ　ウッテイルト　キイタノダガ<line>"
.stringmap script "ミセガ　ドコニアルノカ　ワカラナイ。<wait more>"
.stringmap script "コマッタ。コマッタ。<wait>"
; I heard that a store in this city sells an apparatus called a ‘GasClear’, which protects the body against poison gas. The only thing is, I can’t find the damn store! Sheesh!

textDrasgoCave2:
.stringmap script "ココハ　アイテムショップデス。<line>"
.stringmap script "ドンナ　ゴヨウデショウ。<wait more>"
textDrasgoCave2a:
.stringmap script "ナーンチャッテ。カラカッテゴメン。<line>"
.stringmap script "カンベンシテチョ。<wait>"
; This is an item shop. What can I do for you? Haah haah! Sorry, I’m just kidding! Please forgive me.

textDrasgoCave3:
.stringmap script "コンナトコニ　オミセガ　アッテ<line>"
.stringmap script "ビックリ　シタデショ。<wait more>"
textDrasgoCave3a:
.stringmap script "ガスクリアー　<number>メセタデス。<line>"
.stringmap script "ヤスイデショ。　カイマスカ。<end>"
; You must be pretty shocked to see a store in a place like this, huh? ‘GasClears’ are 1000 mesetas. Pretty cheap, no? You wanna buy one?

textDrasgoCave3Yes:
.stringmap script "アリガトウ。マタキテネ。<wait>"
; Thank you. Please come again.

textDrasgoCave3Yes_NoMoney:
.stringmap script "オカネガナイノー。　シケテンナー。"
; Huh? You don’t have enough money?

textDrasgoCave3No:
.stringmap script "オヤ　モッタイナイ。<line>"
.stringmap script "モウ　ウッテアゲナイヨ。<wait>"
; Hey, what the hell?! I’m not selling you ANYTHING!

textSpaceportClosed:
.stringmap script "スペースポートハ　ヘイサスル。<wait>"
; THE SPACEPORT IS CLOSED.

textPassportConfiscated:
.stringmap script "パスポートヲ　ボッシュウスルゾ。<wait>"
; WE ARE CONFISCATING YOUR PASSPORT.

textSkray1:
.stringmap script "ココハ　デゾリスセイノ　スクレ。<line>"
.stringmap script "ソトハ　サムカッタデショウ。<wait>"
; This is Skray, on the planet Dezoris. Pretty cold outside, wasn’t it?

textSkray2:
.stringmap script "パルマセイカラノ　イミンハ　ホトンド"
.stringmap script "コノマチニ　スンデイマス。<wait>"
; Nearly all of the Palman immigrants live in this town.

textSkray3:
.stringmap script "ワタシ　コノホシノコトハ<line>"
.stringmap script "ヨクシラナイケド　キタノ　ヤマオクニ<wait more>"
textSkray3a:
.stringmap script "コノホシノ　ジュウミン　デゾリアンノ"
.stringmap script "ムラガ　アルソウヨ。<wait>"
; I don’t know much about this planet, but I do know that there are some native Dezorians living in a village inside the the northern mountains.

textSkray4:
.stringmap script "ナニ　ラシークヲ　タオスンダト。<line>"
.stringmap script "ソレナラバ　ラコニアデ　デキタ<wait more>"
textSkray4a:
.stringmap script "ソード　アクス　シールド　アーマー<line>"
.stringmap script "ヲ　ソロエナサレ。<wait more>"
textSkray4b:
.stringmap script "コレラノ　ブキハ　サイキョウノ<line>"
.stringmap script "チカラヲ　ハッキスルダロウ。<wait more>"
textSkray4c:
.stringmap script "ブジヲ　イノッテイル。<wait>"
; What? ‘Overthrow LaShiec?’ If you really are going to do that, you must gather all of the Laconian weapons: Sword, Axe, Shield, and Armor. These weapons are more powerful than any others. I’ll be praying for your safety.

textSkray5:
.stringmap script "ラコニアデ　デキタ　ブキハ　セイナル"
.stringmap script "チカラヲ　ヒメテイルンダ。<wait more>"
textSkray5a:
.stringmap script "ラシークハ　ソレヲ　キラッテ<line>"
.stringmap script "アルゴル　タイヨウケイノ　ワクセイノ<wait more>"
textSkray5b:
.stringmap script "アチコチニ　カクシテシマッタトイウ。<wait>"
; Weapons made from laconia conceal holy powers, y’know. I heard that LaShiec despises them, so he hid them here and there throughout the planets of Algol.

textSkray6:
.stringmap script "デゾリスセイハ　コオリノホシデス。<wait>"
; Planet Dezoris is made of ice.

textSkray7:
.stringmap script "コオリノ　ヤマノナカニハ<line>"
.stringmap script "クズレヤスイトコロモ　アルヨウデス。<wait>"
; There are places inside the ice mountains that can be easily broken.

textSkray8:
.stringmap script "アルチプラノコウゲンハ　マワリヲ<line>"
.stringmap script "コオリノ　ヤマニ　カコマレテイマス。<wait>"
; The area around the Altiplano Plateau is encircled by mountains of ice.

textSkray9:
.stringmap script "コノホシハ　ヒャクネンニ　イチド<line>"
.stringmap script "ニッショクガ　アリマス。<wait more>"
textSkray9a:
.stringmap script "ソノトキニ　トモサレタ　ホノオハ<line>"
.stringmap script "イクリプストーチト　ヨバレ<wait more>"
textSkray9b:
.stringmap script "シンセイナル　ホノオトシテ<line>"
.stringmap script "デゾリアンニ　マツラレテイルノデス。<wait>"
; This planet has a solar eclipse once every hundred years. There is a flame lit at this time called an ‘Eclipse Torch’. It is regarded by the Dezorians as sacred.

textSkray10:
.stringmap script "グアランノ　シタイオキバノ<line>"
.stringmap script "シニンガ　ヨミガエッタソウダ。<wait more>"
textSkray10a:
.stringmap script "オソロシヤ。<wait>"
; I heard that all the dead people in the Guaran Morgue have come back to life! How creepy!

textHonestDezorian1:
.stringmap script "トナリノ　ブラクハ<line>"
.stringmap script "ウソツキバカリダ。キヲツケナヨ。<wait>"
; Those guys in the village next to us are all a bunch of liars. Be careful, eh.

textHonestDezorian2:
.stringmap script "コノムラノ　キタノ　ヤマノムコウニ<line>"
.stringmap script "コロナノトウガ　アルズラ。<wait>"
; Corona Tower lies on the other side of the mountains to the North of this village, eh.

textHonestDezorian3:
.stringmap script "コロナノトウノ　ニシニハ　デゾリスノ"
.stringmap script "ドウクツガ　アルズラ。<wait more>"
textHonestDezorian3a:
.stringmap script "ワシラノ　ナカマガ　イルズラ。<line>"
.stringmap script "ヨロシクズラ。<wait>"
; To the West of Corona Tower is Dezoris Cave, eh. Please send my regards to our comrades there, eh.

textHonestDezorian4:
.stringmap script "ラエルマツリーニハ　ラエルマベリー<line>"
.stringmap script "トイウ　キノミガ　ナルズラヨ。<wait more>"
textHonestDezorian4a:
.stringmap script "アノ　キノミハ　オイシイカラ<line>"
.stringmap script "ワシラノ　ショクリョウニ　シタイケド<wait more>"
textHonestDezorian4b:
.stringmap script "ラコニアノ　ツボニ　イレナイト<line>"
.stringmap script "ヒカラビテシマウズラヨ。<wait>"
; Laerma trees make berries called ‘Laerma Berries’, eh. Those berries are real tasty, eh. We wanna use them for food, eh, but if we don’t put them into a ‘Laconian Pot’, they just get all shriveled up, eh.

textHonestDezorian5:
.stringmap script "エアロプリズム　トイウノヲ<line>"
.stringmap script "シッテルズラカ。<end>"
; Do you know about the ‘Aeroprism’?

textHonestDezorian5_No:
.stringmap script "コノヨト　チガウ　セカイガ<line>"
.stringmap script "ミエルソウズラヨ。<wait>"
; I hear you can use it to look at other worlds, eh.

textHonestDezorian5_Yes:
.stringmap script "イチド　ミテミタイモノズラヨ。<wait>"
; I’d really like to see it at least once, eh.

textHonestDezorian6:
.stringmap script "コノブラクノ　ミンナハ　パルマノ<line>"
.stringmap script "ヒトビトヲ　キラッテルズラ。<wait>"
; All the people in this village hate those Palmans, eh.

textDishonestDezorian1:
.stringmap script "コロナノトウニハ　イノチノイズミガ<line>"
.stringmap script "アルンダス。<wait>"
; There's a Life Spring/Fountain of Youth in Corona Tower, y’know.

textDishonestDezorian2:
.stringmap script "デゾリスノ　ドウクツノ　チカ<line>"
.stringmap script "<number>カイデ　ワープデキルンダスヨ。<wait>"
; There's a warp on the 10th underground floor of Dezoris cave, y’know.

textDishonestDezorian3:
.stringmap script "ラエルマベリーハ　アオイイロヲシタ<line>"
.stringmap script "キノミデ　センリョウニ　ツカウダス。<wait>"
; Laerma Berries are colored blue. We use them as a dye, y’know.

textDishonestDezorian4:
.stringmap script "ラエルマツリーノ　マエデ　クリスタル"
.stringmap script "ヲ　ツカウト　ミガ　ナルンダス。<wait>"
; If you use a crystal in front of the Laerma Tree, berries will grow, y’know.

`textDishonestDezorian5:
.stringmap script "コノブラクハ　パルマノ　ヒトビトヲ<line>"
.stringmap script "カンゲイシマス。<wait>"
; This village welcomes Palmans.

textSopia1:
.stringmap script "コノムラハ　ソピアト　イイマス。<wait more>"
.stringmap script "ドクガスノ　ナカヲ<line>"
.stringmap script "ヨウコソ　コラレマシタ。<wait>"
; This village is called Sopia. I’m glad that you were able to brave your way through the poison gas.

textSopia2:
.stringmap script "ワタシハ　コノムラノ　ソンチョウ<line>"
.stringmap script "デス。コノ　キリノセイデ　ホカノ<wait more>"
textSopia2a:
.stringmap script "マチヤ　ムラカラ　トザサレタ　ソピア"
.stringmap script "ハ　トテモ　マズシイノデス。<wait more>"
textSopia2b:
.stringmap script "ドウカ　<number>メセタ　キフシテ<line>"
.stringmap script "クダサイ。<end>"
; I am the chief of this village. Due to the gas, Sopia is cut off from other towns and villages, and is therefore very poor. Could you by any chance offer a contribution of 400 mesetas?

textSopia2_No:
.stringmap script "ソウデスカ。ザンネンデス。ウウッ。<wait>"
; I see. What a pity. Hmmm...

textSopia2_Yes_NoMoney:
.stringmap script "オタガイニ　マズシイノデスネ。<line>"
.stringmap script "サビシイ　ヨノナカデス。<wait>"
; You are poor as well, eh? What a sad world in which we live.

textSopia2_Yes:
.stringmap script "アリガトウ。<line>"
.stringmap script "ワレワレノ　イイツタエニヨレバ<wait more>"
textSopia2_Yes_a:
.stringmap script "ペルセウスガ　メデューサヲ<line>"
.stringmap script "タオストキニ　ツカッタ　タテガ<wait more>"
textSopia2_Yes_b:
.stringmap script "ミズウミニアル　シマノ　サボテンノ<line>"
.stringmap script "シタニ　ウメテアルソウデス。<wait>"
; Thank you. According to local legend, the shield that Perseus used when he defeated Medusa is buried under a cactus on the island in the middle of the lake.

textGamerMiki:
.stringmap script "アタシ　ゲーマーノ　ミキチャンヨ。<line>"
.stringmap script "アナタ　マスターシステム　カッタ。<end>"
; I'm Gamer Miki-chan! Do you own a Master System?

textGamerMiki_Yes:
.stringmap script "マア　アタシトオンナジ　ゲーマーネ。"
.stringmap script "ヤッパ　エフエムオンゲンハ　グーネ。<wait>"
; Yay! Isn’t the FM sound amazing?!<wait>

textGamerMiki_No:
.stringmap script "ヤッダー　アナタ　ハヤク　カッテ<line>"
.stringmap script "ラッシャイヨー　モー　プン　プン。<wait>"
; Aawww! That’s no good! Hurry up and buy one! Hmph!

textSopia3:
.stringmap script "ラシークガ　ケンリョクヲ　ニギル<line>"
.stringmap script "マエハ　コノムラモ　ユタカダッタ。<wait>"
; Before LaShiec’s powerful grasp, this village was very wealthy.

textSopia4:
.stringmap script "ミズウミノ　ミナミノ　ヤマノ　ナカニ"
.stringmap script "タジム　トイウ　ドウシガ　イマス。<wait>"
; There’s a monk named Tajimu living in the mountains South of the lake.

textSopia5:
.stringmap script "パルマセイハ　キレイナ　ホシダト<line>"
.stringmap script "キキマシタガ　ホントウデスカ。<end>"
; I heard that Palma is a very beautiful planet. Is it really true?

textSopia5_Yes:
.stringmap script "イッテミタイナー。<wait>"
; Ooh, I want to go there soo bad!

textSopia5_No:
.stringmap script "ソウデスカ。ワタシハ　モット<line>"
.stringmap script "クウキノ　キレイナトコロヘイキタイ。<wait>"
; Oh, I see. I want to go to a place with cleaner air.

textSopia6_Yes:
.stringmap script "アリガトウ。<wait more>"
.stringmap script "マタキテネ。<wait>"
; Thanks. Please come again.

textSopia6_No:
.stringmap script "ケチ。<wait>"
; Cheapskate!

textSopia6_Yes_NoPelorieMate:
.stringmap script "バカニスンデネエ。<wait>"
; Don’t f--- with me!

textAeroCastle2:
。。。。。。。。。<wait>
; .........

textGovernorGeneral2_Yes:
.stringmap script "ソウカ。ソレデコソ　アルゴルオウノ<line>"
.stringmap script "ムスメダ。<wait more>"
.stringmap script "ワタシモ　テツダワセテモラウヨ。<wait>"
; I see. Then indeed, you are the daughter of the King of Algol, [and our new Queen]. Please let me help you [however I can].

textBayaMarlayPrison1:
.stringmap script "オオ　アンタモ　トジコメラレタノカ<line>"
.stringmap script "カワイソウニ。<wait more>"
textBayaMarlayPrison1a:
.stringmap script "ソトニデル　ホウホウハ　アルンジャガ"
.stringmap script "ワシハ　ココニ　イルホウガ<wait more>"
.stringmap script "キラクデ　イイワイ。<wait>"
; Oh! So you’re locked up in here as well? How tragic. There IS a way to get outside, but I'D rather stay here where it's nice and cozy.

textBayaMarlayPrison2:
.stringmap script "コノサキヘハ　イカナイホウガ<line>"
.stringmap script "イイヨ。　ケイビヘイガ　イルンダ。<wait>"
; You’d better not go any further, ‘cuz there’s a guard station up there.

textAvionTower:
.stringmap script "ヒキカエスナラ　イマノウチジャゾ。<wait>"
; Leaving? Better do it now.

textBayaMarlayPrison3:
.stringmap script "ロードパスヲ　モッテイルカ。<end>"
; Do you have a Roadpass?

textBayaMarlayPrison3_Yes:
.stringmap script "ドレドレ<line>"
.stringmap script "ン　コレハ　ニセモノダ。<wait more>"
textBayaMarlayPrison3_Yes_a:
.stringmap script "ロボットダト　オモッテ　ナメルナヨ。"
.stringmap script "ロウニ　ブチコンデヤル。<wait>"
; Let me see here... Hm? This is a fake! Don't think you can fool me just because I'm a robot! Let me show you to your cell.

textBayaMarlayPrison4:
.stringmap script "オレヲ　ココカラ　ダシテクレルノカ。"
.stringmap script "デモ　ムダダヨ。<wait>"
; I wonder if you could help me escape from this place, but it’s hopeless.

textBayaMarlayPrison5:
.stringmap script "ラシークヲ　タオソウナンテ<line>"
.stringmap script "ムボウダヨ。<wait>"
; Defeat LaShiec?! That’s nonsense!

textBayaMarlayPrison6:
.stringmap script "ワタシタチハ　ラシークノ　イケニエニ"
.stringmap script "サレテシマウノヨ。　ウッウウ。<wait>"
; We will all be sacrificed in the name of LaShiec! Agh!

textBayaMarlayPrison7:
.stringmap script "グアランニアル　ヨロイヲ<line>"
.stringmap script "テニイレタカイ。<end>"
; Have you gotten the armor from Guaran?

textBayaMarlayPrison7_No:
.stringmap script "ソレハ　オトシアナノ　ムコウガワニ<line>"
.stringmap script "アルンダヨ。<wait>"
; It’s on the other side of a pitfall!

textBayaMarlayPrison7_Yes:
.stringmap script "キミッテ　スゴイネ。<wait>"
; Damn! You’re pretty cool!

textBayaMarlayPrison8:
.stringmap script "ラシークニ　デアッタモノハ　ミナ<line>"
.stringmap script "ソノ　マリョクデ<wait more>"
.stringmap script "タマシイヲ　ウバワレルソウダヨ。<wait>"
; All those who have gone up against LaShiec have had their souls taken by his magic.

textGovernorGeneral2_No:
.stringmap script "ソウカ。ソレモ　ヨカロウ。<line>"
.stringmap script "マタ　イツデモ　モドッテクルガイイ。<wait>"
; I see. [You must do as you wish]. You are welcome to return at anytime.

textBayaMarlayPrison9:
.stringmap script "バヤマーレノ　オカノウエニハ<line>"
.stringmap script "トウガアル。<wait more>"
.stringmap script "アノトウニ　ヒミツガ　カクサレテ<line>"
.stringmap script "イルニチガイナイ。<wait>"
; There is a tower on top of Baya Marlay knoll. There must be secrets hidden inside.

textCoronaTower1:
.stringmap script "ナニシニキタダ。　オメエタチ<line>"
.stringmap script "ワルサ　スンデネエゾ。<wait>"
; What is your business here? Don’t cause any trouble!

textUnused2:
; Index $0236, seems to be unused.
.stringmap script "イヤナ　ヨカンガスル。<wait>"
; I’ve got a baad feeling about this...

textCoronaTower2:
.stringmap script "コレカラ　サキハ　キヲツケテ。<line>"
.stringmap script "ワカレミチヲ　ヒダリヘ　イキナサイ。<wait>"
; Be careful up ahead. You should turn left at the fork in the path.

textCoronaTower3:
.stringmap script "ココダケノ　ハナシダガ　ダモア<line>"
.stringmap script "トイウ　ウラナイシノ　モッテイル<wait more>"
textCoronaTower3a:
.stringmap script "クリスタルヲ　ラシークサマハ<line>"
.stringmap script "キラッテオラレル。<wait more>"
.stringmap script "ナニカ　ヒミツガ　アルニチガイナイ。<wait>"
; Don’t let this get out, but there's a fortune-teller named Damoa who is in possession of a crystal that LaShiec hates. There must be something secret about that crystal.

textCoronaTowerTorchbearer:
.stringmap script "コノ　ヒハ　ヒャクネンニ　イチド<line>"
.stringmap script "ノ　ニッショクノ　トキニ　ツケタ<wait more>"
textCoronaTowerTorchbearer_a:
.stringmap script "モノダ。　ドラゴンノ　モッテイル<line>"
.stringmap script "ホウセキヲ　クレルナラバ　スコシ<wait more>"
textCoronaTowerTorchbearer_b:
.stringmap script "ワケテ　アゲテモ　ヨイガ　ドウダ。<end>"
; This flame is lit during each centennial solar eclipse. If you give me a dragon’s jewel, however, I’ll share the flame with you. Do we have an agreement?

textCoronaTowerTorchbearer_Yes:
.stringmap script "デハ　イクリプストーチヲ<line>"
.stringmap script "ウケトルガイイ。<wait>"
; Well then, please accept this ‘Eclipse Torch’.

textCoronaTowerTorchbearer_No:
.stringmap script "イラナイノカ。ソレジャア　オメエハ<line>"
.stringmap script "ナニシニ　キタンダ。<wait>"
; You don’t want it?! Then, ah, for what did you come here?

textCoronaTowerTorchbearer_Yes_NoCarbuncleEye:
.stringmap script "ホウセキヲ　モッテナイデハナイカ。<line>"
.stringmap script "ナメルナヨ。<wait>"
; You mean to say you don’t have the jewel?! Don’t toy with me!

textNaulaCaveShortcakeSalesman:
.stringmap script "コンナトコロニ　オミセガ　アッテ<line>"
.stringmap script "ゴメンナサイ。<wait more>"
.stringmap script "ショートケーキヲ　<number>メセタデ<line>"
.stringmap script "イカガデスカ。<end>"
; I’m sorry for having a store in a place like this. Shortcakes are 280 meseta. Would you like one?

textTajim1:
.stringmap script "オオ　ワガデシ　ルツヨ。　ツイニ<line>"
.stringmap script "ラシークヲ　タオス　タビニデルカ。<wait>"
; Ah. My student, Lutz! I see you are finally on your way to defeating LaShiec.

textTajim1a:
.stringmap script "デハ　ソツギョウノ　シケンヲ　シテ<line>"
.stringmap script "ヤロウ。ワシト　タタカウガヨイ。<wait>"
; That being the case, I'll give you your final test: a duel with me!

textTajim_Win:
.stringmap script "ツヨクナッタノウ。ルツヨ。<wait more>"
.stringmap script "ソレダケノチカラガ　アレバヨイ。<wait more>"
textTajim_Win_a:
.stringmap script "ワシカラノ　オクリモノトシテ<line>"
.stringmap script "フラードマントヲ　ツカワソウ。<wait more>"
textTajim_Win_b:
.stringmap script "オマエノ　カラダヲ　マモッテクレル<line>"
.stringmap script "ジャロウ。　デハ　ユクガヨイ。<wait>"
; You’ve become strong, my boy! You have all the power you’ll ever need. Please use this Frad Cloak. It is my gift to you. It will protect your body from harm. Well then, you’d best be on your way.

textTajim_Lose:
.stringmap script "マダマダ　シュギョウガ　タリンノウ。"
.stringmap script "デナオシテクルガヨイ。<wait>"
; You still haven’t trained enough. You should come back later.

textTajim2:
.stringmap script "モウ　ワシガ　オシエルコトハ　ナイ。<wait>"
; There is nothing more I can teach you.

textTajim_NoLutzYet:
.stringmap script "オマエサンガタハ　ドナタカナ。<line>"
.stringmap script "マハルノ　ドウクツニ　ワシノ　デシノ<wait more>"
textTajim_NoLutzYet_a:
.stringmap script "ルツガ　オル。シッテオルカ。<end>"
; Who, may I ask, are you? I have a student, Lutz, in the Cave of Magic. Do you know him?

textTajim_NoLutzYet_Yes:
.stringmap script "ルツニ　ツタエネバ　ナラヌコトガ<line>"
.stringmap script "アル。　ツレテキテハ　クレマイカ。<wait>"
; There is something I must tell Lutz. Would you please escort him to me?

textTajim_NoLutzYet_No:
.stringmap script "ソウカ。　ナラバ　イッテモ<line>"
.stringmap script "シカタノナイコトジャノウ。<wait>"
; I see. In that case, I guess it’s pointless for us to talk.

textShadowWarrior:
.stringmap script "オマエタチノ　コウドウハ<line>"
.stringmap script "スベテオミトオシダ。<wait more>"
textShadowWarrior_a:
.stringmap script "カカッテクルガ　イイ。<wait>"
; Make your move, fools. I can see right through you.

textShadowWarrior_Win:
.stringmap script "オレハ　ラシークサマノ<line>"
.stringmap script "カゲムシャダ。<wait more>"
textShadowWarrior_Win_a:
.stringmap script "オレヲタオシタトコロデ<line>"
.stringmap script "ドウニモナラナイノサ。　ヒッヒッ。<wait>"
; I am King LaShiec’s shadow warrior. You have gained nothing by defeating me! Hee hee hee!

textAeroCastle3:
.stringmap script "ラシークサマニ　サカラウナ。<wait>"
; Do not defy the great LaShiec.

textLaShiec:
.stringmap script "トウトウ　ココマデ　キタカ。<line>"
.stringmap script "ウンノ　イイヤツラメ。<wait more>"
.stringmap script "ソンナニ　ワシヲ　タオシタイノカ。<end>"
; And so you finally arrive. How fortunate you are. Do you really wish to defeat me?

textLaShiec_Yes:
.stringmap script "ソウカ。ソレナラバ<wait more>"
.stringmap script "ソノ　カンガエガ　マチガッテイタ<line>"
.stringmap script "コトヲ　オモイシルガイイ。<wait>"
; I see. Then perhaps I should show you the error in your judgment!

textLaShiec_No:
.stringmap script "コノゴニ　オヨンデ<line>"
.stringmap script "フザケタヤツラダ。<wait more>"
.stringmap script "コウカイサセテヤル。<wait>"
; You have already wasted too much of my time. I shall make you regret it!

textGovernorGeneral2:
.stringmap script "オオ。ミンナ　スマナカッタ。<wait more>"
.stringmap script "ワタシノ　ココロト　カラダハ<wait more>"
textGovernorGeneral2a:
.stringmap script "ドウヤラ　アシキ　マリョクニ<line>"
.stringmap script "オカサレテイタラシイ。<wait more>"
textGovernorGeneral2b:
.stringmap script "ヨクゾ　コノヨヲ　スクッテクレタ。<line>"
.stringmap script "モウスコシ　オソカッタラ<wait more>"
textGovernorGeneral2c:
.stringmap script "タイヘンナコトニ　ナッテイタダロウ。"
.stringmap script "ココロカラ　レイヲ　イウゾ。<wait more>"
.stringmap script "アリサヨ。<line>"
.stringmap script "オマエニ　ハナシタイコトガアル。<wait more>"
.stringmap script "ジツハ　オマエノ　チチハ<line>"
.stringmap script "アルゴルノ　オウダッタ。<wait more>"
.stringmap script "アクマノ　シロハ　クズレサリ<line>"
.stringmap script "ラシーク　ナキ　イマ　オマエハ<wait more>"
.stringmap script "チチノ　アトヲ　ツギ　アルゴルノ<line>"
.stringmap script "ジョウオウト　ナルカ。<end>"
; Oh! My friends, please forgive me. My mind and body seem to have been enchanted by some sort of evil force.
; Well done! You have saved the world! If you had taken any longer, terrible events might have come to pass. I extend you my utmost appreciation.
; And now, Alisa, I have something I wish to tell you:
; The truth is, your father was once the King of Algol.
; Now that the demon’s fortress has been destroyed, and LaShiec is no more, will be your father’s successor and become the Queen of Algol?

textOtegamiChieChan:
.stringmap script "ワタシ　オテガミ　チエチャンヨ。<line>"
.stringmap script "イツモ　オタヨリ　アリガトウ。<wait more>"
.stringmap script "コノゲームノ　カンソウヲ<line>"
.stringmap script "キカセテネ。　マッテルワ。<wait>"
; I am 'Otegami Chie-chan!’ Thanks for all your letters. Please tell us how you feel about this game. We’ll be waiting.

textLuvenoGuard1:
; Referenced by unused indices 27c, 27e, 280
.stringmap script "ココカラ　サキハ　ボクノ<line>"
.stringmap script "ナワバリダカラ　トオセナイヨーダ。<wait>"
; The area beyond here is my territory, so stay the hell out!

textLuvenoGuard2:
.stringmap script "ルベノハカセガ　イウノダッタラ<line>"
.stringmap script "ショウガナイ。　トオッテモイイヨ。<wait>"
; Well, I guess I gotta do what Dr. Luveno says. Go ahead and pass.

textShion9:
.stringmap script "モタビアセイニハ　モタビアン<line>"
.stringmap script "デゾリスセイニハ　デゾリアン　トイウ<wait more>"
.stringmap script "セイジンガ　スンデイルソウダヨ。<line>"
.stringmap script "イチド　アッテ　ハナシテミタイナ。<wait>"
; On Motabia, there are the Motavians. On Dezoris, the Dezorians. I’d like to hang out and talk with them sometime.

textPaseo6:
.stringmap script "カシコイ　モンスターニハ<line>"
.stringmap script "モンスターコトバガ　アルソウダ。<wait>"
; I hear that intelligent monsters have monster languages.

textPaseoTrader_HaveMyau:
.stringmap script "ラコニアンポットハ　トテモ　タカク<line>"
.stringmap script "ウレタヨ。　アリガトサン。<wait>"
; That laconian pot was worth a fortune! Thanks a bundle!

textDrLuveno1h:
.stringmap script "ヨシ　コレデ　スタッフハ<line>"
.stringmap script "ソロッタヨウダ。　ソコデ<wait more>"
textDrLuveno1i:
.stringmap script "セイサクヒガ　<number>メセタ<line>"
.stringmap script "カカルンジャガ　ワシニ　クレンカ。<end>"
; Okay, it looks like my staff is assembled. Manufacturing expenses come to 1200 meseta. Will you please give it to me?

textDrLuveno1j:
.stringmap script "アリガトウ。デハ　セイサクヲ<line>"
.stringmap script "ハジメヨウ。スコシマッテクレ。<wait>"
; Thanks. Now then, let’s begin construction, shall we? Please wait for a little while.

textDrLuveno1k:
.stringmap script "アワテテモ　イイモノハ　デキンゾヨ。"
.stringmap script "モウ　スコシノシンボウジャ。<wait>"

textDrLuveno1l:
.stringmap script "ヨシ。コレデ　ルベノゴウニ　ノッテ<line>"
.stringmap script "ウチュウヘ　トビダセル。<wait more>"
.stringmap script "ムラノ　ソトヘ　デテミルガイイ。<line>"
.stringmap script "ナカナカノ　デキダヨ。<wait>"
; Now then, you can use the Luveno to fly through space. Go outside the village and take a look. It’s a brilliant piece of work.

textMadDoctor:
.stringmap script "オイ　ソコノ　ネコ。<line>"
.stringmap script "コッチヘ　コイ。<end>"
; Hey, cat! C'mere!

textMadDoctor_Yes:
.stringmap script "ケッケッケ。オマエラモ　シニタイカ。<wait>"
; Hee hee hee! You guys wanna die too?

textMadDoctor_No:
.stringmap script "ワシノ　ジャマヲ　スルヤツハ<line>"
.stringmap script "コロシテヤル。<wait>"
; I will kill anything that gets in my way!

textGovernorGeneral3:
.stringmap script "ナガイタビデ　ツカレタダロウ。<line>"
.stringmap script "ココデ　ユックリ　ヤスムガイイ。<wait>"
; You must be tired from your long journey. You should relax here for a while.

textGovernorGeneral4:
.stringmap script "モウ　イッコクノ　ユウヨモ<line>"
.stringmap script "ユルサレナイ。<wait more>"
.stringmap script "ココロシテ　カカルガヨイ。<line>"
.stringmap script "ブジヲ　イノッテイル。<wait>"
; There’s no time to lose! Have faith in yourself. I’ll be praying for your safety.

textGuestHouse2:
.stringmap script "フカイ　ネムリニ　ツイタ。<delay>"
; You enter into a deep sleep...

textGuestHouse2a:
.stringmap script "オソロシイ　ユメダッタ。<wait>"
; What a frightening dream!

textAlisasHouse:
.stringmap script "ココハ　アリサノ　ウチデス。<line>"
.stringmap script "ダレモ　イマセン。<wait>"
; This is Alisa’s house. Nobody is here.

textGovernorGeneral5:
.stringmap script "オヤ。ヨウスガ　ヘンダ。<wait more>"
.stringmap script "ソウトクハ　ドコヘ　イッタンダロウ。<wait>"
; Hey. That’s weird... Where’d the Governor-General go?

textTajim1_LutzDead:
.stringmap script "オヤ。シンデオルノカ。ナサケナイ。<line>"
.stringmap script "イキカエッテ　デナオスガイイ。<wait>"
; YOU HAVE GOTTEN YOURSELF KILLED? COME, LET'S TRY ONE MORE TIME.

textLaShiec_Win:
.stringmap script "ラシークハ　タオレタ。<wait more>"
.stringmap script "アリサノ　ネガイハ　カナエラレタ。<wait more>"
.stringmap script "テンゴクノ　ネロモ　キット<line>"
.stringmap script "ヨロコンデイルコトダロウ。<wait more>"
.stringmap script "サア　パセオノ　ソウトクノ　モトヘ<line>"
.stringmap script "イソゴウ。<wait>"
; What?! Could it be that I die? What a disgrace. I shall live again!
; LaShiec has fallen. Alisa’s wish has come true. Surely even Nero will be rejoicing in heaven. Now let's hurry back to Paseo and see the Governor-General!

textMonsterDodgesPlayersAttack:
.stringmap script "<monster>ハ　<player>ノ<line>"
.stringmap script "コウゲキヲ　カワシタ。<delay>"

textPlayerDodgesMonstersAttack:
.stringmap script "<player>ハ　<monster>ノ<line>"
.stringmap script "コウゲキヲ　カワシタ。<delay>"

textPlayerSpeaks:
.stringmap script "<player>ハ　ハナシカケタ。<end>"

textMonsterAnswers:
.stringmap script "<monster>ハ　コタエタ。<delay>"

textMonsterDidntUnderstand:
.stringmap script "ツウジナカッタ。<delay>"

textMonsterBlocksRetreat:
.stringmap script "<monster>ハ　ニゲミチニ<line>"
.stringmap script "タチフサガッタ。<delay>"

textPlayersSpellHadNoEffect:
.stringmap script "<player>ノ　マジックハ<line>"
.stringmap script "コウカガ　ナカッタ。<delay>"

textUnused5:
.stringmap script "<monster>ノ　マジックハ<line>"
.stringmap script "コウカガ　ナカッタ。<delay>"
; Monster's spell had no effect

textMagicWall:
.stringmap script "メノマエニ　ミエナイ　マホウノ<line>"
.stringmap script "カベガ　デキタ。<delay>"

textMagicWallDeflectsMonstersAttack:
.stringmap script "<monster>ノ　コウゲキハ<line>"
.stringmap script "マホウノ　カベニ　ハネカエサレタ。<delay>"

textMagicWallDeflectsMonstersMagic:
.stringmap script "<monster>ノ　マジックハ<line>"
.stringmap script "マホウノ　カベニ　ハネカエサレタ。<delay>"

textMagicWallEnd:
.stringmap script "ミエナイ　カベノ　コウカガ<line>"
.stringmap script "ナクナッタ。<delay>"

textPlayerHealed:
.stringmap script "<player>ノ　タイリョクガ<line>"
.stringmap script "カイフクシタ。<delay>"

textMonsterHealed:
.stringmap script "<monster>ノ　タイリョクガ<line>"
.stringmap script "カイフクシタ。<delay>"

textMonsterTiedUp:
.stringmap script "<monster>ヲ<line>"
.stringmap script "カナシバリニシタ。<delay>"

textPlayerTiedUp:
.stringmap script "<player>ハ　カナシバリニ　アッタ。<delay>"

textPlayerCantMove:
.stringmap script "<player>ハ　ウゴケナイ。<delay>"

textMonsterCantMove:
.stringmap script "<monster>ハ　ウゴケナイ。<delay>"

textPlayerRemovedBindings:
.stringmap script "<player>ハ　カナシバリガ　トケタ。<delay>"

textMonsterRemovedBindings:
.stringmap script "<monster>ハ<line>"
.stringmap script "カナシバリガ　トケタ。<delay>"

textPlayerEnergyBoost:
.stringmap script "<player>ハ　カラダニ　チカラガ<line>"
.stringmap script "ミナギルノヲ　カンジタ。<delay>"

textMonsterRanAway:
.stringmap script "<monster>ハ　コワクナッテ<line>"
.stringmap script "シリゴミシタ。<delay>"

textPartyRanAway:
.stringmap script "<monster>ハ　ニゲアシノ<line>"
.stringmap script "ハヤサニ　オドロイタ。<delay>"

textNoTrap:
.stringmap script "ワナジャナカッタ。<wait>"

textTrapDisarmed:
.stringmap script "アブナイ　トコロダッタ。<player>ハ<line>"
.stringmap script "ワナヲ　ミヤブッテ　ハズシタ。<wait>"

textPlayerUsedItem:
.stringmap script "<player>ハ　<item>ヲ<line>"
.stringmap script "ツカッタ。<delay>"

textPlayerEquippedItem:
.stringmap script "<player>ハ　<item>ヲ<line>"
.stringmap script "ソウビシタ。<end>"

textPlayerDroppedItem:
.stringmap script "<player>ハ　<item>ヲ<line>"
.stringmap script "ステテシマッタ。<wait>"

textNoEffect:
.stringmap script "シカシ　コウカハ　ナカッタ。<delay>"

textItemNoUseHere:
.stringmap script "シカシ　ココデ　<item>ハ<line>"
.stringmap script "ヤクニ　タタナイ。<wait>"

textCantDisembark:
.stringmap script "ココデ　オリルワケニハ　イカナイ。<wait>"

textBoardedVehicle:
.stringmap script "<item>ニ　ノリコンダ。<delay>"

textDisembarkedVehicle:
.stringmap script "<item>カラ　トビオリタ。<delay>"

textNothingHappened:
.stringmap script "シカシ　ナニモ　オキナカッタ。<delay>"

textSootheFluteCalmedMonster:
.stringmap script "<monster>ハ　フエノネヲ<line>"
.stringmap script "キイテ　オトナシクナッタ。<delay>"

textUnused6:
.stringmap script "<monster>ハ　メガ　ウツロダ。<delay>"
; Monster's eyes looked vacant

textCantDoThatNow:
.stringmap script "シカシ　イマハ　ソンナコトヲ<line>"
.stringmap script "シテイルバアイジャ　ナイヨウダ。<delay>"

textPlayerTakesOutItem:
.stringmap script "<player>ハ　<item>ヲ<line>"
.stringmap script "トリダシタ。<delay>"

textNoNeedNow:
.stringmap script "ベツニ　コワレテナイヨウダ。<wait>"

textTooDarkToMove:
.stringmap script "マックラデ　ススムコトガ　デキナイ。"

textAlisPourBottle:
.stringmap script "ソシテ　ビンノ　フタヲ　アケテ<line>"
.stringmap script "シズカニ　タラシタ。<delay>"

textMyauCantOpenBottle:
.stringmap script "シカシ　ミャウハ　ビンノ　フタヲ<line>"
.stringmap script "アケルコトガ　デキナカッタ。<wait>"

textItStinks:
.stringmap script "イツ　カイデミテモ　イヤナ<line>"
.stringmap script "ニオイガ　スル。<wait>"

textPlayerPremonition:
.stringmap script "<player>ハ　トテモ<line>"
.stringmap script "イヤナ　ヨカンガシタ。<wait>"

textPlayerNoPremonition:
.stringmap script "<player>ハ　ナニモ　カンジナカッタ。<wait>"

textMonsterAfraidOfFlame:
.stringmap script "<monster>ハ　アカイ　ホナオヲ<line>"
.stringmap script "ミテ　オジケズイタ。<delay>"

textPlayerHeldItemUp:
.stringmap script "<player>ハ　<item>ヲ<line>"
.stringmap script "テンニ　カザシタ。<delay>"

textPlayerPutLaermaBerriesInLaconianPot:
.stringmap script "<player>ハ　ラエルマベリーヲ　トッテ<line>"
.stringmap script "ラコニアンポットニ　イレタ。<wait>"

textLaermaBerriesShriveledUp:
.stringmap script "ラエルマベリーヲ　トッテミタガ<line>"
.stringmap script "シバラクスルト　ヒカラビテシマッタ。<wait>"

textAerocastleAppeared:
.stringmap script "マボロシノ　エアロキャッスルガ<line>"
.stringmap script "オオゾラニ　スガタヲ　アラワシタ。<wait>"

textNobodyHungry:
.stringmap script "オナカガ　スイテナカッタノデ<line>"
.stringmap script "モトニ　モドシタ。<wait>"

textHapsbySaysNo:
.stringmap script "ハプスビーハ　イヤイヤヲシタ。<wait>"

textHapsbyHardHead:
.stringmap script "ハプスビーノ　アタマハ　カタイ。<wait>"

textItemAlwaysActive:
.stringmap script "ソレハ　ツカワナクテモ<line>"
.stringmap script "キキメガ　アル。<wait>"

textNothingUnusualHere:
.stringmap script "トクニ　カワッタトコロハ<line>"
.stringmap script "ナイヨウダ。<wait>"

textFoundItem:
.stringmap script "<item>ヲ　ミツケタ。<wait>"

textYouBecomeLight:
.stringmap script "ナンダカ　カラダガ　カルクナッタ。<delay>"

textPlayerRevived:
.stringmap script "<player>ノ　タマシイハ<line>"
.stringmap script "ヨミガエッタ。<wait>"

textTaironCantUseMagic:
.stringmap script "タイロンハ　マジックヲ　ツカエナイ。<delay>"

textPlayerHasNoMagicYet:
.stringmap script "<player>ハ　マダ　マジックヲ<line>"
.stringmap script "オボエテイナイ。<delay>"

textPlayerCantEquipItem:
.stringmap script "<player>ハ　<item>ヲ<line>"
.stringmap script "ソウビ　デキナイ。<wait>"

textNoNeedToEquipItem:
.stringmap script "ソレハ　ソウビシナクテモイイ。<wait>"

textGainedExperience:
.stringmap script "ケイケンチガ　<number>ポイント<line>"
.stringmap script "アガッタ。<wait>"

textLevelUp:
.stringmap script "<player>ハ　レベルアップシタ。<wait>"

textPlayerLearnedASpell:
.stringmap script "<player>ハ　マジックヲ<line>"
.stringmap script "ヒトツ　ミニツケタ。<wait>"

textMesetasInside:
.stringmap script "<number>メセタ　ハイッテイタ。<wait>"

textDoYouWantToOpenIt:
.stringmap script "アケテミルカ。<end>"

textItsEmpty:
.stringmap script "カラッポダッタ。<wait>"

textInventoryFull:
.stringmap script "コレイジョウ　モノヲ　モテナイ<line>"
.stringmap script "ナニカヲ　ステルカ。<end>"

textWhatToDrop:
.stringmap script "ドレヲ　ステルカ。<end>"

textDropItemToGetItem:
.stringmap script "<item>ヲ　ステテ<wait>"

textAndGetItem:
.stringmap script "<item>ヲ　テニイレタ。<wait>"

textConfirmDropItem:
.stringmap script "<item>ハ　イラナイノカ。<end>"

textDropItem:
.stringmap script "<item>ヲ　アキラメタ。<wait>"

textCantDropItem:
.stringmap script "<item>ヲ<line>"
.stringmap script "ステルワケニハ　イカナイ。<wait>"

textNotEnoughMagicPoints:
.stringmap script "マジックポイントガ　タリナイ。<delay>"

textPlayerIsNotDead:
.stringmap script "<player>ハ　マダ　イキテイル。<delay>"

textMonsterKilled:
.stringmap script "<monster>ヲ　ヤッツケタ。<wait>"

textPlayerDied:
.stringmap script "<player>ハ　シンデシマッタ。<delay>"

textPlayerAlreadyDead:
.stringmap script "<player>ハ　モウ　シンデイル。<delay>"

textMyauAteLaermaBerry:
.stringmap script "ミャウハ　ラエルマベリーヲ<line>"
.stringmap script "カジッタ。<wait>"

textHapsby_ChooseDestination:
.stringmap script "ドコヘ　イキマスカ。<end>"

textHapsby_DestinationSkray:
.stringmap script "デゾリスセイノ　スクレノマチヘ<line>"
.stringmap script "イキマス。イイデスカ。<end>"

textHapsby_DestinationUzo:
.stringmap script "モタビアセイノ　ウーゾノムラヘ<line>"
.stringmap script "イキマス。イイデスカ。<end>"

textHapsby_DestinationGothic:
.stringmap script "パルマセイノ　ガシコノムラヘ<line>"
.stringmap script "イキマス。イイデスカ。<end>"

textHapsby_ThisIsSkray:
.stringmap script "ココハ　スクレ　デス。<end>"

textHapsby_ThisIsUzo:
.stringmap script "ココハ　ウーゾ　デス。<end>"

textHapsby_ThisIsGothic:
.stringmap script "ココハ　ガシコ　デス。<end>"

textUnused7:
.stringmap script "シュッパーツ。<delay>"
; Let's go! (in context of Hapsby flying Luveno)

textEppiWoodsCantPass:
.stringmap script "モリノナカデ　ミチニ　マヨッテ<line>"
.stringmap script "シマッタ。<wait>"

textArmory:
.stringmap script "ココハ　アーマーショップデス。<line>"
.stringmap script "ナニカ　カイマスカ。<end>"

textShopComeAgain:
.stringmap script "ソウデスカ。マタキテクダサイ。<wait>"

textShopWhatDoYouWant:
.stringmap script "ドレヲ　カイマスカ。<end>"

textShopBuyItem:
.stringmap script "アリガトウ。モット　カイマスカ。<end>"

textShopInventoryFull:
.stringmap script "ソレイジョウ　モテナイヨウデスネ。<line>"
.stringmap script "マタキテクダサイ。<wait>"

textPharmacy:
.stringmap script "ココハ　ドラッグストアデス。<line>"
.stringmap script "ナニカ　カイマスカ。<end>"

textToolShop:
.stringmap script "ココハ　ツールショップデス。<line>"
.stringmap script "ドンナ　ゴヨウデスカ。<end>"

textToolShop_WhatToSell:
.stringmap script "ドレヲ　ウリマスカ。<end>"

textToolShop_SellPriceOffer:
.stringmap script "<item>デスネ。<line>"
.stringmap script "<number>メセタデ　イイデスカ。<end>"

textToolShop_SoldItem:
.stringmap script "アリガトウ　モットウリマスカ。<end>"

textHospital:
.stringmap script "ココハ　ホスピタルデス。<line>"
.stringmap script "チリョウヲ　ウケマスカ。<end>"

textHospitalFee:
.stringmap script "シンサツト　チリョウヒ<line>"
.stringmap script "<number>メセタデス。ヨロシイデスカ。<end>"

textHospitalAnyoneElse:
.stringmap script "ホカニ　チリョウヲ　ウケタイカタハ<line>"
.stringmap script "イマスカ。<end>"

textHospitalWho:
.stringmap script "ドナタガ　チリョウヲ　ウケマスカ。<end>"

textHospitalThankYouForWaiting:
.stringmap script "オマチドウサマ。<line>"
.stringmap script "ドウゾ　オダイジニ。<wait>"

textHospitalCouldNotHelp:
.stringmap script "ソウデスカ　オテツダイデキナクテ<line>"
.stringmap script "ザンネンデス。"
; Falls through to
textHospitalPleaseBeCareful:
.stringmap script "デハ　オキヲツケテ。<wait>"

textHospitalNoNeedToHealPlayer:
.stringmap script "<player>サンハ　イジヨウ<line>"
.stringmap script "アリマセンネ。<wait>"

textChurch:
.stringmap script "ココハ　キョウカイデス。　ダレカノ<line>"
.stringmap script "タマシイヲ　ヨビモドサレマスカ。<end>"

textUnused8:
.stringmap script "デハ　アナタノタメニ<line>"
.stringmap script "オイノリヲ　ササゲマス。<wait>"
; I shall pray for you

textChurchIncantation1:
.stringmap script "ソレデハ　ジュモンヲ　トナエマス。<delay>"

textChurchIncantation2:
.stringmap script "アルテムハムラム　アルテムハムハム<line>"
.stringmap script "ストラトポン。<delay>"

textChurchWho:
.stringmap script "ドナタノ　タマシイデショウ。<end>"

textChurchAnyoneElse:
.stringmap script "ホカノカタハ　イカガデスカ。<end>"

textChurchPrice:
.stringmap script "<number>メセタ　カカリマスガ<line>"
.stringmap script "ヨロシイデスカ。<end>"

textChurchToLevelUp:
.stringmap script "コレカラ　レベルアップスルタメニハ<wait>"

textChurchPlayerNeedsExperiencePoints:
.stringmap script "<player>ハ　<number>ポイント<line>"
.stringmap script "ヒツヨウデス。<wait>"

textChurchEnd:
.stringmap script "アナタガタノ　ユクスエニ<line>"
.stringmap script "カミノ　メグミガ　アリマスヨウニ。<wait>"

textChurchPlayerNotDead:
.stringmap script "<player>ハ　イキテイマスヨ。<end>"

textSaveSelectSlot:
.stringmap script "セーブヲ　オコナイマス。<line>"
.stringmap script "バンゴウヲ　エランデクダサイ。<end>"

textSaveDeleteConfirmSlot:
.stringmap script "<number>バンデ　イイデスカ。<end>"

textSavingToSlot:
.stringmap script "デハ　<number>バンニ　セーブシマス。<delay>"

textSavingComplete:
.stringmap script "オワリマシタ。<wait>"

textMonster1:
.stringmap script "ワタシタチハ　パルマノ　ヒトタチト<line>"
.stringmap script "ナカヨク　シタイ。<wait>"

textMonster2:
.stringmap script "ラエルマベリーガ　タベタイナア。<wait>"

textMonster3:
.stringmap script "ラシークサマニハ<line>"
.stringmap script "サカラワナイホウガ　イイヨ。<wait>"

textMonster4:
.stringmap script "オッ。ワタシタチノ　コトバガ<line>"
.stringmap script "ワカルンダネ。<wait>"

textMonster5:
.stringmap script "ヤッホー。<wait>"

textMonster6:
.stringmap script "ダンジョンデハ　オトシアナニ<line>"
.stringmap script "キヲツケナヨ。<wait>"

textMonster7:
.stringmap script "タカラバコハ　ムヤミニ<line>"
.stringmap script "アケルト　ケガヲスルヨ。<wait>"

textMonster8:
.stringmap script "コノ　オイハギヤロウ。<wait>"

textMonster9:
.stringmap script "ワタシタチハ　ドウセ<line>"
.stringmap script "ニクマレモノダヨ。<wait>"

textMonster10:
.stringmap script "スーズフルートノ　ネイロハ<line>"
.stringmap script "イイナア。<wait>"

textMonster11:
.stringmap script "アイスデッカー　トイウ　ノリモノハ<line>"
.stringmap script "コオリモ　ケズレルンダッテ。<wait>"

textMonster12:
.stringmap script "ラシークサマハ　ソラノウエニ<line>"
.stringmap script "イラッシャルンダ。<wait>"

textMonster13:
.stringmap script "アビオンノ　マッドドクターガ<line>"
.stringmap script "ラスコニアンポットヲ　モッテタゼ。<wait>"

textMonster14:
.stringmap script "ソラノ　ウエニハ　ウチュウセンデモ<line>"
.stringmap script "イケナイトコロガアルゼ。<wait>"

textMonster15:
.stringmap script "ラエルマベリーヲ　ミノラセルタメニハ"
.stringmap script "アルモノガ　ヒツヨウダ。<wait>"

textMonster16:
.stringmap script "ダンジョンノ　メイロニハ<line>"
.stringmap script "カクシトビラガ　アルンダゼ。<wait>"

textMonster17:
.stringmap script "ミラクルキーハ　マホウノドアデモ<line>"
.stringmap script "アケルコトガ　デキルゾ。<wait>"

textMonster18:
.stringmap script "デゾリアンニハ　ウソツキモ　イルカラ"
.stringmap script "キヲツケナヨ。<wait>"

textMonster19:
.stringmap script "ワタシニ　ハナシカケルトハ<line>"
.stringmap script "ユウキガ　アルネエ。　ガンバレヨ。<wait>"

textMonsterStrengthBoost:
.stringmap script "<monster>ハ　カラダニ<line>"
.stringmap script "チカラガ　ミナギルノヲカンジタ。<delay>"

textMonsterHadATreasureChest:
.stringmap script "<monster>ハ　タカラバコヲ<line>"
.stringmap script "モッテイタ。<end>"

textCompassEast:
.stringmap script "イマ　ヒガシヲムイテイル。<wait>"

textCompassWast:
.stringmap script "イマ　ニシヲ　ムイテイル。<wait>"

textCompassNorth:
.stringmap script "イマ　キタヲ　ムイテイル。<wait>"

textCompassSouth:
.stringmap script "イマ　ミナミヲ　ムイテイル。<wait>"

textAllDead:
.stringmap script "アリサタチハ　ゼンメツシタ。<wait>"

textGameOver:
.stringmap script "アリサノ　ネガイハ　ラシークノ<line>"
.stringmap script "ヤボウノ　マエニ<wait more>"
.stringmap script "ムナシク　キエサッタ。<line>"
.stringmap script "ココデ　ボウケンハ　オワリデス。<wait>"

textShopNotEnoughMoney:
.stringmap script "オカネガ　タリナイヨウデスネ。<line>"
.stringmap script "マタキテクダサイ。<wait>"

textHandyLater:
.stringmap script "ソレハ　アトデ　ヤクニタチマスヨ。<wait>"

textFoundTreasureChest:
.stringmap script "タカラバコヲ　ミツケタ。<end>"

textChurchNotEnoughMoney:
.stringmap script "アルテムハムラム　ア　ウッ。<line>"
.stringmap script "ゴホッ。ゴホッ。<wait more>"
.stringmap script "ゴメンナサイ。<line>"
.stringmap script "ドウヤラ　シッパイシタヨウデス。<wait>"

textBoundForMotavia:
.stringmap script "モタビア　ユキデス。ノリマスカ。<end>"

textBoundForPalma:
.stringmap script "パルマ　ユキデス。ノリマスカ。<end>"

textHospitalPlayerAtMaxHealth:
.stringmap script "<player>ハ　モウ<line>"
.stringmap script "チカライッパイデス。<wait>"

textChooseSlotToContinue:
.stringmap script "ゲームノ　ツヅキヲ　ヤリマス。<line>"
.stringmap script "バンゴウヲ　エランデクダサイ。<end>"

textContinuingGameX:
.stringmap script "デハ　<number>バンノゲームヲ　ハジメマス。<delay>"

textUnused9:
.stringmap script "パスワードガ　チガイマス。<line>"
.stringmap script "モウイチド　タシカメテクダサイ。<wait>"
; That password is incorrect. Please try again.

textContinueOrDelete:
.stringmap script "ゲームノツヅキヲ　ヤル。ーー　ハイ<line>"
.stringmap script "ゲームヲ　ケス。ーーーーーー　イイエ<end>"

textConfirmDelete:
.stringmap script "セーブシタ　ゲームヲ　ケシマス。<line>"
.stringmap script "イイデスカ。<end>"

textChooseWhichToDelete:
.stringmap script "ナンバンノ　ゲームヲ　ケシマスカ。<end>"

textGameXHasBeenDeleted:
.stringmap script "<number>バンノ　ゲームヲ　ケシマシタ。<wait>"

textPlayerTurnedToStone:
.stringmap script "<player>ハ　イシニ　ナッテシマッタ。<wait>"

textItemUsedUp:
.stringmap script "<item>ハ　イマ　ダレカガ<line>"
.stringmap script "ツカッテシマッタ。<wait>"

textEnding1:
.stringmap script "シダイニ　ソラガ　アカルクナッテイキ"
.stringmap script "ヒトビトモ　ヘイワヲ　トリモドシタ。<end>"

textEnding2:
.stringmap script "イマ　バヤマーレハ　サワヤカナ<line>"
.stringmap script "ソヨカゼニ　ツツマレテイル。<end>"

textEnding3:
.stringmap script "カレラノ　ナガク　クルシカッタタビヲ"
.stringmap script "ソヨカゼハ　シッテイルノダロウカ。<end>"

textMyauDiesWhileFlying:
.stringmap script "ミャウニ　ノッテイタ　アリサタチハ<line>"
.stringmap script "ソラニ　ホウリダサレテシマッタ。<wait>"

textDarkForceResurrection:
.stringmap script "ソノトキ　アリサノ　タマシイハ<line>"
.stringmap script "ネロノコエヲ　キイタ。<wait more>"
.stringmap script "オマエハ　フタタビ　イキテ<line>"
.stringmap script "ヘイワノタメニ　ツクスガイイ。<wait more>"
.stringmap script "アリサノ　タマシイハ　ヨミガエッタ。<wait>"

textSoothFlute:
.stringmap script "ココロガ　ナゴムヨウナ<line>"
.stringmap script "ウツクシイ　ネイロダ。<wait>"

textIntro1:
.stringmap script "ラシークサマノ　コトヲ　コソコソト<line>"
.stringmap script "カギマワリヤガッテ。<line>"
.stringmap script "コレカラハ　セイゼイ　オトナシク<line>"
.stringmap script "シテイルコトダナ。<wait more>"
.stringmap script "ニイサン。<line>"
.stringmap script "ナニガ　アッタノ。<line>"
.stringmap script "シッカリシテ。<wait>"

textIntro2:
.stringmap script "アリサ。キイテクレ。<line>"
.stringmap script "ラシークハ　コノホシニ　キョダイナ<line>"
.stringmap script "ワザワイヲ　マネイテシマッタ。<line>"
.stringmap script "セカイハ　ハメツニ　ムカッテイル。<wait more>"
.stringmap script "オレハ　ラシークガ　ナニヲ　タクランデ<line>"
.stringmap script "イルノカ　サグッテイタンダ。<line>"
.stringmap script "ケド　オレヒトリデハ　ドウスルコトモ<line>"
.stringmap script "デキナカッタ。<wait more>"
.stringmap script "タビノ　トチュウ　タイロン　トイウ<line>"
.stringmap script "ツヨイ　オトコノ　ウワサヲ　キイタ。<line>"
.stringmap script "カレト　イッショナラ　ラシークヲ　タオシ<line>"
.stringmap script "ヘイワヲ　トリモドスコトガデキルダロウ。<wait more>"
.stringmap script "アリサ。<line>"
.stringmap script "オレハ　モウ　ダメダ。<line>"
.stringmap script "オマエ　ヒトリヲ　ノコシテイク　オレヲ<line>"
.stringmap script "ユルシテクレ。<wait>"

textIntro3:
.stringmap script "アリサハ　ニイサンノ　イノチヲ　ムダニ<line>"
.stringmap script "シナイタメニ　タタカイニ　イキマス。<line>"
.stringmap script "キット　ミマモッテイテネ。<line>"
.stringmap script "ニイサン。<wait>"

textMyauIntro1:
.stringmap script "キョウカラ　ナカマネ。<line>"
.stringmap script "ワタシハ　アリサ。<line>"
.stringmap script "アナタノ　ナマエヲ　オシエテ。<wait>"

textMyauIntro2:
.stringmap script "ミャウ。<wait>"

textMyauIntro3:
.stringmap script "ネエ　ミャウ。<line>"
.stringmap script "タイロンノ　コト　ナンダケド　ナニカ<line>"
.stringmap script "シッテイタラ　オシエテ。<wait>"

textMyauIntro4:
.stringmap script "タイロン　イシニ　ナッチャッタノ。<line>"
.stringmap script "コノ　クスリ　カケレバ　ナオルンダ。<line>"
.stringmap script "ケド　ミャウ　ビンノ　フタ<line>"
.stringmap script "アケラレナイノ。<wait>"

textMyauIntro5:
.stringmap script "ソッカ。<line>"
.stringmap script "ジャ　イッショニ　タイロンヲ<line>"
.stringmap script "タスケニ　イキマショウ。<wait>"

textTylonIntro1:
.stringmap script "アリガトウ。タスカッタヨ。<line>"
.stringmap script "シカシ　メデューサニ<line>"
.stringmap script "シテヤラレルヨウデハ　ラシークハ<line>"
.stringmap script "タオセソウニ　ナイナ。<wait>"

textTylonIntro2:
.stringmap script "ワタシノ　ニイサンモ　ラシークヲ<line>"
.stringmap script "タオソウトシテ　シンデシマッタワ。<line>"
.stringmap script "シヌマエニ　アナタノ　ナマエヲ<line>"
.stringmap script "イイノコシテ。<wait>"

textTylonIntro3:
.stringmap script "ソウダッタノカ。<line>"
.stringmap script "ヨシ　キミノ　ニイサンノ　タメニモ<line>"
.stringmap script "チカラヲ　アワセテ　ラシークヲ<line>"
.stringmap script "タオソウ。<wait>"

textTylonIntro4:
.stringmap script "ソレヨリ　ナゼ　メデューサヲ<line>"
.stringmap script "タオソウト　シタノ。<wait>"

textTylonIntro5:
.stringmap script "メデューサガ　モッテイル　デンセツノ<line>"
.stringmap script "オノガ　ホシカッタンダケド<line>"
.stringmap script "ニゲラレチマッタ。<line>"
.stringmap script "クヤシイナア。<wait more>"
.stringmap script "ソウイエバ　オレ　コノ　ドウクツノ<line>"
.stringmap script "イキドマリニ　コンパスヲ<line>"
.stringmap script "カクシテオイタンダッケ。<line>"
.stringmap script "トリニ　イコウゼ。<wait>"

textLutzIntro1:
.stringmap script "ソウトクカラノ　テガミヲ　アズカッテ<line>"
.stringmap script "キマシタ。<line>"
.stringmap script "ヨンデイタダケマセンカ。<wait>"

textLutzIntro2:
.stringmap script "ワカリマシタ。<line>"
.stringmap script "ミンナデ　コノ　アルゴルタイヨウケイヲ<line>"
.stringmap script "アクノ　テカラ　マモリマショウ。<wait more>"
.stringmap script "ソノタメニハ　マズガシコノ　モリヘ<line>"
.stringmap script "イッテ　ルベノハカセニ　アイタイ。<line>"
.stringmap script "タシカ　マンホールヲ　トオッテ<line>"
.stringmap script "イケタハズデス。<wait>"

textMyausTransformation1:
.stringmap script "ラエルマベリーヲ　カジルト<line>"
.stringmap script "ミャウノ　カラダハ　ネツヲ　オビ<line>"
.stringmap script "マバユイ　ヒカリニ　ツツマレタ。<wait>"

textMyausTransformation2:
.stringmap script "ソシテ　ミルミル　ウチニ　ミャウハ<line>"
.stringmap script "オオキナ　ツバサヲ　モッタ　ウツクシイ<line>"
.stringmap script "ケモノヘト　カワッタ。<wait more>"
.stringmap script "ミャウハ　トクイソウニ　ヒトツ<line>"
.stringmap script "ハバテイテ　ミセタ。<wait>"

textEndingAlisa:
.stringmap script "　<line>"
.stringmap script "　　　　　アリサ<delay>"

textEndingTylon:
.stringmap script "　<line>"
.stringmap script "　　　　　タイロン<delay>"

textEndingLutz:
.stringmap script "　<line>"
.stringmap script "　　　　　ルツ<delay>"

textEndingMyau:
.stringmap script "　<line>"
.stringmap script "　　　　　ソシテ　ミャウ<delay>"

textEndingEnd:
.stringmap script "　　　　ヤミノ　キオクガ　キエテモ<line>"
.stringmap script "　　　　カレラノ　ナマエハ<line>"
.stringmap script "　　　　ヒトビトノ　ココロニ<line>"
.stringmap script "　　　　ノコリツヅケルダロウ。<delay>"

; text lookup table for items
ItemTextTable: ; $bd94
.stringmap script "　　　　　　　　"        ; Blank
.stringmap script "ウッドケイン<wait>　"      ; UtuDoKeIN         Wood Cane 
.stringmap script "ショートソード<wait>"       ; Siyo-ToSo-Do      Short Sword
.stringmap script "アイアンソード<wait>"        ; AIANSo-Do         Iron Sword  
.stringmap script "サイコウオンド<wait>"       ; SaIKoUONDo        Psycho (Ultimate) Wand  
.stringmap script "シルバータスク<wait>"      ; SiRuBa-TaSuKu     Silver Tusk
.stringmap script "アイアンアクス<wait>"       ; AIANAKuSu         Iron Axe  
.stringmap script "チタニウムソード"            ; TiTaNiUMuSo-Do    Titanium Sword  
.stringmap script "セラミックソード"            ; SeRaMituKuSo-Do   Ceramic Sword  
.stringmap script "ニードルガン<wait>　"       ; Ni-DoRuGaN        Needle Gun 
.stringmap script "サーベルクロー<wait>"        ; Sa-BeRuKuRo-      Sabre Claw   
.stringmap script "ヒートガン<wait>　　"      ; Hi-ToGaN          Heat Gun  
.stringmap script "ライトセイバー<wait>"        ; RaIToSeIBa-       Light Sabre   
.stringmap script "レーザーガン<wait>　"      ; Re-Za-GaN         Laser Gun
.stringmap script "ラコニアンソード"             ; RaKoNiANSo-Do     Laconian Sword   
.stringmap script "ラコニアンアクス"           ; RaKoNiANAKuSu     Laconian Axe
.stringmap script "レザークロス<wait>　"       ; ReZa-KuRoSu       Leather Clothes 
.stringmap script "ホワイトマント<wait>"        ; HoWaIToMaNTo      White Mantle (Cloak)   
.stringmap script "ライトスーツ<wait>　"       ; RaIToSu-Tu        Light Suit  
.stringmap script "アイアンアーマー"            ; AIANA-Ma-         Iron Armour  
.stringmap script "トゲリスノケガワ"           ; ToGeRiSuNoKeGaWa  Spiky Squirrel Fur 
.stringmap script "ジルコニアメイル"           ; ZiRuKoNiAMeIRu    Zirconain Mail
.stringmap script "ダイヤノヨロイ<wait>"        ; DaIYaNoYoRoI      Diamond Armour   
.stringmap script "ラコニアアーマー"             ; RaKoNiAA-Ma-      Laconian Armour   
.stringmap script "フラードマント<wait>"       ; HuRa-DoMaNTo      Frad Mantle
.stringmap script "レザーシールド<wait>"        ; ReZa-Si-RuDo      Leather Shield   
.stringmap script "アイアンシールド"           ; AIANSi-RuDo       Iron Shield
.stringmap script "ボロンシールド<wait>"       ; BoRoNSi-RuDo      Boron/Bronze Shield  
.stringmap script "セラミックノタテ"            ; SeRaMituKuNoTaTe  Ceramic Shield  
.stringmap script "アニマルグラブ<wait>"      ; ANiMaRuGuRaBu     Animal Glove 
.stringmap script "レーザーバリア<wait>"       ; Re-Za-BaRiA       Laser Barrier  
.stringmap script "ペルセウスノタテ"           ; PeRuSeUSuNoTaTe   Shield of Perseus
.stringmap script "ラコニアシールド"            ; RaKoNiASi-RuDo    Laconian Shield  
.stringmap script "ランドマスター<wait>"       ; RaNDoMaSuTa-      LandMaster  
.stringmap script "フロームーバー<wait>"       ; HuRo-Mu-Ba-       FlowMover
.stringmap script "アイスデッカー<wait>"        ; AISuDetuKa-       IceDecker   
.stringmap script "ペロリーメイト<wait>"       ; PeRoRi-MeITo      PelorieMate  
.stringmap script "ルオギニン<wait>　　"      ; RuOGiNiN          Ruoginin  
.stringmap script "スーズフルート<wait>"       ; Su-ZuHuRu-To      Soothe Flute  
.stringmap script "サーチライト<wait>　"       ; Sa-TiRaITo        Searchlight  
.stringmap script "エスケープクロス"           ; ESuKe-PuKuRoSu    Escape Cloth 
.stringmap script "トランカーペット"            ; ToRaNKa-PetuTo    TranCarpet  
.stringmap script "マジックハット<wait>"       ; MaZituKuHatuTo    Magic Hat  
.stringmap script "アルシュリン<wait>　"      ; ARuSiyuRiN        Alsuline
.stringmap script "ポリメテラール<wait>"        ; PoRiMeTeRa-Ru     Polymeteral  
.stringmap script "ダンジョンキー<wait>"       ; DaNZiyoNKi-       Dungeon Key  
.stringmap script "テレパシーボール"           ; TeRePaSi-Bo-Ru    Telepathy Ball
.stringmap script "イクリプストーチ"             ; IKuRiPuSuTo-Ti    Eclipse Torch   
.stringmap script "エアロプリズム<wait>"       ; EARoPuRiZuMu      Aeroprism  
.stringmap script "ラエルマベリー<wait>"       ; RaERuMaBeRi-      Laerma Berries  
.stringmap script "ハプスビー<wait>　　"      ; HaPuSuBi-         Hapsby  
.stringmap script "ロードパス<wait>　　"      ; Ro-DoPaSu         Roadpass  
.stringmap script "パスポート<wait>　　"      ; PaSuPo-To         Passport  
.stringmap script "コンパス<wait>　　　"     ; KoNPaSu           Compass
.stringmap script "ショートケーキ<wait>"        ; Siyo-ToKe-Ki      Shortcake 
.stringmap script "ソウトクノテガミ"             ; SoUToKuNoTeGaMi   Commander-General's Letter   
.stringmap script "ラコニアンポット"           ; RaKoNiANPotuTo    Laconian Pot 
.stringmap script "ライトペンダント"           ; RaIToPeNDaNTo     Light Pendant 
.stringmap script "カーバンクルアイ"           ; Ka-BaNKuRuAI      Carbunckle Eye
.stringmap script "ガスクリア<wait>　　"       ; GaSuKuRiA         GasClear   
.stringmap script "ダモアクリスタル"           ; DaMoAKuRiSuTaRu   Damoa's Crystal
.stringmap script "マスターシステム"            ; MaSuTa-SiSuTeMu   Master System 
.stringmap script "ミラクルキー<wait>　"       ; MiRaKuRuKi-       Miracle Key  
.stringmap script "ジリオン<wait>　　　"     ; ZiRiON            Zillion
.stringmap script "ヒミツノモノ<wait>　"        ; HiMiTuNoMoNo      Secret Thing  
